### ISSUE TITLE
Clipboard copies only plaintext between Mac and Windows

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#2909]
**Imported issue:**

* Author: Pieter Van Nuffel
* Date: 2011-09-16 15:07:23
* Legacy ID: 2978
* Version: 1.4.2

**Steps to reproduce:**  
  
1. Select a block of text/code in an IDE like IntelliJ, Eclipse or Netbeans and do the copy command  
2. go to the other machine that's connected with synergy  
3. paste the text in an application  
  
Expected: The code or text that was copied from the source should be pasted on the other machine (the color hightlighting from the IDE should not be kept, of course)  
Actual: Nothing happens, the clipboard appears to be empty  
  
Please note that this issue happens in both directions: mac -> windows and windows -> mac  
  
PS This might be a duplicate with Bug 77  
( http://synergy-foss.org/pm/issues/77 )  
  
**Versions (Synergy, OS):**  
  
Server: Mac OS X 10.6, synergy 1.4.2 or 1.4.4   
(IntelliJ 10.5.2 used as my IDE)  
Client 1: Windows XP SP3, synergy 1.4.2 or 1.4.4   
(Netbeans 7.0.1 used as my IDE)  
  
**Workaround:**  
  
It seems that only pure plaintext gets through correctly. The way I copy text between my machines is by copying the block of text needed into a basic text editor such as textwrangler on mac or notepad++ on windows. Then I select the plaintext in that text editor and move my mouse to the other machine. There I paste the text into the other basic text editor. Only then I can select that text again and paste it into my IDE.  
  
I would have liked that any text/code from an IDE would be able to transfer the plaintext itself over to the other machine. Instead, nothing comes through.  
  
**Comments:**  
  
The same issue (trying to copy text that has formatting in it) appears to happen regardless of application. So copying text from a browser like firefox, or document editor such as microsoft word also fails. Only pure plaintext 'survives' the trip between my machines.

**Comment by trombonekenny** [comment]
I'm also seeing this behavior pasting from Windows 7 (client) to Linux RHEL6 (server). Things like Firefox URLs or content needs to be copied to Notepad first, and then re-copied before it can be pasted into the Linux environment. 1.6.2 on both systems.

Pasting a firefox URL from the Linux server to the Windows client directly works.

Bringing this up because I hadn't seen a Linux reference in this thread yet.

**Comment by fwenzel** [comment]
Quick comment that I, too experience this, and my server/client are both Mac OS X 10.10.2, so it does not appear to be a cross-platform issue.

**Comment by mrjester888** [comment]
Still occurring on 1.7.1 between Win8.1 and OSX 10.10.3

**Comment by beeb** [comment]
Same as @mrjester888 I can't copy from Chrome in Windows to anything in Mac using 1.7.1

**Comment by nielsharland** [comment]
Same issue: I'm unable to copy anything but plain-text (Chrome address bar e.g.) on my Synergy 1.7.1 set-up with two OSX 10.10.3 MacBook Pro's.

**Comment by chadmoore** [comment]
1.7.3 still has the problem.   Very frustrating.

**Comment by dragonivre** [comment]
Hello Nick.  In the meaning, copy/paste shortcut doesn't work, but works with mouse.  Do you know when we can expect an update?

**Comment by kariavka** [comment]
1.7.3 Can't copy from Mac (OS X Yosemite 10.10.3) to Windows 8 and to Debian 7 with Fluxbox.

**Comment by cweihnacht** [comment]
I can't copy from Yosemite 10.10.3 Mac Pro to Yosemite 10.10.3 MacBook Pro. I haven't been able to copy-paste anything using either short-cut or context menus. I paid for the pro license and I need this functionality. Please fix!

**Comment by timmerk** [comment]
1.7.3 still has the problem, which was originally reported in 2011.

**Comment by Bradleycorn** [comment]
Agree. Still having this problem on 1.7.3

**Comment by alexciarlillo** [comment]
Still exists in 1.7.4 (linux server, win7 client). I cannot believe this issue has been unresolved for so long. I've stopped recommending synergy to people because of this issue and the developers refusal to address it seriously.

**Comment by rdamon** [comment]
It comes from different key mapping from windows to mac : use ctrl + c on windows and "win/cmd" button + v on mac and the other way around (win+c on mac and ctrl+v on win) works for me. but the ability to remap the command key to ctrl  on the mac side would be a nice to have.

**Comment by alexciarlillo** [comment]
This issue is not related to key mapping. No matter what methods I use to copy and paste (context menu or keyboard shortcuts) nothing is copied from the windows client to the linux server. I can *usually* copy/paste from the linux server to the windows client though.

**Comment by timmerk** [comment]
Yes, I can confirm it's not related to key mapping, as well.

**Comment by beporter** [comment]
@rdamon It **is** possible to remap the <kbd>Ctrl</kbd> and <kbd>Cmd</kbd> keys in the Synergy config file. [Google returns many, many results for this](https://www.google.com/search?q=synergy%20remap%20ctrl%20cmd), and it's also [documented in the wiki](http://synergy-project.org/wiki/Text_Config#screen_options). This is **definitely** not related to the clipboard issues.

**Comment by dfberger** [comment]
Aside from posting here, is there a mechanism to "upvote" this bug for attention?  The lack of cut-and-paste without bouncing through TextEdit/notepad is highly impactful to workflow.

**Comment by cweihnacht** [comment]
Agreed. I'm working between Mac OS X (yosemite) laptop / desktop and I generally have to paste into a text editor and then re-copy my text to get rid of formatting in order to get copy-paste to work.

**Comment by beporter** [comment]
No, there isn't a way to upvote really. People can (and do) pile on to a threads, but that really only serves to distract the developers and ends up being counter-productive. It's up to them to take stock of the bigger picture and decide where their engineering resources are best spent to help the most people. You really just have to live with it until they can find and implement a solution for a particular problem, unfortunately.

**Comment by beporter** [comment]
Or dig into the code and find the solution yourself, of course. :-\

**Comment by thetrevdev** [comment]
Any other recommended workarounds like a supplemental tool that would auto convert clipboard to plaintext or sync my clipboard?

**Comment by cweihnacht** [comment]
I'd also like to add as a side issue (not sure if this has been logged) that when I try to copy rich text between yosemite laptop & yosemite desktop, if will often stop synergy from working and I have to restart my client and server.

**Comment by gomker** [comment]
I have always experienced this issue between two Windows Machines, not just when dealing with Mac - currently running the latest synergy builds on Windows 10

Is there a way to change the title of this or should we be opening another issue?

**Comment by beporter** [comment]
@gomker There are actually a ton of issues, both open and closed, related to the clipboard. *This* issue might not exactly match your setup, but one of the others probably does. (See my [huge roundup post](https://github.com/synergy/synergy/issues/4735#issuecomment-108422245) that's probably a little out of date by now.)

In any case though, it's already a "known issue" so there isn't much to do but wait for the developers to get to it. Opening a new issue would only add to the noise and administrative work they have to deal with and that takes away from them fixing bugs. :wink:

**Comment by XinyuHou** [comment]
Hi Guys, please try out our 1.7.5 release to see if it fixes this problem.

**Comment by Bradleycorn** [comment]
I installed 1.7.5 on both my OSX (10.10.5) client and Windows 7 server ...
I still cannot copy/paste rich text from the Windows Server to the OSX
client. I can copy/paste plain text, and I can copy/paste from the OSX
client to the Win7 server. But the problem of pasting rich text from the
Win7 server to the OSX client remains.

**Comment by XinyuHou** [comment]
Can anyone test this nightly to see if the problem persists?
http://synergy-project.org/nightly?filter=synergy-v1.7.6-rc1-abba6

**Comment by Bradleycorn** [comment]
I can test it, but it won't be until next Monday, Nov. 30th.

**Comment by livejamie** [comment]
@XinyuHou Still not copying with the formatting

**Comment by XinyuHou** [comment]
@livejamie 
What platforms are you using?

Sorry if you have mentioned it before.

**Comment by livejamie** [comment]
OS X 10.11.2B and Windows 10 Pro

**Comment by XinyuHou** [comment]
@livejamie 
Please try this nightly
http://synergy-project.org/nightly?filter=synergy-v1.7.6-rc1-39d3c31

**Comment by Bradleycorn** [comment]
sorry for the delay. I just tried the nightly from here:
http://synergy-project.org/nightly?filter=synergy-v1.7.6-rc1-abba6

Same problem persists.
Win7 Server
OSX10.10 Client

Would it be helpful if I put the logs on debug mode and sent a log file?

**Comment by XinyuHou** [comment]
@Bradleycorn 

Please try this nightly.
http://synergy-project.org/nightly?filter=synergy-v1.7.6-rc1-39d3c31

If you still experience some problems, please sent the log from both server and client

**Comment by XinyuHou** [comment]
Hey guys,

Please try this nightly.
http://synergy-project.org/nightly?filter=synergy-v1.7.6-rc1-5287c62

**Comment by thetrevdev** [comment]
Not working for me from server to client with rich text.
Windows 7 Server
OSX 10.9 Client
synergy-v1.7.6-rc2-a5acb0

**Comment by timmerk** [comment]
Confirmed; not working.

**Comment by XinyuHou** [comment]
@thetrevdev 
Please send us some log. Debug level should be enough.

**Comment by XinyuHou** [comment]
@timmerk 
What platforms are you using?

Some log info would be helpful.

**Comment by pvannuff** [comment]
I just tried the new 1.7.6 RC2 and at first it looked like Windows client -> Mac server worked, but not the other way. Then I tried one of my earlier remedies by doing a copy, then a mouse click on a random spot before going over with my mouse to the other screen, which did seem to work.
(Please note I have a keyboard on both computers/screens, so I use the cmd-c or ctrl-c on the respective machine, only the mouse is moving about.)
I would love it if I did not need to the mouse click in between though.

My current setup (which has obviously changed a bit since my initial bug report in 2011):
Mac (server) OS X 10.10.5
Windows (client) 7

I've configured my client and server to generate debug logging and while 'stress testing' I didn't see any issues up to now, strangely. I'll keep trying but it would seem like some of the general use cases are fixed but some edge cases remain.

**Comment by XinyuHou** [comment]
@pvannuff 
> Then I tried one of my earlier remedies by doing a copy, then a mouse click on a random spot before going over with my mouse to the other screen, which did seem to work.
This is interesting!

There are so many facts that could cause clipboard not working. Please send us some logging from both your server and client sides.

**Comment by pvannuff** [comment]
Here's some further testing I did, in detail:

09h32:
mac text select (from comment thread) and cmd-c
move mouse to windows
open notepad++ extra tab
ctrl-v
-> nothing happens

9h34: second attempt, exact same action (notepad++ tab still open) -> worked perfectly

9h35: 
rich text select from windows
ctrl-c
mouse move over to mac
open new textwrangler window
cmd-v
text arrives

9h36: both client and server restart to try to get an error condition again
rich text select on mac
cmd-c
move over to windows
delete content in open notepad++ tab
ctrl-v -> nothing happens
move back to mac
do a new cmd-c
click on random spot
move to windows
ctrl-v
text arrives


9h39: another restart of client and server
here I did the same mac text-copy and move to windows, but notepad++ showed me the 'content changed in a tag, reload?' dialog so I needed to do a click
then the text arrived perfectly

So I would state doing my intermediate clicks before/after moving over to the other screen seems to be a workaround or a helpful action to make sure the clipboard moves over correctly

[synergy - mac server.txt](https://github.com/synergy/synergy/files/59167/synergy.-.mac.server.txt)
[synergy - windows client.txt](https://github.com/synergy/synergy/files/59168/synergy.-.windows.client.txt)

**Comment by Bradleycorn** [comment]
I just installed synergy-v1.7.6-rc2-a5acb08
<http://synergy-project.org/files/nightly/synergy-v1.7.6-rc2-a5acb08-Windows-x64.msi>


I used the Windows x64.msi and the MacOSX1010-x86_64.dmg

I am running Windows 7 as the server and Mac OSX 10.10.5 as the client.

*I am happy to report that Copy/Paste IS working again for me*! I tried
copying both plain text AND rich text (copied content from a web page in
Chrome, email text from MS Outlook, and text from a MS Word document) and
all pasted fine in my OSX client. Also tried some limited plain and rich
text copy/pasting from the OSX client to the Win7 server and it also worked
fine.

Hooray!

**Comment by krislindgren** [comment]
I can confirm the same as Bradleycorn.  My setup is exactly the same.

1.7.6 rc2-a5acb08 worked both ways.  rc3 doesn't work for me.

**Comment by pvannuff** [comment]
I just noticed another strange behaviour. I just did a copy of some SQL query results in the (java based) SQL developer app on mac into TextWrangler (which is a text editor), since I'm used to doing this to get copies over to my windows computer. After having the text in TextWrangler I do a new copy of that and move over to windows to do a paste in Notepad++.
The paste did nothing so I attempted this same flow from TextWrangler to Notepad++ with no avail. When I then did a ctrl-c of absolutely nothing (no selection active) in notepad++ on windows but then doing a paste, suddenly the data from the mac did appear. 

Very strange, especially since this is all plaintext anyway. Not sure if this helps in finding all special cases surrounding this issue, though.

I'm still using RC2 since I did not see any relevant code changes in RC3 for my platforms (but this was some time ago so I might be mistaken about that). Still having the mac as the server and windows as the client.

**Comment by XinyuHou** [comment]
@krislindgren 
Thank you for the information.

1.7.6-rc3 is almost identical to 1.7.6-rc2 except a memory leak fix which should not affect any clipboard issue.

Try use rc2 for a while and switch to rc3, the clipboard issues are mostly random.

**Comment by pvannuff** [comment]
I'm a bit sad to see the 1.7.6 version being released today, without actually fully fixing this issue.
I have no idea how many people are affected by this copy-paste bug (on any combination of platforms), but my initial issue is still not resolved.

I guess this has mostly to do with the variety of applications I use such as programming IDE, database client, text editors and browsers. They all use the system clipboard in slightly different ways, which is the most likely cause why synergy does not properly read/write to all of those buffers.
(At least that's my understanding after following this and other threads about this issue.)

Creating a new bug (which would be pretty much a duplicate of this one) won't help I guess, since it would be closed immediately anyway, right? :-(
