### ISSUE TITLE
Cannot connect with encryption

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#3730]
**Imported issue:**

* Author: Hong-Leong Ong
* Date: 2013-10-29 01:44:15
* Legacy ID: 3800

**Steps to reproduce:**

1. Enable encryption on both client and server
2. Connection will fail
3. Disable encryption on both client and server
4. Connection will succeed

Expected: Connection from client to server to succeed

Actual: Connection from client to server failed

**Versions and operating systems:**

Upgraded synergy (1.4.14-1 -> 1.4.15-1) with pacman on 64-bit Arch Linux, which is the synergy server.

Also upgraded client PC (Win7 32-bit) to the latest Synergy v1.4.15.

After that, the client can no longer connect to server with encryption enabled. Once encryption is disabled on both client and server, connection is successful.

**Temporary workarounds:**

Disable encryption.

**Comment by bwilson** [comment]
I can also confirm this bug with Synergy 1.6.3. Server: Ubuntu 14.10. Client: Ubuntu 14.04. Hope that helps.

**Comment by cledoux** [comment]
Another confirmation on Synergy 1.6.3. Server: Linux Mint 17. Client: Windows 8.1.

dmesg gives me similar message to pvtischler.

**Comment by Ustabil** [comment]
Another confirm.
Running Synergy 1.6.3. Server (64bit): Windows 7. Client: Ubuntu 14.04.2 LTS
Client starts and just stops with "connecting to <IP>" when encryption is on, no other errors. Turning encryption off works without problems.

Recompiling 1.6.3 (client) solved the issue. Server installed from installer.

**Comment by dbergamini** [comment]
I am able to reproduce with Ubuntu 14.04 LTS 64-bit server running 1.6.3 and Windows 8.1 64-bit client running 1.6.3. Reverting the Ubuntu box to 1.6.2 seems to do the trick. Can we get a recompile? I can probably just wait until 1.6.4 comes out.

Daniel

**Comment by nbolton** [comment]
I'm really sorry to tell you this, but 1.6 and legacy encryption are no longer supported.
