### ISSUE TITLE
Missing MinGW dependencies after install on Windows

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#3774]
Note: A fix is available.

--

**Imported issue:**

* Author: Jason Woodall
* Date: 2013-11-27 22:03:59
* Legacy ID: 3844

**Steps to reproduce:**

1. turned on my computer (Windows 7 Professional, Lenova w530, 64 bit SSD drive)
2. Double click on the Synergy.exe desktop icon
3. get "synergy.exe - System error: The program can't start because mingwm10.dll is missing from your computer."

Expected: mingwm10.dll should be included in the build

Actual: synergy.exe - System error: The program can't start because mingwm10.dll is missing from your computer.

**Versions and operating systems:**

Windows 7 Professional, Lenova w530, 64 bit SSD drive

**Temporary workarounds:**

I had this issue once before, uninstalled and reinstalled (Get error opening file for writing C:\Progam Files\Synergy\synwinxt.dll during install), unlocked that dll (explorer had it locked), deleted it, uninstalled again, did a fresh install.  Synergy works again.

**Similar bugs:**

#2733 http://synergy-foss.org/spit/issues/details/2733/
**Additional comments:**

I develop in Qt, but in Visual Studio not Mingw, so not sure if changing Qt versions may have precipitated this issue.

**Comment by mrramsey** [comment]
@porear This is also what i had to do on my machines.

**Comment by joelmale** [comment]
Just had the same problem, but even with Comodo turned off I still could not get the dlls to extract.  Manual extraction solved my problem with 7zip, but I would hope to find a better way to do this in the future.

**Comment by sparrowt** [comment]
Hitting this same issue after installing 1.7.1 (previously had 1.5.1 installed)

**Comment by sparrowt** [comment]
Looking at the windows installer log, it is saying:
```
MSI (s) (A0:68) [22:19:54:016]: Executing op: SetCompanionParent(ParentPath=C:\Program Files\Synergy\,ParentName=synergy.exe,,)
MSI (s) (A0:68) [22:19:54:017]: Executing op: FileCopy(SourceName=eacyhyve.dll|libgcc_s_dw2-1.dll,SourceCabKey=libgcc_s_dw2_1.dll,DestName=libgcc_s_dw2-1.dll,Attributes=512,FileSize=43008,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,Version=GuiProgram,,InstallMode=58982400,,,,,,,)
MSI (s) (A0:68) [22:19:54:213]: File: C:\Program Files\Synergy\libgcc_s_dw2-1.dll;	Won't Overwrite;	Won't patch;	Existing file is unversioned but modified	(Checked using version of companion: C:\Program Files\Synergy\synergy.exe)
MSI (s) (A0:68) [22:19:54:213]: Executing op: SetCompanionParent(ParentPath=C:\Program Files\Synergy\,ParentName=synergy.exe,,)
MSI (s) (A0:68) [22:19:54:213]: Executing op: FileCopy(SourceName=mingwm10.dll,SourceCabKey=mingwm10.dll,DestName=mingwm10.dll,Attributes=512,FileSize=11362,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,Version=GuiProgram,,InstallMode=58982400,,,,,,,)
MSI (s) (A0:68) [22:19:54:215]: File: C:\Program Files\Synergy\mingwm10.dll;	Won't Overwrite;	Won't patch;	Existing file is unversioned but modified	(Checked using version of companion: C:\Program Files\Synergy\synergy.exe)
MSI (s) (A0:68) [22:19:54:215]: Executing op: SetTargetFolder(Folder=C:\Program Files\Synergy\OpenSSL\)
```
so because it apparently finds ``mingwm10.dll`` (and various others) on my machine, it decides not to install them. Indeed the file is in ``C:\MinGW\bin`` however this shouldn't affect whether it's installed in ``C:\Program Files\Synergy`` because what if I uninstalled MinGW afterwards?

``C:\MinGW\bin`` isn't even on my PATH, hence why I get the error message when trying to run Synergy. Somehow windows installer still finds it & therefore fails to install a copy in the Synergy folder which is surely wrong behaviour.

**Comment by sparrowt** [comment]
It seems like [these files](https://github.com/synergy/synergy/blob/master/src/setup/win32/Product.wxs#L108) don't get installed if Windows Installer "cleverly" finds them somewhere else on the system. Perhaps removing the ``CompanionFile`` attribute would help, but Wix bemuses me at best.

**Comment by nbolton** [comment]
@sparrowt `CompanionFile` - good shout! @XinyuHou

**Comment by sparrowt** [comment]
Hmm I'm not sure that will help based on [this](http://wixtoolset.org/documentation/manual/v3/xsd/wix/file.html):
```Set this attribute to make this file a companion child of another file. The installation state of a companion file depends not on its own file versioning information, but on the versioning of its companion parent.```
because in that case it should've installed it. However it's probably worth a try, alternatively we might need to give each of those files a unique ID?

**Comment by sparrowt** [comment]
Yippee, after a day I finally got Synergy compiling... then I removed ``CompanionFile`` from those files and now they are installed correctly. I will do a PR shortly.

**Comment by sparrowt** [comment]
PR here: https://github.com/synergy/synergy/pull/4634

**Comment by jkugler** [comment]
I also had to copy the Qt*.dll files too.

**Comment by sparrowt** [comment]
Yes I think I had to too. The pull request above fixes all of them, would somebody be able to take a look & kick off the relevant build/test? Many thanks.

**Comment by nbolton** [comment]
Fixed by 9893a01

**Comment by nbolton** [comment]
Please test this pre-release to confirm this is ready for release.
http://synergy-project.org/nightly?filter=v1.7.4-stable-ebb7edf

**Comment by notta3d** [comment]
I was having the same issue and I just the latest installer you posted and it resolved the issue for me. Thanks.

**Comment by MikeCockrem** [comment]
Had the exact same issue, 1.7.4 fixed for me also (Win 7 x64)

**Comment by Azbests** [comment]
A little bit late to party, but can also confirm that 1.7.4 installer fixed the issue on win8.1 x64 installation.

**Comment by DragonDon** [comment]
Greetings all.

I just installed Synergy on my Gateway Laptop, first time ever, Comodo running, and ran into the same error.  Seems there's still something up.

How can I help?

**Comment by b3taman** [comment]
Installing the current stable version, I encountered this for the first time as well (been using Synergy through its various incarnations for years).

**Problems**
1. I could not find v1.7.4-stable-ebb7edf as referred above, and installed synergy-v1.7.3-stable-efd0108-Windows-x64.msi.
2. It has the same problem.

**Work-around, plus another problem**
1. Uninstall the current stable Synergy.
2. Install the newer one as above.
3. Open the MSI in 7-zip and copy the whole lot to the installation directory (C:\Program Files\Synergy), ignoring an error about the directory being open.
4. Rename libgcc_s_dw2_1.dll to libgcc_s_dw2-1.dll.

That got me to the point of being able to configure it. I still have to test it in use.

**Comment by metawolf** [comment]
I think this issue should be reopened.  I just ran into it while installing synergy-v1.7.4-stable-c734bab-Windows-x64.msi on Windows 7 Ultimate 64-bit.  I previously had Synergy installed on this machine, but uninstalled it due to some issues with a previous version.

I installed Synergy using above installer and received this error when launching it.  I then uninstalled it, rebooted, and deleted the following registry keys: HKCU\SOFTWARE\Synergy & HKLM\SOFTWARE\Synergy.  I reinstalled using the same installer and received this same error again.  I was able to resolve by copying the missing dlls to the Synergy installation folder.

**Work-around for 1.7.4 64-bit installer**
1. Open MSI in 7-zip
2. Copy the following files to installation directory (C:\Program Files\Synergy)
     a. libgcc_s_dw2_1.dll
     b. mingwm10.dll
     c. QtCore4.dll
     d. QtGui4.dll
     e. QtNetwork4.dll
3. Rename libgcc_s_dw2**_1**.dll to libgcc_s_dw2**-1**.dll

**Comment by sparrowt** [comment]
@metawolf it appears to have been reverted from 1.7.4 and the milestone is now 1.8.0-beta, so I guess you'll need to either wait for 1.8.0 or download the nightly build

**Comment by TheSmartGerman** [comment]
@metawolf 
Got the same Problem, your work arround works for me too.
OS: Win7 64x Pro
Installer: synergy-v1.7.4-stable-c734bab-Windows-x64.msi

**Comment by FredStein** [comment]
Having the same problem.  Have spent a VERY frustrating evening of lost production. Nick, this issue has been around for years.  If I wanted to run the kind of futzing around above I'd be doing PRODUCTIVE work on my linux machine. Putting sprint-must and priority-urgent on two weeks ago is too little too late.  Synergy is a great utility.   Until this catastrophe one I WAS going to recommend for a high end simulation environment.  Until you guys address quality issues you are not going to get serious commercial clients.  Dropped the ball my man.

**Comment by denormalizer** [comment]
Would like to report that this issue is happening on Synergy v 1.7.5 - on Windows 10.

I also run Comodo. An previously I've had to disable Comodo to install Synergy.

This time, it seems, disabling Comodo still doesn't seem to rectify the issue.

**Comment by AVOlight** [comment]
just bought this and had this issue on latest stable, on windows 10 64bit with just comodo firewall so?
@metawolf  thanks for fix, didn't know one could just open up a msi with 7-zip

**Comment by ThyRaven13** [comment]
This is still an issue today.  I've tried both the stable version 1.7.5 32 and 64 bit and also the beta 1.8.0 32 bit and 64 bit.  All installers having an issue with placing all the .dll files.  Unable to extract and place them in correct locations so I am unable to use the app.  Any advice?

Using Windows 10 Pro x64 on desktop and laptop.  Also have a Windows 7 Pro 32 bit desktop.  The Windows 10 Pro x64 Desktop is the server.

**Comment by jarrodhroberson** [comment]
This appears to be broken again, I can not get github desktop to install completely on Windows 10 with the current download as of this post.
