### ISSUE TITLE
Double click & drag doesn't select words on client

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#3784]
**Imported issue:**

* Author: Martyn Haigh
* Date: 2013-12-05 10:48:10
* Legacy ID: 3854

**Steps to reproduce:**

1. Connect Win 8.1 (server) and OSX 10.9 (client)
2. Open a document with a text document (I'm using Sublime Text 2 but my brief testing shows that this manifests regardless of editor)
3. Double click a word and drag to either side

Expected: Text selection should expand/contract 

Actual: Text selection does nothing beyond selection of initial work

**Versions and operating systems:**

Synergy : 1.4.15 on both machines
OSX : 10.9
Win: 8.1

**Temporary workarounds:**

None known

**Similar bugs:**

None known

**Additional comments:**

plugging a mouse in to the mac itself shows that this double click and drag is possible

**Comment by jankcat** [comment]
PR #4261 also seems to fix #3784. 

Tested with build: http://synergy-project.org/nightly?filter=pr-jpmcmu-tripple-click-fix

Video of it working: https://jankcat.com/public/synergy/doubleclickdrag.mov

**Comment by nbolton** [comment]
@jankcat Awesome, thanks for testing.

**Comment by nbolton** [comment]
See #4462
