### ISSUE TITLE
Cursor disappears on clients of high resolution server

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4078]
**Imported issue:**

* Author: Greg Grundy
* Date: 2014-08-30 00:41:43
* Legacy ID: 4148

**Steps to reproduce:**

Install synergy on a high resolution screen server (say 3200 x 1800) and a lower resolution screen client (say 2560 x 1600).
Problem applies to both synergy 1.6.0 and 1.5 

Expected: 
cursor to move seamlessly between displays as the server mouse is moved around

Actual: 
cursor disappears when moved off the server display and can't be restored until synergy on the client is stopped.
Keyboard and mouse scroll wheel activity does seem to transition to the client system as expected.

**Versions and operating systems:**

Synergy 1.6 (but also earlier versions)
Windows 8.1 (as server at 3200 x 1800 resolution)
Ubuntu 14.04 LTS (as client at 2560 x 1600 resolution)
and iMax OSX 10.9.4 or (as client at 1920 x 1200) 

**Temporary workarounds:**

Run synergy as the client on the high resolution display and the server lower resolution system
or
set the resolution on the server to a lower resolution

**Additional comments:**
none

**Comment by the-wes** [comment]
Duplicates https://github.com/synergy/synergy/issues/4041
