### ISSUE TITLE
Separate configuration window

### ISSUE THREAD

**Issue by XinyuHou** [synergy/synergy#4238]
Problem: right now message boxes are over used which makes it look hacky. When a user configures a new client, Synergy would broadcast to notify all the existing servers about its existence. This would cause a dialog pop up on server. In a large local network, it could get really messy.
 
Solution: eliminate the usage of message box. A configuration window that helps users setup their server or client should be shown before the old main window. Zeroconf only advertises the service when configuration window is active.

**Comment by nbolton** [comment]
@XinyuHou Please correct me if I'm wrong, but I'm not sure this is very well defined.
