### ISSUE TITLE
Keyboard not working 90% of the time (Mac server and client)

### ISSUE THREAD

**Issue by igs-awilliams** [synergy/synergy#4278]
Using a Server (OSX 10.9.5) and a Client (OSX 10.10.1) both running Synergy version 1.6.2. The connection is successfully made, the mouse works correctly but the keyboard doesn't.  Sometimes text typed into the client won't appear at all (90%), sometimes it will appear on the server side instead (5%).  When client/server roles are reversed, Synergy works as expected.

**Comment by SynVisions** [comment]
I have an OS X 10.10.1 server and a Windows 8.1 client, the keyboard is not working, but mouse input does. The keyboard input just goes to the OS X server even when the mouse is being directed to the Windows client.

**Comment by pklopping** [comment]
Hey @SynVisions Have you tried using this fix? http://davidvielmetter.com/tips/synergy-keyboard-doesnt-work-on-macbook-pro/

It worked for me.

**Comment by SynVisions** [comment]
Honestly I don't remember how I fixed it, but it's fixed now. I had forgotten that I commented here.

Thanks for the suggestion though.

**Comment by blandman** [comment]
+1

**Comment by CeramicGod** [comment]
I have this issue as well and have discovered that closing Chrome on the Synergy server restores keyboard functionality 100% of the time, at least in my environment.

**Comment by XinyuHou** [comment]
Duplicate to #47

**Comment by nkasmer** [comment]
I have an elementary OS (ubuntu 12.04) PC as a server, and a Win 7 as a client. On my situation the arrow keys and PgUp and PgDown were not working.

The fix was to have the NumLock key off.

**Comment by atnalta** [comment]
I fixed my issue with disabling all autofills inside Safari browser's preference in Mac OS server.
