### ISSUE TITLE
Readme.md references this project as free

### ISSUE THREAD

**Issue by derek-adair** [synergy/synergy#4299]
Probably want to change your README and add licensing stuff!  I believe you want this project to be open source and commercially licensed?

>Synergy is free and open source, so you are free to run it and
redistribute it with or without changes. Just use "hm conf" and
"hm build" to compile (./hm.sh on Linux and Mac).

**Comment by the-wes** [comment]
Would it be sufficient to add "(as in free speech)" after the word free?

**Comment by derek-adair** [comment]
not sure! i dont think the description "synergy is free" is fitting any longer though, i could be wrong...

**Comment by nbolton** [comment]
Fixed in d7fb7b03300abf042b3d5e4e87dd57dc4a60ec5b
