### ISSUE TITLE
Client detected dialog is not shown when Synergy is minimized

### ISSUE THREAD

**Issue by XinyuHou** [synergy/synergy#4307]
Problem: When Synergy is minimized either by user or automatically, server doesn't show any client detected dialog anymore. It is not obvious to users what they need to do next.

Solution: Show Synergy main window and pop up the client detected dialog even when Synergy is minimized. If users find it annoying, they can tick the "Ignore auto connect clients" check box.

**Comment by nbolton** [comment]
+1

**Comment by XinyuHou** [comment]
Fixed by 1f41b92
