### ISSUE TITLE
Hebrew keyboard layout issues ('?' characters and changing the layout on the client)

### ISSUE THREAD

**Issue by eyalzek** [synergy/synergy#4311]
I'm on version 1.6.2, the server is on a Windows 7 machine, client is Xubuntu 14.04.

I have 2 keyboard layouts installed on both machines, English and Hebrew. I'm experiencing the following issues:
1. I am unable to change the keyboard layout to Hebrew on the client (both machines use L-SHIFT+L-Alt to change the layout). When changing it using the client keyboard, as soon as I type a character on the server's keyboard - it'll reset back to English.

2. When my server's layout is set to Hebrew, typing letters on the client produces nothing but question marks. Numbers and characters seem to work fine.

**Comment by nbolton** [comment]
Thanks for contributing to Synergy, @eyalzek. Would you mind splitting your bug report into two separate issues? Only if it makes sense to do so.
