### ISSUE TITLE
Add date and time to log in release mode binary

### ISSUE THREAD

**Issue by dsdee** [synergy/synergy#4312]
I'm trying to track down an issue that is triggered when I'm not at the computer... either at, while, or just after the screen locks.   As such, I'm not in front of the machine to note the exact time that it happens.

I'd like to see the date/time printed in the Log console, and the debug log file, synergy.log, so that I can try to use the data to correlate to the events on the system..

ie, right now, I see: 
INFO: switch from "XXX" to "YYYY" at -1917,-454
INFO: entering screen
INFO: switch from "YYYY" to "XXX" at 1399,575
INFO: leaving screen
INFO: switch from "XXX" to "YYYY" at -1909,-289
INFO: entering screen

I would like to see:

2015-01-06 05:15:00 INFO: switch from "XXX" to "YYYY" at -1917,-454
2015-01-06 05:15:00 INFO: entering screen
2015-01-06 05:15:00 INFO: switch from "YYYY" to "XXX" at 1399,575
2015-01-06 05:18:40 INFO: leaving screen
2015-01-06 05:18:40 INFO: switch from "XXX" to "YYYY" at -1909,-289
2015-01-06 05:18:400 INFO: entering screen

Any chance this could get added in?  It would make this part of debugging my other issue (#4282) easier to provide more data on the issue.

Thanks

**Comment by nbolton** [comment]
Right now this is only turned on in release mode so that the log is easier to read for new users. I think it would be a good idea to make the date/time an option (which is turned off by default).

**Comment by davidmmiller** [comment]
Logs entries should definitely have a timestamp.  They are much less useful for any level user without context as to "when" an event occurred.

**Comment by dsdee** [comment]
This looks like it is now logging the timestamps.  Thanks.
