### ISSUE TITLE
Runtime error, event queue is not ready

### ISSUE THREAD

**Issue by MeyerCoffee** [synergy/synergy#4315]
Trying here to set up a Windows7 64bit as a server and a Mac OSX 10.10 Yosemite as a client.
here is what I got, if the Auto Config box is select:

ERROR: exception on thread 0x00000003: <unknown>
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: event queue is not ready within 5 sec

with the Auto Config Box unselected:
NOTE: started client
NOTE: connecting to '192.168.25.12': 192.168.25.12:24800
2015-01-08 04:42:09.741 synergyc[7432:560451] starting cocoa loop
WARNING: failed to connect to server: Timed out

I try the last stable build and the last night build, and got the same errors on both clients.

Hope that helps.

If I put the mac as server, everything goes smooth. 

(theres any other stable version that might not have this problem? I really need to set up those computers)

**Comment by nbolton** [comment]
@XinyuHou We don't throw this exception any more, right? I think the OP is using an old version.

**Comment by nbolton** [comment]
Duplicates #4276
