### ISSUE TITLE
How to build synergy.exe with gui

### ISSUE THREAD

**Issue by yulin0629** [synergy/synergy#4318]
I can only build this but without gui
![synergy](https://cloud.githubusercontent.com/assets/2434581/5715590/9c05897e-9b16-11e4-801b-75691b21744a.png)

Want to know how to build it with QT

**Comment by digse** [comment]
I have the exact same problem.

After successful build also I can not see synergy.exe .

**Comment by fvetsper** [comment]
did you build with the hm script provided ? what visual studio version you have ?

**Comment by dubuaych** [comment]
I pulled the repository yesterday and managed to build everything just fine under Windows 7 and and Debian Wheezy. Make sure you have the right dependencies for Windows; it's a little bit of trial and error getting your environment variables set up and getting the right versions of things installed, but it does work.

**Comment by johenning** [comment]
The GUI is build seperately. You might try checking the output of the build script for errors that occur after "Build succeeded".

In my case I had not included the path to mingw32-make in my PATH-variable so the core build (apparently qmake) succeeded but the GUI build was not even started.

**Comment by nbolton** [comment]
On Windows, please use...

hm conf
hm build
