### ISSUE TITLE
Files missing errors

### ISSUE THREAD

**Issue by Drumsticks** [synergy/synergy#4322]
I have completely uninstalled the older version of Synergy and made sure the service was deleted as well. I installed v1.6.2 and get errors about files missing. It looks like the installer is buggy. So, I extracted the files from the msi manually and placed them into the Synergy folder. I had to rename one of the files ending _1. with -1, as well.

After this, I kept receiving connection refused. I shut both the client and server off (including service), turned client on first, then the server. Now it is stuck at INFO: crypto mode: cfb and then it Times out, going into an infinite loop between connecting, stopping on crypto line and then timing out.

Both client and server are updated to 1.6.2

Please assist us in this matter quickly as I use Synergy for work.

**Comment by nbolton** [comment]
@the-wes This one looks like a support issue, please could you take over?

**Comment by nbolton** [comment]
@the-wes @speaker

**Comment by the-wes** [comment]
The DLL files missing is a problem with the Comodo anti-virus software, it seems to block the DLLs being copied to the Synergy folder.

Connection timeouts are usually due to a firewall blocking the connections.

**Comment by nbolton** [comment]
Thanks @the-wes
