### ISSUE TITLE
Fast cursor on Linux client when using Retina on Mac server

### ISSUE THREAD

**Issue by dobkeratops** [synergy/synergy#4324]
[snip] "cursor will move much faster in the linux desktop. "

sometimes when using a retina macbook pro as the server and a linux desktop with standard monitors (multi monitor setup, 2x1920x1200+1920x1080, another 1920x1080 overlapped with one) , sometimes it works perfectly, with consistent cursor speed between them; other times, the [snip]

I guessed when its' working right, its' compensating correctly for the retina scaling, whilst other times it might not be. (does synergy itself know about this or is it just transparently handled by the OS?)

But having said that, the scaling is sometimes inconsistent, almost looking like its moving 4x as  fast, not just 2x.  
Sometimes merely restarting the client on the linux machine fixes it.

Are there any options I might be missing that would help it out, is it a known issue ? 

How is pointer acceleration handled.. I know mac's tend to have quite high mouse-acceleratoin, perhaps its' a glitch due to that. (perhaps the cursor is being held in a state where it thinks it's permanently accelerated)

I wondered if I might have multiple copies of synergy launched (leftover from initialise scripts i might have lost track of..), and it was doubling or quadrupling the mouse move messages or something like that. (and 'restart' works by killing those)

**Comment by nbolton** [comment]
Related to #451 or #304?

**Comment by nbolton** [comment]
Duplicates #451
