### ISSUE TITLE
Separate mousebutton options per screen

### ISSUE THREAD

**Issue by dsl101** [synergy/synergy#4331]
I have 2 clients, one OSX and one Win8 running off a Win8 server. The 2 clients need different `mousebutton()` settings for the back/forward buttons to work properly in Chrome - `WWWBack` / `WWWForward` don't work on OSX, and `control+BracketL` / `control+BracketR` don't work on Win8.

I had hoped the `[,screens]` option to `keystroke()` would help here, but it seems like that serves a different purpose. Would it be possible to allow the `mousebutton()` option within the screens section, to define per-screen mappings? Or perhaps there's some other way to do this that I couldn't find?

**Comment by nbolton** [comment]
@the-wes @speaker

**Comment by the-wes** [comment]
There is a feature request which I believe covers this case:

https://github.com/synergy/synergy/issues/576

Please clarify if there is something further which isn't covered there.
