### ISSUE TITLE
Config script suggests old Qt version

### ISSUE THREAD

**Issue by johenning** [synergy/synergy#4332]
in synergy/ext/toolchain/commands1.py
Line 212: w32_qt_version = '4.6.2'

I am pretty sure that synergy (at least the gui) can't be compiled with that version.

**Comment by nbolton** [comment]
We're very behind with Qt on Windows. Our Windows build machine uses "2010.02"

```
C:\Users\Synergy>C:\Qt\2010.02\qt\bin\qmake --version
QMake version 2.01a
Using Qt version 4.6.2 in C:/Qt/2010.02/qt/lib
```

So, yeah, we're on 4.6.2 (for Windows). I think Linux is at a similar version, but on our Mac build machine we're on 5.4.1 (to comply with the Apple deployment stuff).

```
ws3:~ nick$ qmake -v
QMake version 3.0
Using Qt version 5.4.1 in /Developer/Qt5.4.1/5.4/clang_64/lib
```
