### ISSUE TITLE
Will synergy have a android client?

### ISSUE THREAD

**Issue by Tedxz** [synergy/synergy#4333]

**Comment by morganestes** [comment]
http://synergy-project.org/wiki/Android_Client says yes but it
> Requires a modded Android with access to `/dev/uinput` (Like Cyanogen).

**Comment by Tedxz** [comment]
thank you, and how about rooted device with original android?

**Comment by morganestes** [comment]
Try the F-Droid repository and see if it works on your device. https://f-droid.org/repository/browse/?fdfilter=synergy&fdid=org.synergy

**Comment by dragon788** [comment]
I would highly recommend checking out this app. https://play.google.com/store/apps/details?id=com.liveov.skm&hl=en 
Sources: https://sites.google.com/site/droidskm/

**Comment by morganestes** [comment]
@dragon788 That looks like a PC-only competitor to Synergy. Not sure this is the best place to promote it...

**Comment by dragon788** [comment]
Agreed that ShareKM is Windows + Android only, but its an option. I personally would grab the Synergy apk from the "official" file repo rather than f-droid, as they aren't an official app store. http://sourceforge.net/projects/synergyandroid/files/

**Comment by nbolton** [comment]
We plan to spend some R&D time on this. Our best solution might be to emulate a Bluetooth HID from the server computer.
