### ISSUE TITLE
Dual screen support

### ISSUE THREAD

**Issue by dpedu** [synergy/synergy#4335]
Currently, the following setup is impossible:

- 3 Systems
- 4 Monitors in 2x2 grid
- Master system controls the top two monitors
- Bottom two monitors are separate clients

It seems that synergy cannot handle having two clients share the space below another.

**Comment by beporter** [comment]
It used to be possible using the old, manual config files and something like this:

**sample synergy.conf**:
```
# Physical monitor arrangement, with machine names as used by Synergy.
#  +----------+----------+
#  | top (L)  | top (R)  |
#  |          |          |
#  +----------+----------+
#  | client-1 | client-2 |
#  |          |          |
#  +----------+----------+

section: screens
	top:
	client-1:
	client-2:
end
section: links
	top:
		down(0,50) = client-1
		down(51,100) = client-2
	client-1:
		up = client-1(0,50)
		right = client-2
	client-2:
		up = client-1(51,100)
		left = client-1
end
```

The idea is that you could "slice" the bottom edge of your master system in half, and point the left half to one client, and the right half to the other client. This may be dependent on how Synergy counts your dual-monitor's desktop size, but based on my experience with another of Synergy's unusual behavior (#3744), it should work in your favor.

I honestly haven't tried to see if this is still respected in the "auto-config" versions (1.6+) released in the past few years.

_(The [current wiki](http://synergy-project.org/wiki/Text_Config) isn't as fully fleshed out, so I used [this old doc](http://synergy2.sourceforge.net/configuration.html) for reference.)_

**Comment by dpedu** [comment]
Thanks for the info, I'll try that out.

**Comment by speaker** [comment]
dpendu,

Did that solve the issue for you?

**Comment by dpedu** [comment]
@speaker - it did, thanks!

**Comment by nbolton** [comment]
@speaker I guess this is closed? I'll remove the bug and enhancement labels, since these are generally reserved for feature requests or bug reports.
