### ISSUE TITLE
'hm package win' error with Microsoft Visual C++ 2008 Express Edition

### ISSUE THREAD

**Issue by tsaiid** [synergy/synergy#4336]
I tried to build Synergy in WinXP (x86) with Microsoft Visual C++ 2008 Express Edition. `hm build` succeeded after adding a `stdint.h` header file, but while building the installer with `hm package win`:

```
Mapping command: package -> dist
Setting environment for using Microsoft Visual Studio 2008 x86 tools.
vcbuild.exe : warning VCBLD6002: invalid option /p:DefineConstants=Version=1.7.0 specified.  The option was ignored.
Error: project file 'synergy.sln' was not found or not a valid project file.
Error: Microsoft compiler failed with error code: -1
```

It seems that project file 'synergy.sln' is for VC++ 2010. But I cannot build with VC++ 2010 either due to missing merge modules in Visual C++ 2010 Express: `C:\Program Files\Common Files\Merge Modules\Microsoft_VC100_CRT_x86.msm`.

Is there any solution?

**Comment by tsaiid** [comment]
I found somewhere to get `Microsoft_VC100_CRT_x86.msm`, but I think a better solution is to use Express 2013 for Windows Desktop (it contains merge module) to compile and build the package. However, a patch is needed (see pull request #4220 ). Besides, the WiX Toolset setting `src/setup/win32/Include.wxi` should also be changed. (see [this gist](https://gist.github.com/tsaiid/c3e9c56742672a4a047e))

**Comment by nbolton** [comment]
> It seems that project file 'synergy.sln' is for VC++ 2010.

Ah yeah, so I think the issue here is that you need VS Pro for the merge modules (unless the dev doesn't mind manually hunting them down), not much we can do about that.

> (see this gist)

Thanks for the gist, much appreciated, but we don't have time right now to upgrade our build machines and dev environment (but it is planned).
