### ISSUE TITLE
AltGr not sent to Linux client from Windows server

### ISSUE THREAD

**Issue by gosukiwi** [synergy/synergy#4339]
I'm using spanish keyboard and Windows 10 as my server, for characters like `{` and `}` I use AltGr-`´`, but on the linux client, AltGr is just recognized as a regular Alt, thus I cannot make a bunch of characters. 

I googled and found a similar issue but it was on Linux host. 

Synergy version: 1.7

**Comment by nbolton** [comment]
Related: #3929, #3327
