### ISSUE TITLE
Feature Request: Black and White Menu Bar Icon (Mac)

### ISSUE THREAD

**Issue by redbassett** [synergy/synergy#4351]
I use almost entirely black and white menubar icons. Could an option be added to use one for Synergy as well?

**Comment by feekApp** [comment]
+1
and dark mode support!
tnx feek

**Comment by romanzolotarev** [comment]
@nbolton Something like this would be nice to have.
![image](https://cloud.githubusercontent.com/assets/29062/6241451/c8e73f6e-b74f-11e4-9c7e-0b34474b3440.png)

What do you think?

**Comment by redbassett** [comment]
I like those icons.

**Comment by nbolton** [comment]
Duplicates #3791

**Comment by redbassett** [comment]
Thanks @nbolton!
