### ISSUE TITLE
Large clipboard causes crash

### ISSUE THREAD

**Issue by blockloop** [synergy/synergy#4353]
Server: OSX Yosemite
Client: Windows 7

Actions to reproduce:

1. Copy a large image on the server to clipboard (Mine was ~7MB)
1. Move your mouse to the client
1. Synergy locks up for a few seconds
1. The server instance crashes 

Once I cleared the image from the clipboard it no longer crashes

**Comment by venuur** [comment]
I am experiencing the same issue.

Server: Windows 7
Client: Ubuntu 12 LTS

I copy ~30000 rows of an Excel spread sheet and I receive an error message saying 'unknown exception', and my computer freezes.

**Comment by adfaklsdjf** [comment]
I am able to reliably reproduce a crash of the Windows 7 Synergy (server) service by copying the contents of the attached text document into clipboard and trying to mouse over to an OSX Yosemite client.

Both server and client are running v1.7.4 of Synergy.  The crash seems reliable for me even after freshly booting both server and client.

Can other people try the contents of this file on whatever platforms and see if it reliably causes problems for them on their platform?   I'm not a Synergy-grade developer but I am a web developer and I know reliably reproducing a problem is a key step in debugging it.

https://dl.dropboxusercontent.com/u/1589876/caffeine_html_breaks_synergy.txt


Details:
I restart the Windows service using the "Services" menu connect with client, then copy the text to clipboard from a text editor (Sublime seems slightly more reliable, but notepad.exe usually works too) and mouse over to the client and the service crashes.  Smaller amounts of text don't always crash the service completely, often the network connection just crashes and the client reconnects when it notices it's lost connection, but trigger it a few times and the Windows service will crash and need to be restarted before Synergy will work agian.

**Comment by XinyuHou** [comment]
Can anyone test this nightly to see if the problem persists?
http://synergy-project.org/nightly?filter=synergy-v1.7.6-rc1-abba6

**Comment by XinyuHou** [comment]
@adfaklsdjf 

Please try this nightly
http://synergy-project.org/nightly?filter=synergy-v1.7.6-rc1-39d3c31

**Comment by sruffell** [comment]
I just installed 1.7.6-rc1 on my machines (the version in the client is only showing 1.7.6, so not sure how to tell an rc2 apart from this one...).

With just the rc1 installed on my linux server, I was still able to get a crash when cutting and pasting a large amount of text from OSX client.  When both machines where updated and restarted. It appeared that I was able to cut and paste a large amount of text between machines without crashing.  I'll run with this one awhile and report back later.

**Comment by MyXelf** [comment]
Server: Kubuntu Linux - 15.04 (amd64)
Client: Windows 7 Ultimate (x64)

I installed the recommended build (synergy-v1.7.6-rc1-abba638-Windows-x64) and on the Linux side I'm running a different RC1 (synergy-v1.7.6-rc1-c97bd2c-Linux-x86_64.deb). I can tell that a lot of less crashes are happening on the Windows side, and I'm able to copy/paste text from either machine to the other side. There were a lot of times I copied text from one side, and nothing would be pasted in the other side. Haven't happened with the mentioned environment.

Some crashes are still happening in the Windows side, but I can't tell for sure they are related to this issue.

HTH

**Comment by XinyuHou** [comment]
@MyXelf 

Please use Debug2 log level and log to file feature in settings. If a crash happens again, please send us the log file.

**Comment by XinyuHou** [comment]
Hey guys,

Please try this nightly.
http://synergy-project.org/nightly?filter=synergy-v1.7.6-rc1-5287c62

**Comment by Nairou** [comment]
I finally got it to crash while running it in debug2 mode, running 1.7.6-rc1. It occurred while copying text from a Windows client and trying to paste it on the Linux server. Here is what the server spit out:

```
[2015-12-27T00:05:33] DEBUG1: request for clipboard 1, target _VIMENC_TEXT (494) by 0x0100d98b (property=GDK_SELECTION (305))
[2015-12-27T00:05:33] DEBUG1: success
[2015-12-27T00:05:33] DEBUG1: clipboard: setting property on 0x0100d98b,494,305
[2015-12-27T00:05:33] DEBUG1: clipboard: sending notify to 0x0100d98b,494,305
[2015-12-27T00:05:33] DEBUG2: properties of 0x0100d98b:
[2015-12-27T00:05:33] DEBUG2: read property 305 on window 0x0100d98b: bytes=1512
Segmentation fault (core dumped)
```
