### ISSUE TITLE
Mouse doesn't display intermitently

### ISSUE THREAD

**Issue by felipe-lavratti** [synergy/synergy#4355]
Using two ubuntus x64 as server and client.

On the server, mouse pointer is always visible when the control is in the server.
When the pointer is sent to the client system, not always it is visible, frequently it shows no pointer in the client but the OS show mouse hover events. To get the mouse pointer displaying again in the client it is necessary to bring it back to the server and then to the client once again.

What extra info should I provide?

**Comment by nbolton** [comment]
Related? #2754

**Comment by felipe-lavratti** [comment]
Yes, it is the same as described by
​
Bobbejaan Jansen below:

" (quote from https://github.com/synergy/synergy/issues/2754)

   - Author:
   ​​
   Bobbejaan Jansen
   - Date: 2014-06-12 19:44:16

I'm experiencing the same bug on the Ubuntu version from the software
store. I noticed a pattern through in the bug. Imagine you go with your
mouse from the server desktop to the client desktop and back. That counts
as one time. Now every time you repeat this (server desktop -> client
desktop -> server desktop), the mouse will appear on odd times and be
invisble on even times on the client desktop. Thus when you don't see the
cursor appear you have to drag the mouse back to the server and than try
again and you will see the cursor. I hope this contributes in anyway. "

On Fri, Mar 6, 2015 at 10:07 AM, Nick Bolton <notifications@github.com>
wrote:

> Related? #2754 <https://github.com/synergy/synergy/issues/2754>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/synergy/synergy/issues/4355#issuecomment-77555797>.
>



-- 
Skype: felipeanl
