### ISSUE TITLE
`syntool` Crashes on OS X

### ISSUE THREAD

**Issue by ylluminate** [synergy/synergy#4357]
I just attempted to activate Synergy and received two crashes.  The first was simply when the activation was occurring.  The second was when it was querying available plugins.  This is on the most recent nightly build and here are the crash reports:
• On activation: https://gist.github.com/6e0ca08dca5f1cd45ba9
• On plugin search: https://gist.github.com/82c4abda26b988cce60e

**Comment by nbolton** [comment]
@XinyuHou

**Comment by XinyuHou** [comment]
@ylluminate Thank you for the feedback. Which version of Mac do you use?

**Comment by ylluminate** [comment]
@XinyuHou in the crash reports, please note the OS Version.

**Comment by XinyuHou** [comment]
@ylluminate could you try our latest build again? This issue looks quite familiar and we found it only on Linux. Though my Mac is 10.10.1, I will update and check again. Thanks.

**Comment by nbolton** [comment]
@ylluminate I think the newest 1.7 beta fixes this.
http://synergy-project.org/nightly?filter=1.7.0-master-2feb916

**Comment by alanhoyle** [comment]
I am seeing this on Synergy 1.7.1 on OSX 10.10.3 client, Ubuntu 15.4 server.  

The attached screen shot is similar to what I saw, but it comes from running syntool at the command line:

$ /Applications/Synergy.app/Contents/MacOS/syntool
no args
Segmentation fault: 11

and it pops up the window:

![screen shot 2015-05-04 at 2 59 42 pm](https://cloud.githubusercontent.com/assets/289779/7460050/4e6bd3a8-f26e-11e4-9391-13282316f2cb.png)

**Comment by XinyuHou** [comment]
Could anyone test this nightly?

http://synergy-project.org/nightly?filter=9c5c6f5

**Comment by XinyuHou** [comment]
duplicated to #4581

**Comment by alanhoyle** [comment]
At the very least, it doesn't segfault on 10.10.3 with the 10.10 version,
when run at the command line.  I haven't tested the full app yet.


--
  -  Alan Hoyle  -  alan@alanhoyle.com  -  http://www.alanhoyle.com/  -
