### ISSUE TITLE
"Password" is misspellt as "Passward" in GUI wizard

### ISSUE THREAD

**Issue by ylluminate** [synergy/synergy#4358]
On your website at signup and within the application, the word "password" is misspelled as "passward."  Thought you'd most certainly want to correct a trivial spelling issue like this.

**Comment by JoshMcCullough** [comment]
This is also the case in the setup process (after install):

![image](https://cloud.githubusercontent.com/assets/4859660/6448408/d455e552-c0e7-11e4-9e4c-4748b216cde1.png)

**Comment by nbolton** [comment]
@XinyuHou
