### ISSUE TITLE
[req] Add support for LLVM/Clang on Windows instead of Visual studio

### ISSUE THREAD

**Issue by LeonardKoenig** [synergy/synergy#4362]
Is it possible to compile for windows without Visual studio? I'm mainly using Linux and don't want to install VS in order to compile Synergy myself.

Is it possible to compile with clang (and how, if i may ask?) - and if not, is it possible to add it (or maybe even replace VS with clang)?

**Comment by nbolton** [comment]
Hey @LeonardKoenig - really sorry but we only support VS right now. Patches welcome!
