### ISSUE TITLE
Add option to autohide on startup

### ISSUE THREAD

**Issue by kepi** [synergy/synergy#4374]
I would really appreciate adding option to autohide Synergy to tray on startup. I need it on Linux but would be useful on Windows too.

**Comment by Corben78** [comment]
Also on OS X please.
Iirc before 1.7.1 it was auto-hiding after start on my Mac.

**Comment by sruffell** [comment]
I have synergy 1.7.3, and in ~/.confg/Synergy/Synergy.conf there is an "autoHide" option in the general section that you can set to true.

**Comment by kepi** [comment]
@sruffell thanks! Working great on Linux. For me its enough but I'm leaving it open as it would be nice to document it or provide GUI checkbox to propagate this option to users. Also OS X wants this and I'm not sure if it works same way or not.

**Comment by sruffell** [comment]
Hmm..I just checked and on both Linux and OSX, it looks like in the miscellaneous sections there is a checkbox to "hide on startup".  Again, I'm using Synergy Pro 1.7.3, not sure if this is specific to my version or not.

![image](https://cloud.githubusercontent.com/assets/87230/8597936/ca67b110-261d-11e5-82da-fe27f1793fad.png)

**Comment by kepi** [comment]
Sorry, I didn't check it now as you wrote. Yes, it is now present but it wasnt before (or I was really blind but I looked for it really thoroughly).

Thanks to those who added it, closing the issue.

**Comment by apostrophedave** [comment]
im using 1.7.5 on windows and don't see any checkbox to hide on startup. is this option only for the linux version?
