### ISSUE TITLE
Synergy conflicts with Karabiner

### ISSUE THREAD

**Issue by mooreaa** [synergy/synergy#4381]
Synergy and Karabiner is running on my Mac (mac is the synergy server). Running Karabiner to add/emulate ctrl-c/ctrl-v function on Mac. Result is that ctrl-c/ctrl-v actions do not work when the mouse focus moves to the PC.  

Synergy needs a way to alert external programs such as Karabiner that the keyboard focus has changed, and in this case, to disable any remapping that is happening.

Please see the issue on the corresponding side: https://github.com/tekezo/Karabiner/issues/15

**Comment by nbolton** [comment]
Honestly I'm not sure this'll ever get fixed, though I'm open to suggestions from @tekezo (Karabiner) on how we might approach it. Patches welcome.

**Comment by limeb** [comment]
You can add exceptions to karabiner for what shortcuts will and won't transfer over that is IMO the best idea.
