### ISSUE TITLE
OS X Mouse Acceleration conflict

### ISSUE THREAD

**Issue by dorianfm** [synergy/synergy#4387]
I'm using Synergy 1.6.2 on OS X 10.10.2 as a server, with Synergy 1.6.2 on Ubuntu 14.10 as the client.

I have Smoothmouse - http://smoothmouse.com - installed on my OS X system as a mouse accelerator. This works fine except when I try to drag or select on Linux, at which point the acceleration seems to be amplified, causing it to be unusable. Disabling smoothmouse makes the linux side work more consistently, but mouse tracking is unbearably slow (not synergy's problem).

**Comment by JoshMcCullough** [comment]
I also have mouse-acceleration issues but on a Win7 server, Win8.1 client and no third party utilities involved. If I'm on the Win8.1 side and hit `Scroll Lock` to keep the mouse on that screen, my mouse becomes too fast to use. Not sure if this is related...

**Comment by nbolton** [comment]
Duplicates #451
