### ISSUE TITLE
Remove included pbt.h from MSWindowsScreen

### ISSUE THREAD

**Issue by JoshMcCullough** [synergy/synergy#4389]
This include doesn't seem to be needed...I've removed it from my local copy but wanted to get feedback before I commit that change. I can build w/out that include.

**Comment by nbolton** [comment]
Would you mind creating a PR? I'm not sure what it's for, a quick search seems to turn up some wxWidgets results, but we've never used that...

**Comment by JoshMcCullough** [comment]
Yeah it's in PR #4371 which has been patiently waiting to be merged for a while now. :)
