### ISSUE TITLE
Disable GUI auto-hide by default

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4390]
Problem: The auto-hide feature is insanely annoying.

Solution: It used to be a setting, but we took this out for some reason. We should to reintroduce the setting and disable it by default.

**Comment by nbolton** [comment]
This is now important, since for the user to verify the server fingerprint, they need the server GUI to be visible when a client connects.

**Comment by williamrice** [comment]
I think you may have forgotten to reintroduce the auto-hide setting? No sign of it in 1.7.1 on OSX 10.8.5

**Comment by nbolton** [comment]
@williamrice Sorry about that, I raised an issue for 1.7.2: https://github.com/synergy/synergy/issues/4569
