### ISSUE TITLE
How to build included openssl package.

### ISSUE THREAD

**Issue by JoshMcCullough** [synergy/synergy#4392]
I think it would be helpful to add instructions for building the openssl DLLs/etc. for WIN32 to the documentation. It took me a bit of time to figure this out myself as I never work with C++.

1. Extract `ext/openssl-1.0.1h.zip` to `ext/openssl`.
2. Open a VS command prompt at `etc/openssl` and run these commands (or similar, setting PATH as needed):

    set PATH=%PATH%;C:\Perl\bin
    set PATH=%PATH%;C:\Program Files (x86)\nasm

    perl Configure VC-WIN32
    ms\do_nasm
    nmake -f ms\ntdll.mak

3. Point to the install doc: `ext/openssl/INSTALL.W32`

**Comment by nbolton** [comment]
Sorry, that's bleeding edge stuff and we haven't yet added OpenSSL to our toolchain (coming soon).

**Comment by JoshMcCullough** [comment]
Ah, okay - got it.

**Comment by nbolton** [comment]
Created #4412
