### ISSUE TITLE
OSX 10.10 server and Linux client shows constant disconnect/reconnect in log BUT remains functional

### ISSUE THREAD

**Issue by wufufufu** [synergy/synergy#4393]
Looks something like this. It is still functional.

    NOTE: client "myhostname" has disconnected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    WARNING: a client with name "myhostname" is already connected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    WARNING: a client with name "myhostname" is already connected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    WARNING: a client with name "myhostname" is already connected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    WARNING: a client with name "myhostname" is already connected
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    WARNING: a client with name "myhostname" is already connected
    NOTE: client "myhostname" has disconnected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    WARNING: a client with name "myhostname" is already connected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    WARNING: a client with name "myhostname" is already connected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    WARNING: a client with name "myhostname" is already connected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    WARNING: a client with name "myhostname" is already connected
    NOTE: client "myhostname" has disconnected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    WARNING: a client with name "myhostname" is already connected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    WARNING: a client with name "myhostname" is already connected
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    WARNING: a client with name "myhostname" is already connected
    NOTE: client "myhostname" has disconnected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    WARNING: a client with name "myhostname" is already connected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    WARNING: a client with name "myhostname" is already connected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    WARNING: a client with name "myhostname" is already connected
    NOTE: client "myhostname" has disconnected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    WARNING: a client with name "myhostname" is already connected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    WARNING: a client with name "myhostname" is already connected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    WARNING: a client with name "myhostname" is already connected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    WARNING: a client with name "myhostname" is already connected
    NOTE: accepted client connection
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    NOTE: client "myhostname" has disconnected
    WARNING: a client with name "myhostname" is already connected
    WARNING: a client with name "myhostname" is already connected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    WARNING: a client with name "myhostname" is already connected
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    WARNING: a client with name "myhostname" is already connected
    NOTE: accepted client connection
    NOTE: accepted client connection
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    DEBUG: received client "myhostname" info shape=0,0 1366x768 at 683,384
    NOTE: disconnecting client "myhostname"
    NOTE: client "myhostname" has disconnected
    WARNING: a client with name "myhostname" is already connected
    WARNING: a client with name "myhostname" is already connected

**Comment by wufufufu** [comment]
I think the issue was that there were multiple instances of the linux client open. Closing.

**Comment by sunk818** [comment]
I had the same issue. Its been 4 years. I wonder if they should have some sort of check so that the same process doesn't launch twice, or some way to detect that synergy is already running.

For me, it was in Windows 7. I had to end task of synergy.exe and run Synergy again.

```
2019-02-13T07:21:15] WARNING: a client with name "xxx" is already connected
[2019-02-13T07:21:15] NOTE: disconnecting client "xxx"
[2019-02-13T07:21:15] NOTE: client "xxx" has disconnected
[2019-02-13T07:21:15] NOTE: accepted client connection
```
