### ISSUE TITLE
Cursor on Mac OS X client is too sensitive after sleep/wake

### ISSUE THREAD

**Issue by mathie** [synergy/synergy#4401]
I'm using Synergy 1.7.0 with a Mac OS X server and client.

When the server is freshly started, the mouse sensitivity on the client is OK. After the client/server sleeps and reawakens, the mouse is too sensitive on the client, and becomes jumpy. This gets progressively worse after several sleep & wake cycles.

Restarting the server fixes the problem.

**Comment by nbolton** [comment]
Duplicates #451
