### ISSUE TITLE
Scrolling is too sensitive on the Mac OS X client

### ISSUE THREAD

**Issue by mathie** [synergy/synergy#4402]
I'm using Synergy 1.7.0 on both the Mac OS X server and client.

Scrolling on the client is too sensitive and seems jumpy. Unlike the cursor sensitivity in #4401 it's still too sensitive even when the server is restarted.

Please let me know if there's anything I can do to help resolve these issues!

**Comment by nbolton** [comment]
Could be related to #451 but may not be a duplicate.

**Comment by mkjones** [comment]
I'm seeing this same problem (scrolling with 2 fingers on a trackpad connected to a Yosemite server, with the cursor on a Yosemite client).  Scrolling on the server is fine, and tracking speed on both is fine.

I suspect it's unrelated, but gestures also fail (e.g. two-finger swipe to go back in a browser) even though they're configured on both the client and the server.

**Comment by ulumi** [comment]
+1 this is really annoying!

**Comment by jonern** [comment]
+1 yep, still annoying.
