### ISSUE TITLE
GUI wizard gets stuck on "Generating certificate..."

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4406]
Version: 1.7.0

1. Run the GUI wizard
2. Get to the last step
3. Status gets stuck on "Generating certificate..."

The issue here could be that the download is taking a long time (or has stalled), or there's an error that didn't get reported to the GUI (and nothing is happening).

**Comment by the-wes** [comment]
maybe even some sort of "show details" type button which will let us/users see the URL to the file that is being downloaded? and/or the parameters being supplied to the tool, the path to the tool, the output from the tool, etc?

**Comment by nbolton** [comment]
@the-wes Good idea.

**Comment by JoshMcCullough** [comment]
It went past the download screen almost immediately. Although one time it did hang there, too. It seems that there is some error behind the scenes and the certificate generation failed or stalled?

**Comment by nbolton** [comment]
I think it'd be interesting to see what's in this folder: %LOCALAPPDATA%\Synergy

**Comment by JoshMcCullough** [comment]
![image](https://cloud.githubusercontent.com/assets/4859660/6510187/684df712-c332-11e4-8db8-e45221b58cf2.png)

**Comment by JoshMcCullough** [comment]
Is there a log file somewhere? The one in `C:\Program Files\Synergy` appears to only log service-related stuff.

**Comment by nbolton** [comment]
No logs sorry, what about the "Synergy" folder? What's in there? %LOCALAPPDATA%\Synergy

**Comment by JoshMcCullough** [comment]
I already posted a screenshot. ^^^

**Comment by JoshMcCullough** [comment]
BTW, still "generating certificate" after ~7 minutes.

**Comment by nbolton** [comment]
Ah, you posted a screenshot of `%LOCALAPPDATA%\Synergy\Plugins` - would you mind going up one level into `%LOCALAPPDATA%\Synergy` and letting me know what's in there?

**Comment by JoshMcCullough** [comment]
Sorry about that. `%LOCALAPPDATA%\Synergy` only has the Plugins folder.

**Comment by nbolton** [comment]
No problem, so it seems like it's not able to download the certificate tool. You can grab that manually (http://synergy-project.org/files/tools/openssl-1.0.2-Windows-x86.exe) and extract to `%LOCALAPPDATA%\Synergy` -- if you'd like? That said, I think the wizard re-downloads the file, so it might not help.

**Comment by JoshMcCullough** [comment]
Yeah, no luck...

**Comment by nbolton** [comment]
Dang. OK leave it with me Josh, I'll update this issue once I've added more debug info. Thanks for your help!

**Comment by nbolton** [comment]
@JoshMcCullough Just a thought - does this happen on your other computers? What other OSs are you running?

**Comment by nbolton** [comment]
Interestingly I saw a similar bug on my Mac VM, but it gets stuck downloading the plugin...

![screen shot 2015-03-05 at 18 16 12](https://cloud.githubusercontent.com/assets/313427/6511296/d910af90-c363-11e4-8b29-1a0fc397bf90.png)

**Comment by JoshMcCullough** [comment]
I'm pretty sure it happened on my laptop which is Win8.1...

**Comment by JoshMcCullough** [comment]
Interestingly, on Win8.1 I don't get the loading indicator while generating certificate, but it also does not seem to complete. `%LOCALAPPDATA%\Synergy` still only has the Plugins folder. I ran Synergy as Administrator and it didn't seem to help.

Also this: 
![image](https://cloud.githubusercontent.com/assets/4859660/6511648/1a5a2012-c33c-11e4-8257-d9467a403cff.png)

**Comment by nbolton** [comment]
I think that's an older version, the wording is slightly different in the official beta.
Try this: http://synergy-project.org/nightly?filter=1.7.0-master-2feb916

**Comment by JoshMcCullough** [comment]
This was using `synergy-1.7.0-focus-fix-patch-8823ad5-Windows-x64.msi` I'll switch to the version you've suggested.

**Comment by JoshMcCullough** [comment]
Okay, so the cert generates fine with that installer. Sorry about that. 

I have SSL enabled, which seems to work fine on the server (Win7). On the client (Win8.1), I've enabled SSL but I'm not able to control the service from the desktop app. This comes up when I click start, get the "Synergy is starting" message, and then get impatient and click stop:

    ERROR: could not get session id for process id 121284
    ERROR: secure socket error: SSL_ERROR_SSL
    ERROR: secure socket error: error:140940F6:SSL routines:ssl3_read_bytes:unknown alert type

Note that during this time, mouse/keyboard interactivity from the server to the client works fine (so Synergy is definitely running). But once I click stop, it does stop Synergy. The app just can't seem to start it...

**Comment by nbolton** [comment]
Oh awesome! I guess this one's closed then. Would you mind raising another issue for the `SSL_ERROR_SSL` message?

**Comment by JoshMcCullough** [comment]
#4409
