### ISSUE TITLE
SSL_ERROR_SSL (unknown protocol) on Mac client

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4410]
Version: 1.7.0-master-2feb916 (beta)
Server: Win 7 64-bit
Client: Mac OS X 10.10

Not sure about repro steps, but I came into work this morning and my Mac client had crashed. Win server was still running.

Last error was...

```
ERROR: secure socket error: SSL_ERROR_SSL
INFO: server connection may not be secure
ERROR: secure socket error: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

**Comment by nbolton** [comment]
Related to #4409?

**Comment by XinyuHou** [comment]
It seems there are many cases that could cause unknown protocol error. In this case, Add timestamps to log lines #4439 may help us to figure out what is wrong.

**Comment by TTimo** [comment]
I am seeing this between a MacOS X 10.10 client and a Linux server (Debian sid x64).
Running beta 1.7.0 both sides

**Comment by TTimo** [comment]
Workaround .. turn off encryption (of course) ..

**Comment by nbolton** [comment]
Maybe fixed by 916a4c75af19f9d6031c7236d63b308f943250fc

**Comment by nbolton** [comment]
@speaker Jerry thinks this probably doesn't crash any more (it will retry instead). So this issue may be fixed. The error will still log out, but I think that's just how OpenSSL works.

**Comment by nbolton** [comment]
@speaker I should elaborate, could you test and confirm its fixed? See if you can get it to crash with this error.
