### ISSUE TITLE
Add other payment options (recommondation)

### ISSUE THREAD

**Issue by LeonardKoenig** [synergy/synergy#4418]
Hello there,
though I use synergy exclusively (currently) on Linux, I'ld like to donate/buy. Sadly, PayPal is the only option - which is not an option for me.
There are plenty of alternatives:
- Skrill
- paysafecard
- ukash

I really would like to see that (and I know some others who would, I guess, too)

**Comment by nbolton** [comment]
Thanks for the suggestion, adding this to our internal tracker for the website.
