### ISSUE TITLE
Large amounts of data in clipboard can cause connectivity issues

### ISSUE THREAD

**Issue by Dezzles** [synergy/synergy#4428]
When large amounts of data are stored in the clipboard, communication can break down between server and client when changing focus between screens.

Test case:
Windows 8.1 machine - Server
Windows 7 machine - client 
Communication via wireless
With a 1920x1080 image stored in the server's clipboard (i.e. a screenshot), moving focus from the server to the client causes the connection to break

**Comment by nbolton** [comment]
Duplicates #4353
