### ISSUE TITLE
Client cursor speed doubles on each wake-up (Mac server)

### ISSUE THREAD

**Issue by rogerdrummond** [synergy/synergy#4432]
Undoubtedly the same issue as #451, but since you've lost customers for over 5 years over this, perhaps you could put in a quick fix that simply "stops-and-restarts" synergy during Mac Wakeup? 

This appears to be the only workaround documented, and it fixes the problem, but reading Google, people abandon Synergy after a few weeks of having to manually "Start" and "Stop" Synergy every time they walk away from their desk.  This is FUNDAMENTAL to good working software, and the equivalent of having to unplug and plug in your keyboard every time you walk away from your computer.

My own experience is that the issue exists on every Mac OS Server.  I've tried 10.6, 10.7, 10.8, 10.9, 10.10, both MacBookPros and MacMinis; using clients of Win7, Win8, Win8.1.  The only thing intermittent about it is if your Mac really goes into full sleep or not.  It is highly consistent: Each wakeup causes an additional increase in cursor speed, until it goes so fast you can't see it.   (Some of your customers can simply switch the Server to Windows, but not many, and your software has a lot of bugs preventing this, especially horizontal and vertical scroll wheels and function keys used with Mac software.)

I've read many rude comments about the integrity of a software engineer who charges for software that is fundamentally broken and puts priority on random cute features rather than something that is CORE to the idea of sharing a mouse.  Although extreme, I suspect this single bug now effects your entire reputation.  If you can't fix it soon, I'd really suggest trying the STOP-START during wakeup fix.

**Comment by nbolton** [comment]
Duplicates #451

**Comment by nbolton** [comment]
@rogerdrummond I prioritized #451 in light of this :)
