### ISSUE TITLE
can't build on mac (open ssl deprecated)

### ISSUE THREAD

**Issue by lukeg01** [synergy/synergy#4442]
Hello

version: 1.7.1
OS: OSX 10.10.2

when building, this is my output:

<code> 
Entering dir: build/release
[ 12%] Built target arch
[ 13%] Built target common
[ 21%] Built target base
[ 25%] Built target mt
[ 27%] Built target io
[ 32%] Built target net
[ 54%] Built target synergy
[ 64%] Built target server
[ 74%] Built target platform
[ 79%] Built target ipc
[ 80%] Built target client
[ 81%] Building CXX object src/lib/plugin/ns/CMakeFiles/ns.dir/SecureSocket.cpp.o
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:63:3: error: 
      'SSL_shutdown' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]
                SSL_shutdown(m_ssl->m_ssl);
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1537:5: note: 
      'SSL_shutdown' has been explicitly marked deprecated here
int SSL_shutdown(SSL *s) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
    ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:65:3: error: 
      'SSL_free' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]
                SSL_free(m_ssl->m_ssl);
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1495:6: note: 
      'SSL_free' has been explicitly marked deprecated here
void    SSL_free(SSL *ssl) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
        ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:69:3: error: 
      'SSL_CTX_free' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]
                SSL_CTX_free(m_ssl->m_context);
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1352:6: note: 
      'SSL_CTX_free' has been explicitly marked deprecated here
void    SSL_CTX_free(SSL_CTX *) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
        ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:79:2: error: 
      'SSL_shutdown' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]
        SSL_shutdown(m_ssl->m_ssl);
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1537:5: note: 
      'SSL_shutdown' has been explicitly marked deprecated here
int SSL_shutdown(SSL *s) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
    ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:105:7: error: 
      'SSL_read' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]
                r = SSL_read(m_ssl->m_ssl, buffer, n);
                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1498:6: note: 
      'SSL_read' has been explicitly marked deprecated here
int     SSL_read(SSL *ssl,void *buf,int num) DEPRECATED_IN_MAC_OS_X_VERS...
        ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:123:7: error: 
      'SSL_write' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]
                r = SSL_write(m_ssl->m_ssl, buffer, n);
                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1500:6: note: 
      'SSL_write' has been explicitly marked deprecated here
int     SSL_write(SSL *ssl,const void *buf,int num) DEPRECATED_IN_MAC_OS...
        ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:156:6: error: 
      'SSL_CTX_use_certificate_file' is deprecated: first deprecated in OS X
      10.7 [-Werror,-Wdeprecated-declarations]
        r = SSL_CTX_use_certificate_file(m_ssl->m_context, filename, SSL...
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1407:5: note: 
      'SSL_CTX_use_certificate_file' has been explicitly marked deprecated here
int     SSL_CTX_use_certificate_file(SSL_CTX *ctx, const char *file, in...
        ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:161:6: error: 
      'SSL_CTX_use_PrivateKey_file' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]
        r = SSL_CTX_use_PrivateKey_file(m_ssl->m_context, filename, SSL_...
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1406:5: note: 
      'SSL_CTX_use_PrivateKey_file' has been explicitly marked deprecated here
int     SSL_CTX_use_PrivateKey_file(SSL_CTX *ctx, const char *file, int ...
        ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:166:6: error: 
      'SSL_CTX_check_private_key' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]
        r = SSL_CTX_check_private_key(m_ssl->m_context);
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1480:5: note: 
      'SSL_CTX_check_private_key' has been explicitly marked deprecated here
int SSL_CTX_check_private_key(const SSL_CTX *ctx) DEPRECATED_IN_MAC_OS_X...
    ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:175:2: error: 
      'SSL_library_init' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]
        SSL_library_init();
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1558:5: note: 
      'SSL_library_init' has been explicitly marked deprecated here
int SSL_library_init(void ) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
    ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:180:2: error: 
      'OPENSSL_add_all_algorithms_noconf' is deprecated: first deprecated in OS
      X 10.7 [-Werror,-Wdeprecated-declarations]
        OpenSSL_add_all_algorithms();
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/evp.h:829:3: note: 
      expanded from macro 'OpenSSL_add_all_algorithms'
                OPENSSL_add_all_algorithms_noconf()
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/evp.h:821:6: note: 
      'OPENSSL_add_all_algorithms_noconf' has been explicitly marked deprecated
      here
void OPENSSL_add_all_algorithms_noconf(void) DEPRECATED_IN_MAC_OS_X_VERS...
     ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:183:2: error: 
      'SSL_load_error_strings' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]
        SSL_load_error_strings();
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1421:6: note: 
      'SSL_load_error_strings' has been explicitly marked deprecated here
void    SSL_load_error_strings(void ) DEPRECATED_IN_MAC_OS_X_VERSION_10_...
        ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:187:12: error: 
      'SSLv23_server_method' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]
                method = SSLv23_server_method();
                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1521:13: note: 
      'SSLv23_server_method' has been explicitly marked deprecated here
SSL_METHOD *SSLv23_server_method(void) DEPRECATED_IN_MAC_OS_X_VERSION_10...
            ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:191:12: error: 
      'SSLv23_client_method' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]
                method = SSLv23_client_method();
                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1522:13: note: 
      'SSLv23_client_method' has been explicitly marked deprecated here
SSL_METHOD *SSLv23_client_method(void) DEPRECATED_IN_MAC_OS_X_VERSION_10...
            ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:196:21: error: 
      'SSL_CTX_new' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]
        m_ssl->m_context = SSL_CTX_new(m);
                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1351:10: note: 
      'SSL_CTX_new' has been explicitly marked deprecated here
SSL_CTX *SSL_CTX_new(SSL_METHOD *meth) DEPRECATED_IN_MAC_OS_X_VERSION_10...
         ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:208:18: error: 
      'SSL_new' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]
                m_ssl->m_ssl = SSL_new(m_ssl->m_context);
                               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1486:7: note: 
      'SSL_new' has been explicitly marked deprecated here
SSL *   SSL_new(SSL_CTX *ctx) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
        ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:218:2: error: 
      'SSL_set_fd' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]
        SSL_set_fd(m_ssl->m_ssl, socket);
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1375:5: note: 
      'SSL_set_fd' has been explicitly marked deprecated here
int     SSL_set_fd(SSL *s, int fd) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_A...
        ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:221:10: error: 
      'SSL_accept' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]
        int r = SSL_accept(m_ssl->m_ssl);
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1496:6: note: 
      'SSL_accept' has been explicitly marked deprecated here
int     SSL_accept(SSL *ssl) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
        ^
/Users/Luke/Downloads/synergy-master/src/lib/plugin/ns/SecureSocket.cpp:247:2: error: 
      'SSL_set_fd' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]
        SSL_set_fd(m_ssl->m_ssl, socket);
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/ssl.h:1375:5: note: 
      'SSL_set_fd' has been explicitly marked deprecated here
int     SSL_set_fd(SSL *s, int fd) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_A...
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [src/lib/plugin/ns/CMakeFiles/ns.dir/SecureSocket.cpp.o] Error 1
make[1]: *** [src/lib/plugin/ns/CMakeFiles/ns.dir/all] Error 2
make: *** [all] Error 2
Going back to: /Users/Luke/Downloads/synergy-master
Error: make failed: 512
</code>

**Comment by nbolton** [comment]
You need to extract openssl to `ext/openssl` (otherwise it uses the Mac version of openssl).

**Comment by lukeg01** [comment]
I did (It was first called opensslVersionNr) and now I'm having this as output:

make[2]: *** No rule to make target `../../ext/openssl/libssl.a', needed by `../../lib/libns.dylib'.  Stop.
make[1]: *** [src/lib/plugin/ns/CMakeFiles/ns.dir/all] Error 2
make: *** [all] Error 2
Going back to: /Users/Luke/Downloads/synergy-master
Error: make failed: 512

**Comment by nbolton** [comment]
Ah, sorry you need to compile it first, see the "install" files in the openssl dir.

**Comment by lukeg01** [comment]
So by accident I compiled openSSL in i386 and even tough I re-compiled it for 64bit i'm still getting the error that I compiled it for the i386 architecture. any way to fix that?

**Comment by XinyuHou** [comment]
Hi,

You need to delete openSSL folder completely and recompile 64 bit. That is
what openSSL official website recommended.

Hope this helps.

Thanks

--
Xinyu Hou
Software Engineer
The Synergy Project

<http://synergy-project.org>

http://synergy-project.org
View my LinkedIn profile
<https://www.linkedin.com/profile/view?id=179423259>

**Comment by lacombar** [comment]
FWIW, I successfully built the latest git on Yosemite with the following:
```
diff --git a/src/lib/plugin/ns/CMakeLists.txt b/src/lib/plugin/ns/CMakeLists.txt
index 81a6da4..ba1fc1a 100644
--- a/src/lib/plugin/ns/CMakeLists.txt
+++ b/src/lib/plugin/ns/CMakeLists.txt
@@ -44,14 +44,7 @@ if (WIN32)
 endif()
 
 if (UNIX)
-  if (APPLE)
-    set(OPENSSL_LIBS
-         ${CMAKE_SOURCE_DIR}/ext/openssl/libssl.a
-         ${CMAKE_SOURCE_DIR}/ext/openssl/libcrypto.a
-    )
-  else()
     set(OPENSSL_LIBS ssl crypto)
-  endif()
 endif()
 
 target_link_libraries(ns
diff --git a/src/lib/plugin/ns/SecureSocket.cpp b/src/lib/plugin/ns/SecureSocket.cpp
index cb6db76..e90f322 100644
--- a/src/lib/plugin/ns/SecureSocket.cpp
+++ b/src/lib/plugin/ns/SecureSocket.cpp
@@ -1,3 +1,4 @@
+#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
 /*
  * synergy -- mouse and keyboard sharing utility
  * Copyright (C) 2015 Synergy Si Ltd.
```

It was much quicker than trying to figure out how to build openssl (which doesn't seem to be wired *anywhere* btw...).

**Comment by david-koller** [comment]
Hello together,

I think it's a misunderstanding. For me compiling ./ext/openssl for i386 (./config && make) worked fine.

Regards
