### ISSUE TITLE
v1.7 freezes entire system.

### ISSUE THREAD

**Issue by vanowm** [synergy/synergy#4443]
I'm unable test v1.7 as server on W7 x64 because it's totally unusable.
After install over v1.6 it froze entire system to the point that even keyboard's numlock didn't work (a good indicator if system still recoverable)
After reboot cursor lagged a few times and when I opened Synergy window it froze and never recovered (system didn't freeze though)

**Comment by nbolton** [comment]
Duplicates #4403
