### ISSUE TITLE
GUI notification icon freezes

### ISSUE THREAD

**Issue by legonigel** [synergy/synergy#4445]
On windows 8.1 I can get synergy.exe 1.6.2 on my server to freeze sometimes with the following steps:
1. Open syngery.exe
2. Right click on notification icon and hide the synergy.exe window
3. Move mouse to client
4. Move mouse back to server, and immediately right click on the synergy notification icon
5. The notification icon will not pop up the menu
6. The synergy.exe process will stop responding
7. Synergy itself still runs, just the synergy.exe gui stops working

**Comment by nbolton** [comment]
Is this with debug log level? Might be related to #4341

**Comment by legonigel** [comment]
I did have debug level 2 on at the time. I will see if I can reproduce on 1.7.1 with and without debug2.

**Comment by legonigel** [comment]
After some testing. I believe this is related to #4341. I can reproduce on debug2 but not on debug on a 1.7.1 server on windows 8.1.

**Comment by nbolton** [comment]
Thanks for confirming @legonigel!

Duplicates #4341
