### ISSUE TITLE
Mac Client CPU drained, SUPER lag!

### ISSUE THREAD

**Issue by envil** [synergy/synergy#4447]
**Information:**
-Server: Windows 7 64 bit, Core i5, Ram 8G, SSD 128gb , Synergy 1.6.2
-Client: MacBookPro late 2013, Core i5, Ram 8Gb, OS X 10.9.5 (10.10 also) Synergy 1.6.2

**Description:**
The client appears to be very lag! I barely control anything, the keypress and every other action were delayed about 1s. Examining through the Activity Monitor on the OS X, I see the synergy process sometimes consumes a lot of CPU (>30%)

Hope this will be fixed!
Thank you very much!

**Comment by nbolton** [comment]
What version of Synergy are you using, @envil?

**Comment by nbolton** [comment]
#4132
#4417
