### ISSUE TITLE
Windows 8 Issue With Window Focus

### ISSUE THREAD

**Issue by stix11** [synergy/synergy#4456]
When clicking on a window placed behind another window, the focus does not shift to the window and bring it to the front. Instead, the window that is already moved to the top stays there. This correlates with synergy because this was not happening until I installed synergy on Windows 8.
![synergybug](https://cloud.githubusercontent.com/assets/7670727/6752764/bd2708be-ced6-11e4-88c9-1bd9161091ec.GIF)

**Comment by XinyuHou** [comment]
@stix11 this is duplicated to #4349
