### ISSUE TITLE
Problem with 1.7 nightly on Mac

### ISSUE THREAD

**Issue by carukc** [synergy/synergy#4457]
When testing the latest nightly to resolve the focus problem I discovered an error when running the 1.7 nightly on my Mac:

Dyld Error Message:
Library not loaded: QtGui.framework/Versions/4/QtGui
Referenced from: /Applications/Synergy.app/Contents/MacOS/Synergy
Reason: image not found

OSX 10.10.3 (14D105g)

It installed on my Win 8.1 PC without a problem.

**Comment by nbolton** [comment]
Pretty sure this is fixed now, the macdeployqt step was messing up (but wasn't telling us) so incomplete builds were being uploaded.
