### ISSUE TITLE
Add a control to display the password in clear text

### ISSUE THREAD

**Issue by krichter722** [synergy/synergy#4460]
There's no way of telling whether the password is correct, so this control would serve to exclude a password mismatch on server and client as a reason for a connection failure. I'd suggest a checkbox which would allow to display and hide the clear text easily.

**Comment by nbolton** [comment]
Encryption password right? 1.7 solves this too.

**Comment by krichter722** [comment]
> Encryption password right?
Yes. Great!

**Comment by nbolton** [comment]
Its because we're using SSL :)

**Comment by krichter722** [comment]
Even better :)
