### ISSUE TITLE
Can't compile, SyntaxError

### ISSUE THREAD

**Issue by arpadgabor** [synergy/synergy#4479]
I just installed all the dependencies. And after trying to run hm from cmd, pointed at the folder containing the file, and I get this error:

Traceback (most recent call last):
  File "hm.py", line 22, in <module>
    from toolchain import commands1
  File "ext\toolchain\commands1.py", line 130
    print 'Mapping command: %s' % ' -> '.join(cmd_map)
                              ^
SyntaxError: invalid syntax

Windows 8.1

**Comment by saccohuo** [comment]
Why was this issue is closed? Do u solve the problem?
