### ISSUE TITLE
Windows service upgrade fails on privilege error

### ISSUE THREAD

**Issue by mirceanis** [synergy/synergy#4480]
I'm trying to upgrade to version 1.6.3 and I get the error:
```
Service 'Synergy' (Synergy) could not be installed.
Please verify that you have sufficient privileges to install
system services.
```

I'm the administrator of this computer.
After a system restart, the installation proceeds without incident, never asking for any privileges.

This is also the case when upgrading to version 1.7.0(beta)

**Comment by nbolton** [comment]
I'm seeing this too on Windows 7, restart workaround works for me too.

**Comment by nbolton** [comment]
Duplicates #4446
