### ISSUE TITLE
GUI crash on opening settings in Ubuntu 14.04

### ISSUE THREAD

**Issue by dhiva** [synergy/synergy#4483]
Synergy got updated recently to 1.7.0-1~getdeb1 in my ubuntu 14.04 and after the update when I try to open the settings panel of synergy. It crashes without any errors. I tried opening synergy settings few times and it crashed every single time. Could you please resolve this issue.

Thank you.

**Comment by kwhat** [comment]
I am also seeing this issue on Gentoo with 1.7.0.  Let me know if stack traces are needed.

**Comment by nbolton** [comment]
Stack traces would be much appreciated!

**Comment by legonigel** [comment]
Just to note, I am not seeing this on my copy of 14.04 with 1.7.1.

**Comment by kwhat** [comment]
I don't see 1.7.1 available, here is a stacktrace from 1.7.0 http://pastebin.com/aMJAb3PU

**Comment by dhiva** [comment]
I dont see this issue anymore with 1.7.4. So this issue can be resolved.
