### ISSUE TITLE
Linux crash from cryptopp library

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4495]
Matthew Williams wrote:

I'm seeing the same SIGILL in Crypto::SHA256::Transform() on my box and turning off encryption is not an option for me.

```
$ cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz
stepping	: 10
microcode	: 0xa07
cpu MHz		: 2995.000
cache size	: 6144 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm dtherm tpr_shadow vnmi flexpriority
bogomips	: 5985.09
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz
stepping	: 10
microcode	: 0xa07
cpu MHz		: 1995.000
cache size	: 6144 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm dtherm tpr_shadow vnmi flexpriority
bogomips	: 5984.96
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

**Comment by alanhoyle** [comment]
I think I'm seeing this same thing on my Intel Xeon from several years ago.  1.6.3 client on OSX 10.10.2, 1.6.3 server on Ubuntu 14.10 x86_64 with the latest updates.  I also use encryption.  

Server crashes on client connection:

>DEBUG: screen "lbg-alanh" shape changed
NOTE: accepted client connection
Illegal instruction (core dumped)

Here's the info on my CPU, I don't know how to debug or find the core.  

>processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 26
model name	: Intel(R) Xeon(R) CPU           E5530  @ 2.40GHz
stepping	: 5
microcode	: 0xf
cpu MHz		: 1596.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 sse4_2 popcnt lahf_lm ida dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 4787.96
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

**Comment by Corben78** [comment]
Same issue here:
With enabled encryption 1.6.3 synergy server on Ubuntu 14.04 64bit crashes. Works fine with 1.6.2.
CPU: Intel C2Q Q9550

`cat /proc/cpuinfo:`
`processor	: 3`
`vendor_id	: GenuineIntel`
`cpu family	: 6`
`model		: 23`
`model name	: Intel(R) Core(TM)2 Quad CPU    Q9550  @ 2.83GHz`
`stepping	: 10`
`microcode	: 0xa07`
`cpu MHz		: 2003.000`
`cache size	: 6144 KB`
`physical id	: 0`
`siblings	: 4`
`core id		: 3`
`cpu cores	: 4`
`apicid		: 3`
`initial apicid	: 3`
`fpu		: yes`
`fpu_exception	: yes`
`cpuid level	: 13`
`wp		: yes`
`flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon` `pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm dtherm tpr_shadow vnmi flexpriority
`bogomips	: 5677.46`
`clflush size	: 64`
`cache_alignment	: 64`
`address sizes	: 36 bits physical, 48 bits virtual`
`power management:`


Error message in /var/log/syslog:
`kernel: [  774.584304] traps: synergys[4357] trap invalid opcode ip:61f737 sp:7fffed222908 error:0 in synergys[400000+2d5000]`

Stacktrace from Ubuntu crash log
`Stacktrace:`
` #0  0x000000000061f737 in CryptoPP::SHA256::Transform(unsigned int*, unsigned int const*) ()`
` No symbol table info available.`
` #1  0x00000000005fca7a in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::HashMultipleBlocks(unsigned int const*, unsigned long) ()`
` No symbol table info available.`
` #2  0x00000000005fd07a in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::Update(unsigned char const*, unsigned long) ()`
` No symbol table info available.`
` #3  0x0000000000619e75 in CryptoPP::RandomPool::IncorporateEntropy(unsigned char const*, unsigned long) ()`
` No symbol table info available.`
` #4  0x00000000006146d6 in CryptoPP::AutoSeededRandomPool::Reseed(bool, unsigned int) ()`
` No symbol table info available.`
` #5  0x0000000000574ef8 in CryptoStream::CryptoStream(IEventQueue*, synergy::IStream*, CryptoOptions const&, bool) ()`
` No symbol table info available.`
` #6  0x0000000000540f0c in ClientListener::handleClientConnecting(Event const&, void*) ()`
` No symbol table info available.`
` #7  0x0000000000508de8 in EventQueue::dispatchEvent(Event const&) ()`
` No symbol table info available.`
` #8  0x000000000050c114 in EventQueue::loop() ()`
` No symbol table info available.`
` #9  0x0000000000514035 in ServerApp::mainLoop() ()`
` No symbol table info available.`
` #10 0x0000000000512437 in ServerApp::runInner(int, char**, ILogOutputter*, int (*)(int, char**)) ()`
` No symbol table info available.`
` #11 0x0000000000511b22 in App::run(int, char**) ()`
` No symbol table info available.`
` #12 0x0000000000501ed4 in main ()`
` No symbol table info available.`

**Comment by nbolton** [comment]
Invalid since we're dropping Crypto++ encryption.
