### ISSUE TITLE
Atom.io , Chrome, Synergy

### ISSUE THREAD

**Issue by vid** [synergy/synergy#4501]
I'm using synergys 1.7 and synergyc 1.4 (I paid for synergy to get around another issue, and cause it's a great program) between two Ubuntu 14.04 systems. Up till today everything worked fine. But today, probably since updating atom.io, every time I use a clipboard operation there are long pauses and much weirdness with the mouse cursor when switching between windows; the cursor will disappear entirely at the 'border' and takes a few moments to appear in either window.

This is probably related to https://github.com/synergy/synergy/issues/2766

Thanks!

**Comment by xak2000** [comment]
I never heared about Synergy, but started to suffer the same issue with atom.io and Chrome.
When atom.io is running and I try to copy/paste something on Chrome, then Chrome's tab freezes for long time (3-10 min) and then crashes. If I close atom.io editor then copy/paste in Chrome starts working fine.

My OS is Ubuntu 12.04 x64.

As I sayed I never heared about Synergy before so I haven't it installed on my computer. So I think if this is the same problem then this is in atom.io. Not in Synergy. As I know atom.io based on Chromium and maybe this causes some issues with Chrome.

This problem apeared few days ago. I think after update the atom.io.

**Comment by vid** [comment]
I think the problem is with Atom (actually, the problem is the window manager / clipboard since this kind of problem shouldn't happen between apps, but it seems the latest Atom ppk at least carries this problem. I also made a comment on the webupd8 Atom repo if that's what you're using). But it manifests in interaction between atom + chrome and atom, chrome + synergy. I believe it is related to the bug referenced above. So this synergy issue shoudl be closed, though I'm guessing if synergy allowed disabling clipboard between screens the problem wouldnt hit there.

**Comment by xak2000** [comment]
From [atom release notes](https://atom.io/releases)
> Atom now ships with Chrome 41 which means emojis now render in the editor :+1:

I think this upgrade to Chrome 41 will cause the issue somehow.
P.S. My Windows7 x64 machine not under this bug. Only Ubuntu.

**Comment by vid** [comment]
Ironic. I hate emojis. \:

**Comment by jamgregory** [comment]
Just an FYI, Atom has been updated to release 0.190.0, and this appears to fix the copy-paste issue between Atom and Chrome (as far as my limited tested in concerned, anyway!) :+1:

**Comment by vid** [comment]
Yes it does. Thanks everyone!
