### ISSUE TITLE
Debian Jessie - Encryption Fails

### ISSUE THREAD

**Issue by K0HAX** [synergy/synergy#4502]
Synergy 1.7.0
Debian Jessie
When I turn on encryption, Synergy fails to find the libraries libcrypto.so.10 and libssl.so.10.
Workaround: link libssl.so.1.0.0 and libcrypto.so.1.0.0 to libssl.so.10 and libcrypto.so.10 respectively.

After doing that workaround, I get the following error when attempting to set up an encrypted tunnel.
```
ERROR: failed to load plugin: libns.so
FATAL: An error occurred: /usr/lib/x86_64-linux-gnu/libcrypto.so.10: version `libcrypto.so.10' not found (required by /home/michael/.synergy/plugins/libns.so)
NOTE: stopping synergy desktop process
```

**Comment by nbolton** [comment]
We are phasing out the legacy encryption, so this issue is no longer valid.

**Comment by darkrain42** [comment]
Are you sure this is invalid?  I see the same thing with the libns plugin in 1.7.1 (I'm running Debian unstable/sid).

I thought this *was* the new form of encryption (using SSL), i.e. the new stuff introduced in v1.7.0.

**Comment by babamucha** [comment]
yeah I have the same problem too ubuntu 12.04 elementary OS 0.2.1 Luna 64bit

DEBUG1: logging to file (/var/log/synergy.log) enabled
DEBUG: opening configuration "/tmp/qt_temp.S26604"
DEBUG: configuration read successfully
DEBUG1: thread 0x00000002 entry
DEBUG: plugins dir: /home/dom/.synergy/plugins
DEBUG: loading plugin: libns.so
ERROR: failed to load plugin: libns.so
DEBUG1: caught cancel on thread 0x00000002
FATAL: An error occurred: libssl.so.10: cannot open shared object file: No such file or directory
NOTE: stopping synergy desktop process

**Comment by nbolton** [comment]
Ah, because this issue is about the Crypto++ dependency which no longer exists. Please see issue #4565 which is about the SSL dependency.
