### ISSUE TITLE
Plugin wizard doesn't complete but finish button enabled

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4537]
1. Start server/client (use ns.dll)
1. Run wizard from menu
2. Use a pro account
3. Plugin download step passes
4. SSL generate step freezes
5. Finish button can be clicked

**Comment by nbolton** [comment]
Maybe its because the plugin is in use?

**Comment by XinyuHou** [comment]
Can anyone test these nightly build?

http://synergy-project.org/nightly?filter=synergy-master-365d16
