### ISSUE TITLE
Windows service crashes intermittently with no error

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4538]
1. Start GUI on Windows
2. Close GUI
3. Open GUI again
4. See that service has crashed
5. IPC connect message repeats

```
NOTE: connecting to service...
ERROR: ipc connection error, connection refused
NOTE: connecting to service...
ERROR: ipc connection error, connection refused
NOTE: connecting to service...
```

Occurs when restarting the GUI. Might be something to do with the IPC logging?

**Comment by speaker** [comment]
To reproduce either "apply" or "stop/start" a number of times and while processing close and re-open the GUI.

**Comment by nbolton** [comment]
@the-wes Are you still seeing this out in the wild?

**Comment by the-wes** [comment]
I don't recall encountering this issue at all.

**Comment by nbolton** [comment]
Oh, damn, that's not what I thought. I had it in my mind that you were always asking users to manually start their service after it had stopped itself... perhaps I'm imagining things.

**Comment by nbolton** [comment]
Anyway, this happens to me daily and I'm sure I hear of many users experiencing this, so I think its still urgent. Its just not obvious what the problem is, because the service just stops with no errors.

**Comment by the-wes** [comment]
I do occasionally hear from users whose service has stopped, but not in connection with closing or re-opening the GUI or any other particular pattern. So unless the bug is "the service stops sometimes" - I don't see what it is.

Perhaps you could start documenting when you hear it from users?

**Comment by nbolton** [comment]
> Perhaps you could start documenting when you hear it from users?

Good idea. Its usually when I'm browsing support tickets and the like. I'll be sure to make a note here when I see something.

**Comment by nbolton** [comment]
I suspect this was caused by #4651, cautiously closing.
