### ISSUE TITLE
Mac client dies when server has SSL_ERROR_SSL

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4539]
The client doesn't print any error. The last debug message on the client is: `showing cursor`

Server log:

```
NOTE: accepted client connection
INFO: accepted secure socket
DEBUG: received client "ws3.local" info shape=0,0 1920x1080 at 1086,677
DEBUG: active sides: e
NOTE: client "ws3.local" has connected
INFO: switch from "ws1" to "ws3.local" at 1919,701
INFO: leaving screen
DEBUG: open clipboard
INFO: bitmap: 505x52 32
INFO: convert image from: depth=32 comp=3
DEBUG: close clipboard
INFO: screen "ws1" updated clipboard 0
DEBUG: open clipboard
INFO: bitmap: 505x52 32
INFO: convert image from: depth=32 comp=3
DEBUG: close clipboard
INFO: screen "ws1" updated clipboard 1
DEBUG: send clipboard 0 to "ws3.local" size=105092
DEBUG: send clipboard 1 to "ws3.local" size=105092
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: secure socket error: error:1409F07F:SSL routines:ssl3_write_pending:bad write retry
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: secure socket error: error:1409F07F:SSL routines:ssl3_write_pending:bad write retry
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: secure socket error: error:1409F07F:SSL routines:ssl3_write_pending:bad write retry
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: secure socket error: error:1409F07F:SSL routines:ssl3_write_pending:bad write retry
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: secure socket error: error:1409F07F:SSL routines:ssl3_write_pending:bad write retry
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: secure socket error: error:1409F07F:SSL routines:ssl3_write_pending:bad write retry
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: secure socket error: error:1409F07F:SSL routines:ssl3_write_pending:bad write retry
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: secure socket error: error:1409F07F:SSL routines:ssl3_write_pending:bad write retry
NOTE: client "ws3.local" has disconnected
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: secure socket error: error:140D00CF:SSL routines:SSL_write:protocol is shutdown
INFO: jump from "ws3.local" to "ws1" at 960,540
INFO: entering screen
DEBUG: active sides: e
```

**Comment by nbolton** [comment]
@XinyuHou

**Comment by XinyuHou** [comment]
@nbolton  Here is what I found about this error.

"when SSL_Write returns with SSL_ERROR_WANT_WRITE or SSL_ERROR_WANT_READ, you have to repeat the call to SSL_write with the same parameters again, after the condition is satisfied (read/write available on the socket). Calling it with different parameters, will yield the 1409F07F bad write retry error."

**Comment by sarrond** [comment]
https://github.com/synergy/synergy/issues/4539

Hi.

This is the first I've submitted an issue on GitHub, so I apologize if it's better practice to open a new issue. However, I appear to be getting this issue on 1.7.2.

On the server (Windows 7 x64) I get:

    DEBUG: ignored screen "Seans-PC" update of clipboard 1 (unchanged)
    ERROR: secure socket error: SSL_ERROR_SSL
    ERROR: error:1409F07F:SSL routines:ssl3_write_pending:bad write retry
    ERROR: secure socket error: SSL_ERROR_SSL
    ERROR: error:1409F07F:SSL routines:ssl3_write_pending:bad write retry
    NOTE: client "Seans-iMac.local" has disconnected
    ERROR: secure socket error: SSL_ERROR_SSL
    ERROR: error:1409F07F:SSL routines:ssl3_write_pending:bad write retry
    INFO: jump from "Seans-iMac.local" to "Seans-PC" at 960,540
    INFO: entering screen
    DEBUG: active sides: 4

Whilst on the client (Mac OS X 10.10.3) I get:

    WARNING: cursor may not be visible
    ERROR: secure socket error: SSL_ERROR_SYSCALL
    ERROR: secure socket error: SSL_ERROR_SYSCALL
    ERROR: an EOF vi
    olates the protocol
 
    WARNING: cursor may not be visible

In the mean time, I've disabled SSL. If I can provide any additional information, please let me know.
