### ISSUE TITLE
exist-db key alt client java

### ISSUE THREAD

**Issue by adripol94** [synergy/synergy#4543]
key "alt" not found.
When i press alt it doesn't paint nothing...
s.o client: Yosemite IOs
client java: 2.2

Alt+2 expected @ got nothing 
Alt+` expected [ got nothing
Alt+´ expected ] got nothing
Alt+3 expected # got nothing

**Comment by adripol94** [comment]
ups sorry i was wrong '-.-

**Comment by jensopetersen** [comment]
No, you're not: https://github.com/eXist-db/exist/issues/606.

**Comment by speaker** [comment]
Is this than an issue that Synergy is involved with, or is it an eXist-db issue?

**Comment by jensopetersen** [comment]
It is an eXist-db issue and has been there fore quite some time. Frankly speaking, it is minor and I rather doubt it will be fixed, at least anytime soon. One can always insert any Unicode character in the windows where the Alt key is disabled by means of numerical character references, so it is a minor hassle, that's all.

**Comment by speaker** [comment]
Alright. I'll close it then. Thank you for the updates.
