### ISSUE TITLE
How to enable SSL on Yosemite?

### ISSUE THREAD

**Issue by Sydney-o9** [synergy/synergy#4559]
I cannot use SSL on Yosemite. I get the error `crypto disabled because of ns plugin not available`. 

How can we install that `ns plugin`?

As you can see, there is no way to enable SSL..

![screen shot 2015-04-22 at 3 13 41 pm](https://cloud.githubusercontent.com/assets/1480617/7267692/32dcfb00-e902-11e4-9a25-2f31a8f99461.png)

**Comment by XinyuHou** [comment]
Hi there,

Running through wizard could help you download the plugins.

Thanks,
Jerry

--
Xinyu Hou (Jerry)
Senior Software Engineer
<http://synergy-project.org/>

**Comment by Sydney-o9** [comment]
File > Run Wizard.

Note: Very laggy on Yosemite... not usable. Expensive for something we can't use.

**Comment by XinyuHou** [comment]
@Sydney-o9 
Sorry to hear that. I raised another issue for you. Here is the link:

https://github.com/synergy/synergy/issues/4560

Feel free to edit the description and we would look into the problem as soon as possible.

**Comment by nbolton** [comment]
@XinyuHou Hmm, some miscommunication here I think.
@Sydney-o9 Did you mean the connection is laggy? Are you using Wifi? I think you may be experiencing this bug: https://github.com/synergy/synergy/issues/4520

**Comment by Sydney-o9** [comment]
@XinyuHou @nbolton I'm using Wifi. It can't possibly be the problem though.

![screen shot 2015-04-22 at 8 22 57 pm](https://cloud.githubusercontent.com/assets/1480617/7272343/890b70a8-e92d-11e4-95b3-313fa0b8a88c.png)

**Comment by Sydney-o9** [comment]
Hmm could very well be a network error....
![screen shot 2015-04-22 at 8 50 49 pm](https://cloud.githubusercontent.com/assets/1480617/7272848/6d50dc1e-e931-11e4-8d16-425a072b9be7.png)

**Comment by nbolton** [comment]
@Sydney-o9 I'm absolutely certain you're seeing this bug: https://github.com/synergy/synergy/issues/4520
