### ISSUE TITLE
SSL plugin should use TLSv1_method() minimum

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4567]
Use `TLSv1_method()` instead...

```
// create new client-method instance
method = SSLv23_client_method();
```

https://github.com/synergy/synergy/blob/master/src/lib/plugin/ns/SecureSocket.cpp#L219

@VeNoMouS

**Comment by XinyuHou** [comment]
@nbolton 

If I understand it right, it uses TLSv1, with the ability to fall back to SSLv3
"SSLv23_method(void), SSLv23_server_method(void), SSLv23_client_method(void)
A TLS/SSL connection established with these methods may understand the SSLv3, TLSv1, TLSv1.1 and TLSv1.2 protocols.

If extensions are required (for example server name) a client will send out TLSv1 client hello messages including extensions and will indicate that it also understands TLSv1.1, TLSv1.2 and permits a fallback to SSLv3. A server will support SSLv3, TLSv1, TLSv1.1 and TLSv1.2 protocols. This is the best choice when compatibility is a concern."

https://www.openssl.org/docs/ssl/SSL_CTX_new.html

**Comment by nbolton** [comment]
Interesting... maybe add a comment? `// create new client-method instance` seems like a particularly useless comment anyway... what about `//  uses TLSv1, with the ability to fall back to SSLv3`

**Comment by VeNoMouS** [comment]
@XinyuHou is correct , but everyone has abandoned sslv3 after heartbleed etc... tls is considered the industry standard now.

**Comment by nbolton** [comment]
@VeNoMouS You rock! Thanks for reviewing the code :+1:
