### ISSUE TITLE
Make `--crypto-pass` show deprecated message

### ISSUE THREAD

**Issue by Cpuroast** [synergy/synergy#4570]
Problem: The `--crypto-pass` argument is left behind in the registry after a 1.6 to 1.7 upgrade, so when a user upgrades, they need to press 'Apply' in the GUI before it'll work again (not intuitive).

Solution: Give the user a more seamless upgrade by simply showing an "arg deprecated" message when  `--crypto-pass` is used, instead of raising an error and quitting.

----

The upgrade process fails to clear:
--crypto-pass SomeCryptoPass

from:
[HKEY_LOCAL_MACHINE\SOFTWARE\Synergy]
"Command"="\"C:/Program Files/Synergy/synergys.exe\" -f --no-tray --debug INFO --name SomeName  --crypto-pass SomeCryptoPass --ipc --stop-on-desk-switch --enable-drag-drop -c \"D:/SomeUer/Documents/synergy.sgc\" --address :24800"

Resulting in the following error, preventing synergy from starting.
synergys.exe: unrecognized option `--crypto-pass'

This required me to open regedit and manually remove the --crypto-pass option from the "Command" string and restart the synergy service.

**Comment by denilsonsa** [comment]
I can confirm this issue. Also happened to me. There is no UI to let the end-user fix this issue.

**Comment by Elektra58** [comment]
Downgraded. Waiting for a working version. Thank you

**Comment by nbolton** [comment]
The `--crypto-pass` argument was removed in 1.7.

**Comment by Cpuroast** [comment]
The issue is not that the argument was removed, the issue is that the upgrade process doesn't remove it from the registry preventing synergy from starting. 
With no obvious way to fix it except manually editing the registry entry.

**Comment by nbolton** [comment]
Got it, sorry about that.

**Comment by XinyuHou** [comment]
Fixed by c168721.

Sorry @legonigel I didn't notice your pull request.

**Comment by legonigel** [comment]
@XinyuHou The way you fixed this was much better than what I had. :+1:

**Comment by XinyuHou** [comment]
@legonigel Thank you.
