### ISSUE TITLE
Copy paste error of greek characters when using keyboard

### ISSUE THREAD

**Issue by manvla** [synergy/synergy#4574]
Copy paste error of text with Greek characters between Mac OSX Yosemite 10.10.3 and Windows 8.1 when using keyboard.

Original text(Ταξιδια, Ψυχαγωγία, Χρησιμες πληροφοριες, Εστίαση, Ενοικίαση, Οργάνωση,)

Copied text(Œ§Œ±ŒæŒπŒ¥ŒπŒ±, Œ®œÖœáŒ±Œ≥œâŒ≥ŒØŒ±, ŒßœÅŒ∑œÉŒπŒºŒµœÇ œÄŒªŒ∑œÅŒøœÜŒøœÅŒπŒµœÇ, ŒïœÉœÑŒØŒ±œÉŒ∑, ŒïŒΩŒøŒπŒ∫ŒØŒ±œÉŒ∑, ŒüœÅŒ≥Œ¨ŒΩœâœÉŒ∑,)

**Comment by speaker** [comment]
Are the code pages the same on both machines?

**Comment by speaker** [comment]
Looks like a duplucate of #4344
