### ISSUE TITLE
Locking Windows server causes SSL_ERROR_SSL to repeat

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4593]
1. Start Windows server
2. Connect Mac client 
3. Lock Windows server and unlock
4. Message repeats over and over (`ERROR: error:140D00CF:SSL routines:SSL_write:protocol is shutdown`)

**Workaround:** Hit 'Apply' to restart the process, works when it comes back up.

```
INFO: accepted secure socket
NOTE: new client disconnected
ERROR: secure socket error: SSL_ERROR_SYSCALL
NOTE: accepted client connection
INFO: accepted secure socket
NOTE: new client disconnected
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140D00CF:SSL routines:SSL_write:protocol is shutdown
NOTE: accepted client connection
INFO: accepted secure socket
NOTE: new client disconnected
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140D00CF:SSL routines:SSL_write:protocol is shutdown
NOTE: accepted client connection
INFO: accepted secure socket
NOTE: new client disconnected
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140D00CF:SSL routines:SSL_write:protocol is shutdown
NOTE: accepted client connection
INFO: accepted secure socket
NOTE: new client disconnected
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140D00CF:SSL routines:SSL_write:protocol is shutdown
NOTE: accepted client connection
INFO: accepted secure socket
NOTE: new client disconnected
NOTE: accepted client connection
INFO: accepted secure socket
NOTE: new client disconnected
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140D00CF:SSL routines:SSL_write:protocol is shutdown
NOTE: accepted client connection
INFO: accepted secure socket
NOTE: new client disconnected
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140D00CF:SSL routines:SSL_write:protocol is shutdown
NOTE: accepted client connection
INFO: accepted secure socket
```

**Comment by nbolton** [comment]
Actually, pretty sure the `protocol is shutdown` message is not caused by locking the server (but may be related). I think this bug is more likely the cause since its reliably reproducible: #4601

**Comment by xinmeng1** [comment]
I have use the Ubuntu connect with Windows, also encounter this problem. I need to delete the client and re-add client to make it normal.

**Comment by mastastealth** [comment]
I am also experiencing this with a Win 7 server, OSX 10.9 client. It was working for a moment, I did not lock either machine and the client stopped working. Trying to reconnect I just get this:
```
NOTE: accepted client connection
NOTE: new client disconnected
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140D00CF:SSL routines:SSL_write:protocol is shutdown
```

**Comment by mrjester888** [comment]
Same issue here.  Win8.1 + OSX 10.10.3 
After repeating for a couple of minutes, synergys crashes on the windows system.  Synergyc stops and after clicking start, just hangs at "synergy is starting" 

Not sure what the minimal steps are to fix, but I stopped the server, restarted the services and restarted the client to return to operation.

NOTE: accepted client connection
INFO: accepted secure socket
NOTE: new client disconnected
NOTE: accepted client connection
INFO: accepted secure socket
NOTE: new client disconnected
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140D00CF:SSL routines:SSL_write:protocol is shutdown

**Comment by DanWatkins** [comment]
I've noticed that copy+pasting from a Windows Server, everything breaks:

INFO: screen "Dan-PC-NF750" updated clipboard 0
INFO: screen "Dan-PC-NF750" updated clipboard 1
NOTE: client "MacMini" has disconnected
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140D00CF:SSL routines:SSL_write:protocol is shutdown
INFO: jump from "MacMini" to "Dan-PC-NF750" at 960,540

Hitting apply fixed it once, but doing a copy again broke it permanently and required a full system restart.

**Comment by milton-rodriguez-uruit** [comment]
I have the same problem. I couldn't reproduce by using the clipboard, but the error was the same, and I needed to apply several times in client and server in order to get it working again.
Looking forward for a fix.

Thanks for your support and the amazing product!

**Comment by EDToft** [comment]
I turned off SSL on both client and server and can now connect.  

(Caveat) Server is on an XP machine, and the client is on Vista.  GROAN...I know.  For work...ya gotta do what you gotta do.

**Comment by nbolton** [comment]
Duplicates #4650
