### ISSUE TITLE
Server stops when text is copied on server

### ISSUE THREAD

**Issue by weavers** [synergy/synergy#4611]
I am using the Ubuntu (trusty) server with a windows client. When I copy text on the Ubuntu machine to paste on the Windows machine the server stops running. It always happens if I move the cursor from the Windows machine to the Ubuntu machine and perform a copy. When I try and move the cursor back over Synergy has stopped.

**Comment by motopete** [comment]
This behaviour is also confirmed on OS X 10.10.3 (Synergy 1.7.1 server) with Windows 8.1 (1.7.1) client. SSL is enabled.

It only happens with certain types of clipboard items. 

For example:
1. Copy cell content in Numbers.app on OS X. In my test, it's a generic number "16.18".
2. Move cursor to edge of screen to cross over into Windows 8.1 client.
3. Synergy server stops on OS X.

However, this does not happen when copying text from Safari.app or Mail.app. When copying text from Safari or Mail, I'm able to paste it correctly in the Windows client and the OS X server does not stop.

**Comment by bunjiboys** [comment]
I can confirm this also happens with the server (1.7.2) running on Windows 7, and an OSX 1.7.2 client. Quick tests seem to indicate it might be related to when the clipboard contents contains formatting information.

So for example copying text that has markup (background, special color etc) crashes both client and server (depending on where I copy from) but copying plain text doesnt.

**Comment by nkoroste** [comment]
Confirm this bug when copying from Mac OS X v10.9.5 (client) to ubuntu 14.04 (server). The text that was copied looks as follows:

```java
@RunWith(AndroidJUnit4.class)
@SmallTest
public class failureAssumptionTest {
    @Test
    public void checkAssumptionIsSkipped() {
        assumeTrue(false);
    }

    @Test @Ignore
    public void checkIgnoreTestsArePossible() {
        assertTrue(false);
    }
}
```

**Comment by nbolton** [comment]
Duplicates #4601
