### ISSUE TITLE
Missing DLL files after installation.

### ISSUE THREAD

**Issue by m4gnify** [synergy/synergy#4613]
Hi. After installing the 64-bit version of Synergy, I got a message saying that "mingwm10.dll" was missing. After unzipping the while MSI into the Synergy folder, I got a message that "libgcc_s_dw2-1.dll" was missing, but I noticed there was a file called "libgcc_s_dw2_1.dll", so I changed the "_" to a "-", and now it works.

**Comment by sparrowt** [comment]
Looks like https://github.com/synergy/synergy/issues/3774

**Comment by speaker** [comment]
Agreed.
