### ISSUE TITLE
New Encryption feature not working on Mac OS X prior to 10.9

### ISSUE THREAD

**Issue by Ratomas** [synergy/synergy#4615]
Synergy 1.7.1
Mac OS X 10.7.5

I keep getting 

"ERROR: failed to load plugin: libns.dylib
FATAL: An error occurred: dlopen(/Users/*****/Library/Synergy/Plugins/libns.dylib, 1): Symbol not found: _NXArgv
Referenced from: /Users/*****/Library/Synergy/Plugins/libns.dylib
Expected in: /usr/lib/libSystem.B.dylib in /Users/*****/Library/Synergy/Plugins/libns.dylib"

everytime I try to start Synergy. I am trying to run in client mode with a Linux server.

**Comment by Ratomas** [comment]
I have already contacted Synergy support and they have referred me to posting this issue.

https://synergy-project.atlassian.net/servicedesk/customer/portal/4/SHD-75

**Comment by nbolton** [comment]
Duplicates #4648
