### ISSUE TITLE
Slow/Laggy Mouse on Debian Jessie (Client)

### ISSUE THREAD

**Issue by pr0tocol** [synergy/synergy#4616]
Mouse works fine on Windows 8.1 (server). However, when moving from server to client (Debian Jessie box), the mouse lags/slows to the point where it's difficult to use. Has anyone else been experiencing this issue?

**Comment by cmellwig** [comment]
Yes, practically always when starting the client after the server. Try to reboot your server PC. Restarting the service might be enough. Can't test it at the moment because it's not working at all :(

**Comment by speaker** [comment]
If the GUi is running, try closing it and see if that works. Of not that, run the command from a command line directly, (DEBUG logging will show the command).

**Comment by pr0tocol** [comment]
Thanks for this, guys. Restarting the system worked. Apparently, when the server PC goes to sleep and "wakes" back up, it causes the aforementioned issue(s). As long as this doesn't happen, the server-client interaction works fine. 

Again, thanks!
