### ISSUE TITLE
Windows service randomly stops after 'ssl handshake failure' error

### ISSUE THREAD

**Issue by cmellwig** [synergy/synergy#4617]
The server stops working randomly (no screen lock)
Synergy 1.7.1 Pro (activated), SSL enabled
```
NOTE: connecting to service...
NOTE: connection established
```
The server app becomes unresponsive for about 3 minutes at this point
```
NOTE: accepted client connection
ERROR: secure socket error: SSL_ERROR_SYSCALL
ERROR: an EOF violates the protocol
ERROR: failed to accept secure socket
NOTE: client "T20" has disconnected
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140790E5:SSL routines:ssl23_write:ssl handshake failure
.......
```
After restarting it a couple of times, the client (linux) connects again.

I've enabled debug and update with hopefully more detailed logs

**Comment by cmellwig** [comment]
I encountered a new issue. Now the mouse freezes on the server (Win 8.1). Solely CRTL+ALT+DEL is recognized as keyboard input. This happens with both ssl enabled and disabled.

I uploaded a rather large logfile, mb this helps. https://sf.crm114.de/f/953d5db29c/

Is using elevated mode worth a try? I'll also try to use my linux machine as server.

**Comment by nbolton** [comment]
Duplicates #4651
Related to #4677
