### ISSUE TITLE
No connection with 1.7.1 Pro / SSL_ERROR_SSL 140790E5

### ISSUE THREAD

**Issue by schipa** [synergy/synergy#4618]
**Server:**
192.168.2.103 / PascalNote / Win 7 64bit / Synergy 1.7.1 Pro (SSL activated)
**Client:**
192.168.2.106 / PascalHome / Ubuntu 14.10 32bit / Synergy 1.6.2 (via apt-get)

Previously I used 1.6.x with password encryption on server and following command was executed on startup of client (successful connection):
```
synergyc -f --no-tray --debug NOTE --name PascalHome --crypto-pass [...] 192.168.2.103:24800
```

After upgrading to 1.7.1 Pro with SSL, I can't connect anymore and synergy.exe runs on 12% CPU and won't react to actions.
*Server Log*
```
NOTE: connecting to service...
NOTE: connection established
NOTE: starting server
NOTE: config file: C:/Users/pascal/AppData/Local/Temp/qt_temp.gq7652
NOTE: log level: ERROR
activeDesktop:Default
ERROR: secure socket error: SSL_ERROR_SYSCALL
ERROR: an EOF violates the protocol
ERROR: failed to accept secure socket
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140790E5:SSL routines:ssl23_write:ssl handshake failure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140790E5:SSL routines:ssl23_write:ssl handshake failure
...
```
*Client Log* `synergyc -f 192.168.2.103`
```
NOTE: started client
NOTE: connecting to '192.168.2.103': 192.168.2.103:24800
WARNING: failed to connect to server: Timed out
NOTE: connecting to '192.168.2.103': 192.168.2.103:24800
WARNING: failed to connect to server: Timed out
...
```

Am I missing something?

**Comment by thecrazy** [comment]
I am getting the same thing on Xubuntu 14.10 (same logs)

**Comment by ben-duffin** [comment]
Same issue on Yosemite(Client) / Snow  Leopard(Server) - temp fix by disabling SSL on client(s). But then that seems to defeat the reasons for upgrading ...

**Comment by ben-duffin** [comment]
Well - I lie, not the **same** issue but very similar

```NOTE: connecting to '192.168.0.22': 192.168.0.22:24800
2015-05-06 20:28:05.081 synergyc[1452:153275] starting cocoa loop
ERROR: secure socket error: SSL_ERROR_SSL
INFO: server connection may not be secure
NOTE: disconnected from server
ERROR: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
ERROR: failed to connect secure socket```

**Comment by sankalpshere** [comment]
I am getting similar error as well.

ERROR: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol


I am connecting between a Windows and a Mac Pro on version 1.7.2 on either.

**Comment by yangchenyun** [comment]
Me too, after upgrading to 1.7.2, it becomes unusable for me.

**Comment by LindseyB** [comment]
I'm having the same issue Windows (Server) / Yosemite (Client)

**Comment by mccowan** [comment]
Same issue connecting Yosemite client to an Ubuntu server.

This particular client connects to another server instance just fine; this failure occurred when I tried to connect it to a second server.  (Maybe it's a matter of needing to accept multiple certificates?)

**Comment by catch2000** [comment]
After upgrading to 1.7.2, I also have the same issue Win7 (Server 1.7.2)/ Ubuntu14.04(Client 1.7.2).
The log is:
NOTE: accepted client connection
INFO: accepted secure socket
ERROR: secure socket error: SSL_ERROR_SYSCALL
ERROR: secure socket error: SSL_ERROR_SYSCALL
NOTE: new client disconnected
NOTE: accepted client connection
INFO: accepted secure socket
NOTE: new client disconnected
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140D00CF:SSL routines:SSL_write:protocol is shutdown

**Comment by StephanX** [comment]
I'm also affected, Ubuntu 15.04 => OSX 10.10

Disabling SSL works normally.

**Comment by xorinzor** [comment]
Same happens in Windows 10 when the client connects.

In window it even freezes the client, only fixable by restarting the synergyd service.

**Comment by m-ober** [comment]
Same issue for me with Linux Mint 17.1 client an Windows 7 64-bit server ("handshake failure").
The client log also says "NOTE: crypto disabled because of ns plugin not available"

**Comment by nbolton** [comment]
Duplicates #4566

**Comment by EDToft** [comment]
I turned off SSL on both client and server and can now connect.

(Caveat) Server is on an XP machine, and the client is on Vista. GROAN...I know. For work...ya gotta do what you gotta do.

**Comment by EDToft** [comment]
Perhaps it is an OPEN-SSL bug...
http://cplusplusio0.blogspot.com/2015/03/using-openssl-with-its-unblocked-bio.html

**Comment by Thlayli** [comment]
Had similar issue between two Win7 machines. Turned off SSL and connected, then turned SSL back on and reconnected. Fixed it in my case.

**Comment by Shivaess** [comment]
Having a similar issue between Ubuntu and Win7 machines. Getting ERROR: secure socket error: SSL_ERROR_SYSCALL from the windows based server. Restarting both server/client/windows service seems to resolve the error for varied amounts of time. (anywhere from a day to 2 minutes)

**Comment by nerocom** [comment]
Similar issue on 1.7.3

SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

It's only from Mac=> PC server. PC to PC does not error. SSL is enabled on all 3.

**Comment by MasterOfTheHat** [comment]
Same issue with upgrade to 1.7.3.
Server is Windows 8.1 running 1.7.3
Client is Mac OS X 10.10.3 running 1.7.3

Disabling SSL on both allows connection. 
Reenabling SSL on both asked for verification of SSL fingerprint on client and then it worked. 

Anyone tried this with a new install of 1.7.x instead of an upgrade?

ERROR: ssl error occurred (generic failure)
ERROR: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
ERROR: failed to connect secure socket

**Comment by ColinAnthony** [comment]
Same issue upgrade to 1.7.3
Server, windows 7
client mint 17
disabling ssl works
downgrading to 1.6 ...again

ERROR: ssl error occurred (generic failure)
ERROR: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
ERROR: failed to connect secure socket

**Comment by Zapnologica** [comment]
Any solutions besides disabling ssl? I have uninstalled. Deleted temp data. Reinstalled. Then run the setup wizard where it says downloading plugin and It is still giving the same issue.

**Comment by Thlayli** [comment]
Be sure you connect the two devices without SSL before trying it with SSL
turned on. That was the key to getting it to work on my system.

**Comment by Hazyface** [comment]
Got it working by re-running the Setup Wizard on server, then on the client. After starting again, the client asked if OK to trust the new server fingerprint, and then it worked fine.

Synergy 1.7.3
Server OS X 10.10.3
Client: Windows 7

**Comment by qipengos** [comment]
Here is the resolution:
https://ask.fedoraproject.org/en/question/42001/synergy-no-route-to-host-but-i-can-ping-from-terminal/

**Comment by liukun** [comment]
Run wizard again on client works for me.

**Comment by DigitalEyeCandy** [comment]
This worked for me:

1. Run wizard on both
2. Disable SSL on both
3. Start client (Mac) first
4. Once client is fully running, start server (Win7)
5. Stop client, then stop server
6. Enable SSL on both, start client, start server.
7. Get prompted for fingerprint of server, click YES/OK.

**Comment by fireundubh** [comment]
Encountered the same issue with these systems on Synergy 1.8.4-stable-a6ff907:

- Server: Windows 10 Pro 10.0.14393 (64-bit)
- Client: macOS Sierra 10.12.1 (64-bit)

Tried @DigitalEyeCandy's steps, but I didn't need as many to get SSL to work.

1. Re-enabled SSL on server and client.
2. Started client. (Also re-enabled auto-config.)
3. Started server.
4. Accepted fingerprint on client.

**Comment by Stormwing** [comment]
I had this issue as well. I noticed that my Server machine had Synergy Pro, while the client had only Basic. I had entered my serial number into the client incorrectly. Once I fixed that I was able to connect without issue once more.

**Comment by starsparrow** [comment]
Having this or a similar problem at the moment:

[2017-01-23T10:35:45] INFO: watchdog status: ok
[2017-01-23T10:35:50] INFO: OpenSSL 1.0.2 22 Jan 2015
[2017-01-23T10:36:05] ERROR: ssl error occurred (system call failure)
[2017-01-23T10:36:05] ERROR: eof violates ssl protocol
[2017-01-23T10:36:05] ERROR: failed to accept secure socket
[2017-01-23T10:36:05] INFO: client connection may not be secure
[2017-01-23T10:36:06] INFO: OpenSSL 1.0.2 22 Jan 2015
[2017-01-23T10:36:21] ERROR: ssl error occurred (system call failure)
[2017-01-23T10:36:21] ERROR: eof violates ssl protocol
[2017-01-23T10:36:21] ERROR: failed to accept secure socket
[2017-01-23T10:36:21] INFO: client connection may not be secure

**Comment by trocster** [comment]
Had same issue with 

[2017-10-02T14:40:51] INFO: OpenSSL 1.0.2 22 Jan 2015
[2017-10-02T14:40:52] ERROR: ssl error occurred (system call failure)
[2017-10-02T14:40:52] ERROR: eof violates ssl protocol

Version: synergy Pro on linux (synergy-v1.8.8-stable-c30301e-Source) and windows 10 (client 1.8.8-stable-25a8cb2)

It was not having a key/cert under ~/.synergy/SSL/Synergy.pem

# make directory for certificate
$mkdir -p ~/.synergy/SSL/

# cd into it
$cd $_

# generate key and (self signed) certificate
$openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout localhost.key -out localhost.crt

# put them ina file that synergys accepts
$cat localhost* >> Synergy.pem

restart synergys and set to use SSL on both sides, tickbox on windows and --enable-crypto on *nix, then accept the new 'fingerprint' when windows reconnects.
