### ISSUE TITLE
Refuses to move to other computer screen with too much on clipboard

### ISSUE THREAD

**Issue by heinst** [synergy/synergy#4619]
Hi,

If you have too much on your clipboard (even like 15 lines of 20-30 characters each) synergy will refuse to go to the other screen. I bring it to the edge of the screen to switch screens, like normal, it pauses for a second or two, then bounces back to the center of the screen and will not move. I am on Synergy Pro 1.7.1 with Windows 7 as the server and a Mac OS X Yosemite machine as the only client.

Thanks
Trevor Heins

**Comment by heinst** [comment]
Didn't see that @nbolton already reported this...sorry!

**Comment by nbolton** [comment]
#4601
