### ISSUE TITLE
Setup Wizard Does Not Complete after ns plugin downloaded

### ISSUE THREAD

**Issue by bobjunior** [synergy/synergy#4620]
Using Synergy 1.7.1 Pro, Ubuntu 14.04 Server and Windows 8 client.

After successfully installing Synergy, cannot complete setup wizard to complete registration.

Stuck at last screen, Downloading plugins: ns (1/1).
It appears to complete the plugin, but finish button is simply never enabled.

Had no issues on 1.6 for usage or registering.

**Comment by caturday** [comment]
Same issue here. Synergy 1.7.1 Pro, Windows 7 64-bit client. Network capture suggests that some traffic is happening while on the "Downloading plugins" screen - doesn't appear to be using system proxy settings for plugin download.

**Comment by bobjunior** [comment]
Ya, I'm behind a proxy and both systems need to use it.

**Comment by Schubi80** [comment]
Same problem here. Proxy must be used and wizard cannot be completed.

**Comment by caturday** [comment]
Yep. The login request uses the proxy, but the downloader does not.

**Comment by mgkwill** [comment]
I'm seeing the same issue on synergy-v1.7.2-stable-728e9cd-Linux-x86_64.rpm on Fedora 20.

When 'setup synergy' wizard moves to 'downloading plugin: ns (1/1)' the following error appear in the console:
```
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QNetworkAccessManager(0x2bd2cc0), parent's thread is QThread(0x265e690), current thread is QThread(0x2910800)
```
Download never completes, presumably because of proxy.

**Comment by mgkwill** [comment]
In DataDownloader.h, QNetworkAccessManager is declared but a proxy is not set:
```
class DataDownloader : public QObject
{
	Q_OBJECT

public:
	explicit DataDownloader(QObject* parent = 0);
	virtual ~DataDownloader();

	QByteArray data() const;
	void cancel();
	void download(QUrl url);
	bool isFinished() const { return m_IsFinished; }

signals:
	void isComplete();

private slots:
	void complete(QNetworkReply* reply);

private:
	QNetworkAccessManager m_NetworkManager;
	QByteArray m_Data;
	QNetworkReply* m_pReply;
	bool m_IsFinished;
};
```
QNetworkAccessManager must set a proxy as is laid out in these docs to work behind a proxy:
http://doc.qt.digia.com/4.6/qnetworkproxyfactory.html#systemProxyForQuery
http://doc.qt.digia.com/4.6/qnetworkaccessmanager.html#setProxyFactory

**Comment by nbolton** [comment]
Duplicates: #4664

**Comment by phutchins** [comment]
I'm still getting this error when installing synergy under Antergos Linux. Anyone know the solution?
