### ISSUE TITLE
libssl.so.10 missing

### ISSUE THREAD

**Issue by kepi** [synergy/synergy#4621]
Hey, I just downloaded most recent synergy and when I activate pro features with SSL, client cannot be started.

I'm using Debian unstable.

    ERROR: failed to load plugin: libns.so
    FATAL: An error occurred: libssl.so.10: cannot open shared object file: No such file or directory
    NOTE: stopping synergy desktop process

According to apt-file there is no libssl.so.10 in distribution.

**Comment by suxfuuu** [comment]
Same problem here, i'm on debian.

**Comment by retracement** [comment]
Yep same here. Wish Id seen these comments first. Ive just done it. Was running 1.71 so updated to 1.72. Issue still there. Using x64:
Distributor ID:	LinuxMint
Description:	Linux Mint 17.1 Rebecca
Release:	17.1
Codename:	rebecca

Windows x64 8.1 updated without incident :(

**Comment by retracement** [comment]
Ok guys have got a quick workaround (and more info).
Close down and quit the synergy app on Linux. Launch term and run it elevated (sudo synergy). Assuming that this was your server, you will need to disable SSL encryption in synergy settings -in order for those client connections to be accepted. The output I got from the server is below. I'm going to have a look at those urls referenced.....
r@l ~ $ sudo synergy
[sudo] password for r: 
"sni-qt/17371" WARN  14:57:31.039 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
*** WARNING *** The program 'synergy' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=synergy>
*** WARNING *** The program 'synergy' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=synergy&f=DNSServiceRegister>
("-f", "--no-tray", "--debug", "INFO", "--name", "l", "--enable-crypto", "-c", "/tmp/qt_temp.J17371", "--address", ":24800") 

(synergy:17371): Gtk-CRITICAL **: IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed

(synergy:17371): Gtk-CRITICAL **: IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed

**Comment by suxfuuu** [comment]
https://github.com/synergy/synergy/issues/4565

other topic about the same issue

**Comment by cledoux** [comment]
Duplicate of #4565 

Recompiling from source and replacing ~/.synergy/plugins/libns.so with <buildpath>/bin/plugins/libns.so seems to be a viable workaround so far.

**Comment by crlsgms** [comment]
I had the same issue, downloaded version 1.7.2 the website, ill rollback to the early release and wait for stable then.

**Comment by kepi** [comment]
Looks like my issue-search-fu is not good. Thanks for pointing out that this is duplicate of #4565.
