### ISSUE TITLE
Runaway logging causes GUI to freeze

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4624]
1. **Open GUI**
2. Experience bug #4650 (or other runaway log bug)
3. Wait for server cursor to freeze
4. Service and GUI gobble up memory

![image](https://cloud.githubusercontent.com/assets/313427/7655787/f89dcb26-fb1d-11e4-92b3-ceddf72399f4.png)

```
INFO: accepted secure socket
ERROR: secure socket error: SSL
_ERROR_SSL
ERROR: error:140780E5:SSL routines:ssl23_read:ssl handshake failure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140790E5:SSL routines:ssl23_write:ssl handshake failure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140790E5:SSL routines:ssl23_write:ssl handshake failure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140790E5:SSL routines:ssl23_write:ssl handshake failure
ERROR: secure socket error: SSL_ERROR_SSL
```

**Comment by 130s** [comment]
This happens to me:
- Server: Ubuntu 14.04 64b, Synergy 1.7.2
- Client: OSX 10.10, Synergy 1.7.2

**Comment by aitherios** [comment]
Also happening to me with the opposite setup:
* Server: OSX 10.10 synergy 1.7.2
* Client: Ubuntu 15.04 64bits synergy 1.7.2

**Comment by krioles** [comment]
Mine works fine with:
* Server: Windows 7 64 bit synergy 1.7.2
* Client: OSX 10.10 synergy 1.7.2

But I get the referenced error when I start up my other client
* Linux Mint 17.1 (based on Ubuntu 14.04) synergy 1.7.2

**Comment by bcoia** [comment]
Happening for me with:
* Server: Windows 8.1 64 bit, Synergy 1.7.2
* Client: OSX 10.10, Synergy 1.7.2

**Comment by stockmaster** [comment]
Same problem for me, Client locks down - non responding - must Kill the process and reboot machine all toguether.
Sever and all clietns on WIn 8.1 64b, synergy 1.7.2

**Comment by stockmaster** [comment]
Something extreamly severe is happening with 1.7.2

![](http://i.imgur.com/8B89qnr.png)
the service is taking up 12gb of memory?1

**Comment by nbolton** [comment]
@stockmaster Its the IPC log buffer. SSL is spamming errors. The underlying problem is that the log buffer size is unlimited, which is a silly bug.

**Comment by nbolton** [comment]
Note: The 99% CPU used comes from the GUI being spammed and handling many IPC log messages.

**Comment by stockmaster** [comment]
@nbolton Any idea when this will be addressed?
I tried to downgrade to 1.7.1 but now the problem persists, so i am unable to use synergy at all

Thanks

**Comment by nbolton** [comment]
v1.7.3-stable
 Due by May 27, 2015

**Comment by stockmaster** [comment]
Thank you!

**Comment by nbolton** [comment]
This revision is now available to test:
http://synergy-project.org/nightly?filter=master-2cce60f
