### ISSUE TITLE
Dragging file between machines makes the client disconnect

### ISSUE THREAD

**Issue by shoelzer** [synergy/synergy#4629]
I just updated two Windows machines to 1.7.2 (from 1.7.1) and turned on SSL. When I try to drag a file from one screen to another the file does not copy and the client disconnects. The client tries to reconnect but it cannot. I have to manually stop and start Synergy on the client and server to reconnect.

**Comment by joelcarlton** [comment]
I can verify I have the same issue. If I forget that I am running two computers and not two monitors on one computer and drag a window to the second screen the client disconnects.

Drag window on the mac to edge of monitor that borders windows and mac client disconnects.

Server: Windows 7 64bit
Client: Mac OS X 10.10.3

**Comment by styks1987** [comment]
I have the same issue.
Server: Mac OS X 10.10.3
Client: Windows 7 64bit

**Comment by nbolton** [comment]
Duplicates #4584
