### ISSUE TITLE
Installed 1.7.2 and now the application is in Spanish

### ISSUE THREAD

**Issue by LunaticoCR** [synergy/synergy#4630]
After I upgraded to 1.7.2 my application is now in Spanish.
I'm on OSX 10.10.3 and I was running 1.7.1 before the upgrade, which was displaying in English. The OS language is set to English. Not sure why Synergy has picked up Spanish and now I can't seem to be able to change it back.
Tried the same in 2 more computer but couldn't reproduce it.

EDIT: I realised after that Synergy has it's own way of selecting the language in Preferences. I changed it to English and now is good. Still not sure how it got changed to Spanish.

**Comment by speaker** [comment]
Glad you got this one figured out, I'm stumped as well.
