### ISSUE TITLE
synergy-project.org's certificate expired..

### ISSUE THREAD

**Issue by ssreekanth** [synergy/synergy#4638]
![certificate](https://cloud.githubusercontent.com/assets/1380334/7531602/440c8d30-f511-11e4-86b3-ce69229d04fb.png)

Run Wizard -> Activate -> fails

![activation](https://cloud.githubusercontent.com/assets/1380334/7531607/5a16674a-f511-11e4-9465-5c6afb18fec7.png)

**Comment by minimoe** [comment]
The Windows version has the same issue.

![image](https://cloud.githubusercontent.com/assets/68598/7532620/4b04d572-f569-11e4-9720-8499e3b3f959.png)

**Comment by minimoe** [comment]
Just verified that the Windows issue is caused by the SSL error.

Using Fiddler Web Debugger I can "bypass" the expired certificate and login works.

**Comment by nbolton** [comment]
Fixed, sorry that was a really dumb mistake of mine!
