### ISSUE TITLE
Mac Server, Windows Client, screenshots not working anymore, crash client

### ISSUE THREAD

**Issue by DougYS** [synergy/synergy#4646]
Hi there,

Using Mac OS X 10.10.3 as the server and Windows 7 x64 as the client, both with Synergy 1.7.2 Pro, if I take a screenshot on the Windows computer (using a Windows-connected keyboard, thanks to no PrintScreen key on Macs), the Windows client will disconnect and will be unconnectable until you manually stop and start the client. The screenshot will not be transferred to the Mac's clipboard (although it does stay on the Windows computer and Dropbox does put it into its screenshots folder automatically as usual).

Screen shots worked just fine on 1.7.1 non-Pro for taking on Windows and then pasting into documents on the Mac.

The log message from the client computer are below.

Screenshots are very useful. I'm not sure if it is a 1.7.2 bug or a Pro bug. However, the "secure socket error" seems to make me think it's a Pro bug.

Thanks,

Doug

INFO: service command updated
INFO: starting new process
activeDesktop:Default
INFO: starting new process
INFO: drag and drop enabled
NOTE: started client
NOTE: connecting to '192.168.1.107': 192.168.1.107:24800
INFO: watchdog status: ok
NOTE: server fingerprint: B1:3A:67:11:3C:DC:EB:89:3C:01:6D:A5:51:DB:2A:5A:D1:75:DF:20
INFO: connected to secure socket
INFO: server ssl certificate info: /CN=Synergy
NOTE: connected to server
INFO: entering screen
INFO: leaving screen
INFO: bitmap: 2560x1600 32
INFO: convert image from: depth=32 comp=3
INFO: bitmap: 2560x1600 32
INFO: convert image from: depth=32 comp=3
INFO: entering screen
INFO: leaving screen
INFO: bitmap: 2560x1600 32
INFO: convert image from: depth=32 comp=3
INFO: bitmap: 2560x1600 32
INFO: convert image from: depth=32 comp=3
INFO: entering screen
INFO: leaving screen
INFO: bitmap: 2560x1600 32
INFO: convert image from: depth=32 comp=3
INFO: bitmap: 2560x1600 32
INFO: convert image from: depth=32 comp=3
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140D00CF:SSL routines:SSL_write:protocol is shutdown
NOTE: disconnected from server
NOTE: connecting to '192.168.1.107': 192.168.1.107:24800
NOTE: server fingerprint: B1:3A:67:11:3C:DC:EB:89:3C:01:6D:A5:51:DB:2A:5A:D1:75:DF:20

**Comment by nbolton** [comment]
Duplicates #4601
