### ISSUE TITLE
Mouse is behaving strangely

### ISSUE THREAD

**Issue by Cheesebaron** [synergy/synergy#4649]
I use a Mac as Server and Windows 8.1 machine as client both running 1.7.2 but also occurs on 1.7.1, both running with SSL.

After a while, clicks stop working on the Windows 8.1 task bar, middle click is erratic and works sometimes, other times after clicking middle click and then left mouse button, the left click becomes middle click.
On the server hovering the mouse over a text field in a web browser, link etc., the mouse cursor does not change until you click the element. Middle click also behaves strangely as on Windows.

Stopping synergy does not seem to do something :sob:

Sometimes after locking and unlocking the screen on Windows the cursor speed changes, which another user also reported here.

**Comment by speaker** [comment]
There are a number of changes in 1.7.3 and 1.7.4 hat can cause these kinds of effects. ave you checked with 1.7.3 to see if there is any improvement?
