### ISSUE TITLE
SSL error log message repeats excessively and freezes cursor

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4650]
After checking `synergyd.log` I see that the following message repeated 416433 times.

```
ERROR: error:140790E5:SSL routines:ssl23_write:ssl handshake failure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140790E5:SSL routines:ssl23_write:ssl handshake failure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140790E5:SSL routines:ssl23_write:ssl handshake failure
ERROR: secure socket error: SSL_ERROR_SSL
```

Also causes a "synergys.exe crash in LIBEAY32.dll" 

```
Problem signature:
Problem Event Name:	APPCRASH
Application Name:	synergys.exe
Application Version:	0.0.0.0
Application Timestamp:	554b4d07
Fault Module Name:	LIBEAY32.dll
Fault Module Version:	1.0.2.0
Fault Module Timestamp:	550d736a
Exception Code:	c0000005
Exception Offset:	000000000009e236
OS Version:	6.1.7601.2.1.0.768.3
Locale ID:	2057
Additional Information 1:	f489
Additional Information 2:	f4899f4fbc65312bd5be12950e807458
Additional Information 3:	55b1
Additional Information 4:	55b1d379d9809312973fc308a98a09ef
```

**Comment by aedocw** [comment]
I am getting the same error running v1.7.2 on two linux machines
Server: Ubuntu 15, kernel 3.19.0-16-generic
Client: Ubuntu 14, kernel 3.13.0-33-generic

**Comment by nbolton** [comment]
@aedocw Does it crash the GUI?

**Comment by Elektra58** [comment]
Same here on Windows 8.1 64. The GUI becomes unresponsive. Here is an excerpt from the log file:
```
INFO: starting new process
INFO: drag and drop enabled


NOTE: started server, waiting for clients


INFO: watchdog status: ok
NOTE: accepted client connection


INFO: watchdog status: ok
ERROR: secure socket error: SSL_ERROR_SYSCALL


ERROR: an EOF violates the protocol

ERROR: failed to accept secure socket

INFO: client connection may not be secure


INFO: accepted secure socket


ERROR: secure socket error: SSL_ERROR_SSL


ERROR: error:140790E5:SSL routines:ssl23_write:ssl handshake failure
```
etc.

**Comment by nbolton** [comment]
@XinyuHou To solve this we **must** limit the retry mechanism to a specific number, like 100 attempts (instead of letting it run away to 416433 attempts).

**Comment by nbolton** [comment]
I just fixed #4651 and #4624, so it should be a little easier to reproduce this.

**Comment by dinomite** [comment]
I see this on Mac OS X 10.10.3 (both machines).  Happy to provide any info.

**Comment by NadeoWolf** [comment]
I have the same Problem. I have created 2 Logs with LVL Debug2 :

Server(440MB) : https://www.dropbox.com/s/2rdspsu3qvn40dy/synergy_server.log?dl=0
Client(240MB) : https://www.dropbox.com/s/9awkskx50usmc9o/synergy.log?dl=0

Both Logs are from ONE Session(ca. 15 Minutes) 

Server: i7-3Generation,8GB Ram,Win 7 64-Bit, Connection: Wifi
Client: i5-4Generation,16GB Ram,Win 7N(European Version) 64-Bit, Connection: Gigabit Lan

i hope this helps to solve this problem.

**Comment by pithium** [comment]
I confirmed this on Windows 7 and Slackware 14.1 servers, both registered and SSL enabled. It occurs only when attempting to connect from a client not using SSL. After failing once, the synergys process must be completely cleared from memory or I won't be able to get anything done.

This is a major pain on Windows. Linux recovers a little better but maxes out CPU usage on a single core. Ungraceful error handling?
Log output after unencrypted client attempts connection:

```
NOTE: started server, waiting for clients
NOTE: accepted client connection
ERROR: some secure socket I/O error occurred
ERROR: an EOF violates the protocol
ERROR: failed to accept secure socket
INFO: client connection may not be secure
INFO: accepted secure socket
ERROR: a failure in the SSL library occurred
ERROR: error:140780E5:SSL routines:SSL23_READ:ssl handshake failure
ERROR: a failure in the SSL library occurred
ERROR: error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure
ERROR: a failure in the SSL library occurred
```

Synergy is amazing! This isn't that big of an error imo.

**Comment by XinyuHou** [comment]
@pithium Hi, did you download the plugins by run through wizard or compile the plugins yourself? Thanks.

**Comment by pithium** [comment]
In Windows 7 plugin was downloaded through activation. Slackware plugin must be compiled due to bugs #4565 and #4645.

**Comment by dinomite** [comment]
@pithium On my Macs (10.10), this is blocker.  This caused Synergy to stop working for me and downgrading didn't help :-/

**Comment by XinyuHou** [comment]
@pithium Does the log you posted from Slackware server? Thanks.

**Comment by pithium** [comment]
@dinomite I don't have a Mac to test unfortunately. However the SSL issues I have encountered Windows/Linux side seem to be most problematic when committing "user error".

It has never been a problem as long as I am certain that SSL is functional on both server and client before launching processes. I know Windows was causing problems when it crashed because Synergy was still in memory. 

Can you verify that Synergy processes have been killed by OS X before attempting the fixes mentioned here and on forums?

**Comment by pithium** [comment]
@XinyuHou Yes it is.

**Comment by dinomite** [comment]
@pithium Heh, I wouldn't say user error, but I was able to track the root ssl-not-working-making-the-whole-thing-not-work: Synergy was unable to download the ns plugin on one the client due to some VPN configuration.  Reinstalled and that's working now.

**Comment by pithium** [comment]
@dinomite Nice. Glad it's working! :)

**Comment by speaker** [comment]
A Number of issues have been fixed that will add methods to avoid runaway logging based on SSL problems. The changes I added will break out of the case where a retry on a non-fatal SSL state might loop out of control. It will also add some logging to try and allow us to identify the state if entered in the future.

**Comment by speaker** [comment]
I have opened #4694 to address the issues raised by @pithium

**Comment by nbolton** [comment]
For testing: http://synergy-project.org/nightly?filter=18d85f1

**Comment by nbolton** [comment]
#4695 should make this easier to test.

**Comment by nbolton** [comment]
Blocked by #4696

**Comment by speaker** [comment]
If a client is non-SSL and keeps banging on an SSL server, this can't be avoided completely. Whatever log level is set will generate messaging about failed connections. #4698

**Comment by nbolton** [comment]
@speaker I just pushed d3d1db2 to my own branch (for testing) as I can't seem to get a client to connect (it always exceeds the retry limit). Is it working for you?

Try this one, it should re-run the wizard and download a very recent version of the SSL plugin... http://synergy-project.org/nightly?filter=synergy-master-3563217

**Comment by stockmaster** [comment]
as An update, if you dont kill the process and service of synergy, it will create a Error log file 150gb in size in a few mins!

**Comment by nbolton** [comment]
@stockmaster The log size bug was fixed in ad4c799 (#4677).

**Comment by nbolton** [comment]
Seems to be fixed, good job Adam! :+1: 

When a non-SSL client tries to connect, I now see a much more "cursor friendly" error message...
```
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
```

**Comment by nbolton** [comment]
p.s. When connecting from my Mac, I'll intermittently/occasionally see...

```
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to connect secure socket
NOTE: disconnected from server
NOTE: stopping synergy desktop process
```

But reconnecting seems to solve this, I don't think many people will be too angry about this, but we should try to make the Mac handshake more robust on the client side.

**Comment by Pilskalns** [comment]
Hi, Just upgraded to 1.7.3-stable and now I can't connect to server when usin SSL. Server is Win8.1 x64 and client Win8 x64. Below logs from both.

On server I got:

>NOTE: starting server
NOTE: command: "C:/Program Files/Synergy/synergys.exe" -f --no-tray --debug DEBUG2 --name Vienradzis --ipc --stop-on-desk-switch --enable-drag-drop --enable-crypto --profile-dir "C:\Users\Anda\AppData\Local" -c "C:/Users/Anda/AppData/Local/Temp/qt_temp.if1480" --address 192.168.1.3:24800
NOTE: config file: C:/Users/Anda/AppData/Local/Temp/qt_temp.cr1480
NOTE: log level: DEBUG2
INFO: service command updated
DEBUG: getting elevated token, elevation required
DEBUG: processes in session 1: csrss.exe, winlogon.exe, dwm.exe, atieclxx.exe, EasySettingsCmdServer.exe, taskhostex.exe, sSettings.exe, igfxext.exe, igfxEM.exe, igfxHK.exe, igfxTray.exe, BtvStack.exe, ActivateDesktop.exe, AdSync.exe, Skype.exe, chrome.exe, googledrivesync.exe, OctoshapeClient.exe, MFManager.exe, Dropbox.exe, EvernoteClipper.exe, avgnt.exe, MOM.exe, jusched.exe, googledrivesync.exe, chrome.exe, CommonAgent.exe, Avira.OE.Systray.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, CCC.exe, explorer.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, synergy.exe, chrome.exe, 
DEBUG: found winlogon.exe in session 1
DEBUG: got token 1136, duplicating
DEBUG: duplicated, new token: 1156
INFO: starting new process
DEBUG: launched syntool to check active desktop
activeDesktop:Default
DEBUG: getting elevated token, elevation required
DEBUG: processes in session 1: csrss.exe, winlogon.exe, dwm.exe, atieclxx.exe, EasySettingsCmdServer.exe, taskhostex.exe, sSettings.exe, igfxext.exe, igfxEM.exe, igfxHK.exe, igfxTray.exe, BtvStack.exe, ActivateDesktop.exe, AdSync.exe, Skype.exe, chrome.exe, googledrivesync.exe, OctoshapeClient.exe, MFManager.exe, Dropbox.exe, EvernoteClipper.exe, avgnt.exe, MOM.exe, jusched.exe, googledrivesync.exe, chrome.exe, CommonAgent.exe, Avira.OE.Systray.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, CCC.exe, explorer.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, synergy.exe, chrome.exe, syntool.exe, conhost.exe, 
DEBUG: found winlogon.exe in session 1
DEBUG: got token 1080, duplicating
DEBUG: duplicated, new token: 1092
INFO: starting new process
INFO: drag and drop enabled
DEBUG: opening configuration "C:/Users/Anda/AppData/Local/Temp/qt_temp.if1480"
DEBUG: configuration read successfully
DEBUG: plugins dir: C:\Users\Anda\AppData\Local\Synergy\Plugins
DEBUG: loading plugin: ns.dll
DEBUG1: thread 0x00000470 entry
DEBUG: loaded plugin: ns.dll
DEBUG1: starting server
DEBUG: screen shape: 0,0 1366x768 
DEBUG: window is 0x000904da
ERROR: failed to get desktop path, no drop target available, error=2
DEBUG: adopting new buffer
DEBUG: opened display
DEBUG1: registered event type IScreenEvents::error as 4
DEBUG1: registered event type IScreenEvents::suspend as 5
DEBUG1: registered event type IScreenEvents::resume as 6
DEBUG1: creating primary screen
DEBUG1: binding listen socket
DEBUG1: listening for clients
DEBUG1: registered event type IListenSocketEvents::connecting as 7
DEBUG1: registered event type ClientListenerEvents::connected as 8
DEBUG1: registered event type IKeyStateEvents::keyDown as 9
DEBUG1: registered event type IKeyStateEvents::keyUp as 10
DEBUG1: registered event type IKeyStateEvents::keyRepeat as 11
DEBUG1: registered event type IPrimaryScreenEvents::buttonDown as 12
DEBUG1: registered event type IPrimaryScreenEvents::buttonUp as 13
DEBUG1: registered event type IPrimaryScreenEvents::motionOnPrimary as 14
DEBUG1: registered event type IPrimaryScreenEvents::motionOnSecondary as 15
DEBUG1: registered event type IPrimaryScreenEvents::wheel as 16
DEBUG1: registered event type IPrimaryScreenEvents::screensaverActivated as 17
DEBUG1: registered event type IPrimaryScreenEvents::screensaverDeactivated as 18
DEBUG1: registered event type ServerEvents::switchToScreen as 19
DEBUG1: registered event type ServerEvents::switchInDirection as 20
DEBUG1: registered event type ServerEvents::keyboardBroadcast as 21
DEBUG1: registered event type ServerEvents::lockCursorToScreen as 22
DEBUG1: registered event type IPrimaryScreenEvents::fakeInputBegin as 23
DEBUG1: registered event type IPrimaryScreenEvents::fakeInputEnd as 24
DEBUG1: registered event type IScreenEvents::fileChunkSending as 25
DEBUG1: registered event type IScreenEvents::fileRecieveCompleted as 26
DEBUG1: registered event type IScreenEvents::shapeChanged as 27
DEBUG1: registered event type ClipboardEvents::clipboardGrabbed as 28
DEBUG1: registered event type ClipboardEvents::clipboardChanged as 29
DEBUG: active sides: 4
DEBUG: active sides: 4
DEBUG1: half-duplex caps-lock off
DEBUG1: half-duplex num-lock off
DEBUG1: half-duplex scroll-lock off
DEBUG1: screen saver synchronization on
DEBUG1: grab the foreground window
DEBUG1: modifiers on update: 0x2000
DEBUG1: thread 0x00001580 entry
DEBUG: desk Default window is 0x000604e0
DEBUG: switched to desk "Default"
DEBUG: desktop is now accessible
DEBUG1: modifiers on update: 0x2000
DEBUG1: modifiers on update: 0x2000
DEBUG1: registered event type IPrimaryScreenEvents::hotKeyDown as 30
DEBUG1: registered event type IPrimaryScreenEvents::hotKeyUp as 31
DEBUG1: registered event type ServerEvents::connected as 32
DEBUG: registered hotkey ScrollLock (id=ef14 mask=0000) as id=1
DEBUG1: registered event type ServerEvents::disconnected as 33
DEBUG1: registered event type ServerEvents::screenSwitched as 34
NOTE: started server, waiting for clients
DEBUG1: registered event type IDataSocketEvents::connected as 35
DEBUG1: registered event type IStreamEvents::inputReady as 36
DEBUG1: registered event type IpcServerProxyEvents::messageReceived as 37
DEBUG1: registered event type IpcClientEvents::messageReceived as 38
DEBUG1: registered event type ServerAppEvents::reloadConfig as 39
DEBUG1: registered event type ServerAppEvents::forceReconnect as 40
DEBUG1: registered event type ServerAppEvents::resetServer as 41
DEBUG: event queue is ready
DEBUG: add pending events to buffer
DEBUG: screen "Vienradzis" shape changed
DEBUG1: registered event type IpcClientEvents::connected as 42
DEBUG2: writef(IHEL%1i)
DEBUG2: wrote 5 bytes
DEBUG1: registered event type IStreamEvents::outputFlushed as 43
DEBUG: accepted ipc client connection
DEBUG: start ipc handle data
DEBUG: ipc read: IHEL
DEBUG2: readf(%1i)
DEBUG2: readf: read 1 byte integer: 2 (0x2)
DEBUG: finished ipc handle data
DEBUG: ipc hello, type=node
INFO: watchdog status: ok
DEBUG: started process, session=1, command="C:/Program Files/Synergy/synergys.exe" -f --no-tray --debug DEBUG2 --name Vienradzis --ipc --stop-on-desk-switch --enable-drag-drop --enable-crypto --profile-dir "C:\Users\Anda\AppData\Local" -c "C:/Users/Anda/AppData/Local/Temp/qt_temp.if1480" --address 192.168.1.3:24800
NOTE: accepted client connection
DEBUG2: attempting sercure Connection
DEBUG2: retrying sercure Connection
DEBUG2: accepting secure socket
DEBUG2: passive ssl error, error=2, attempt=1
DEBUG2: retry accepting secure socket
DEBUG2: accepting secure socket
DEBUG2: passive ssl error, error=2, attempt=2
DEBUG2: retry accepting secure socket
DEBUG2: accepting secure socket
DEBUG2: passive ssl error, error=2, attempt=3
DEBUG2: retry accepting secure socket
DEBUG2: accepting secure socket
DEBUG2: passive ssl error, error=2, attempt=4
DEBUG2: retry accepting secure socket
DEBUG2: accepting secure socket
DEBUG2: passive ssl error, error=2, attempt=5
DEBUG2: retry accepting secure socket
DEBUG2: accepting secure socket
DEBUG2: passive ssl error, error=2, attempt=6
INFO: client connection may not be secure



And on Client:

>NOTE: starting client
NOTE: command: "C:/Program Files/Synergy/synergyc.exe" -f --no-tray --debug DEBUG2 --name Andzs-PC --ipc --stop-on-desk-switch --enable-drag-drop --profile-dir "C:\Users\Andþs\AppData\Local" 192.168.1.3:24800
NOTE: config file: C:/Users/ANDS~1/AppData/Local/Temp/qt_temp.Uh1068
NOTE: log level: DEBUG2
INFO: service command updated
DEBUG: getting elevated token, elevation required
DEBUG: processes in session 1: csrss.exe, winlogon.exe, dwm.exe, atieclxx.exe, taskhostex.exe, explorer.exe, SynTPEnh.exe, googledrivesync.exe, StikyNot.exe, chrome.exe, Dropbox.exe, avgnt.exe, chrome.exe, googledrivesync.exe, chrome.exe, chrome.exe, LiveComm.exe, CCleaner64.exe, SynTPHelper.exe, RuntimeBroker.exe, VISIO.EXE, MOM.exe, chrome.exe, CCC.exe, chrome.exe, chrome.exe, chrome.exe, dfsvc.exe, taskeng.exe, synergy.exe, 
DEBUG: found winlogon.exe in session 1
DEBUG: got token 848, duplicating
DEBUG: duplicated, new token: 852
INFO: starting new process
DEBUG: launched syntool to check active desktop
activeDesktop:Default
DEBUG: getting elevated token, elevation required
DEBUG: processes in session 1: csrss.exe, winlogon.exe, dwm.exe, atieclxx.exe, taskhostex.exe, explorer.exe, SynTPEnh.exe, googledrivesync.exe, StikyNot.exe, chrome.exe, Dropbox.exe, avgnt.exe, chrome.exe, googledrivesync.exe, chrome.exe, chrome.exe, LiveComm.exe, CCleaner64.exe, SynTPHelper.exe, RuntimeBroker.exe, VISIO.EXE, MOM.exe, chrome.exe, CCC.exe, chrome.exe, chrome.exe, chrome.exe, dfsvc.exe, taskeng.exe, synergy.exe, syntool.exe, conhost.exe, 
DEBUG: found winlogon.exe in session 1
DEBUG: got token 872, duplicating
DEBUG: duplicated, new token: 868
INFO: starting new process
INFO: drag and drop enabled
DEBUG: plugins dir: C:\Users\And�s\AppData\Local\Synergy\Plugins
DEBUG: plugins dir is empty: C:\Users\And�s\AppData\Local\Synergy\Plugins\*.dll
DEBUG1: starting client
DEBUG1: thread 0x000008b8 entry
DEBUG: screen shape: 0,0 1366x768 
DEBUG: window is 0x000c04d0
ERROR: failed to get desktop path, no drop target available, error=2
DEBUG: adopting new buffer
DEBUG: opened display
DEBUG1: registered event type IScreenEvents::error as 4
DEBUG1: registered event type IScreenEvents::suspend as 5
DEBUG1: registered event type IScreenEvents::resume as 6
DEBUG1: registered event type IScreenEvents::fileChunkSending as 7
DEBUG1: registered event type IScreenEvents::fileRecieveCompleted as 8
DEBUG1: registered event type ClientEvents::connected as 9
DEBUG1: registered event type ClientEvents::connectionFailed as 10
DEBUG1: registered event type ClientEvents::disconnected as 11
NOTE: started client
NOTE: connecting to '192.168.1.3': 192.168.1.3:24800
DEBUG1: connecting to server
DEBUG1: registered event type IDataSocketEvents::connected as 12
DEBUG1: registered event type IDataSocketEvents::connectionFailed as 13
DEBUG1: registered event type IStreamEvents::inputReady as 14
DEBUG1: registered event type IpcServerProxyEvents::messageReceived as 15
DEBUG1: registered event type IpcClientEvents::messageReceived as 16
DEBUG: event queue is ready
DEBUG: add pending events to buffer
DEBUG1: registered event type IpcClientEvents::connected as 17
DEBUG2: writef(IHEL%1i)
DEBUG2: wrote 5 bytes
DEBUG1: registered event type IStreamEvents::outputFlushed as 18
DEBUG: accepted ipc client connection
DEBUG: start ipc handle data
DEBUG: ipc read: IHEL
DEBUG2: readf(%1i)
DEBUG2: readf: read 1 byte integer: 2 (0x2)
DEBUG1: registered event type IStreamEvents::inputShutdown as 19
DEBUG1: connected;  wait for hello
DEBUG1: registered event type ISocketEvents::disconnected as 20
DEBUG1: registered event type IStreamEvents::outputError as 21
DEBUG1: registered event type IStreamEvents::outputShutdown as 22
DEBUG1: registered event type ISocketEvents::stopRetry as 23
DEBUG: finished ipc handle data
DEBUG: ipc hello, type=node
INFO: watchdog status: ok
DEBUG: started process, session=1, command="C:/Program Files/Synergy/synergyc.exe" -f --no-tray --debug DEBUG2 --name Andzs-PC --ipc --stop-on-desk-switch --enable-drag-drop --profile-dir "C:\Users\And�s\AppData\Local" 192.168.1.3:24800
DEBUG1: disconnected
NOTE: disconnected from server
DEBUG: retry in 1 seconds

**Comment by aedocw** [comment]
Latest release has resolved all issues for me (Linux server and client).  Nice work!

**Comment by ccoenen** [comment]
Dear fellow user, if you came here from google and have this output on your server:

```
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
```

Go to your settings, look for the "SSL encryption" checkbox. Uncheck it, Hit ok, Hit Apply, **then check it again**, hit ok, hit apply.

In my case, the checkbox seems to have been checked, but the client probably tried unencrypted anyway. At least that's what it looks like from the outside. [i was upgrading 1.6.x to 1.7.3]

**Comment by StevenWColby** [comment]
@ccoenen Your fix ( unchecking the 'Use SSL Encryption' checkbox ) also worked to solve a failure using 1.8.1 on Linux as a client:  ERROR: ssl error occurred (generic failure).  Since all my Synergy connections are within a corporate firewall I'm perfectly happy to disable SSL encryption.  Thanks, amigo!

**Comment by laconbass** [comment]
I was getting this spam at server log because:

- The server (linux) was running `synergys` was running with SSL enabled
- A client (linux) was running `synergyc` without SSL enabled

While trying a custom command I forgot adding the `--enable-crypto` switch

Ouch'

Maybe someone finds this useful, and maybe it could be a possible addition to the User FAQ known errors at https://github.com/symless/synergy/wiki/User-FAQ#Errors
