### ISSUE TITLE
Philisophic issue: SSL shouldn't be a high-tier item

### ISSUE THREAD

**Issue by bocajnotnef** [synergy/synergy#4654]
Currently, SSL is only available in the Pro tier and not the basic tier. This seems rather backwards to me, as encryption should always be available. While I understand that significant effort is required to maintain and support security, in a KVM security is absolutely essential--regardless of the level of support or use--because anything typed by the user will be sent across the network. This will almost certainly include usernames, passwords, contents of communications, etc. which should all be encrypted.

Thoughts?

**Comment by gregsheremeta** [comment]
+1

**Comment by VeNoMouS** [comment]
So.... lemme get this straight... you want new features... but you don't want to help support the developers adding these changes?

**Comment by nbolton** [comment]
A more appropriate place to discuss this would be the forums: http://synergy-project.org/forum/
