### ISSUE TITLE
Clipboard stops working randomly

### ISSUE THREAD

**Issue by pitastrudl** [synergy/synergy#4663]
Both machines are win7 proffesionla 64bit, one is a laptop the other a PC, clipboard randomly stops working/sharing so to solve the issue i have to restart the synergy server. the log set to verbose is here http://pitastrudl.me/synergy.log

**Comment by pitastrudl** [comment]
both programs are 1.7.2 version

**Comment by styks1987** [comment]
I have this issue too. Mac and PC

**Comment by pitastrudl** [comment]
forgot to mention it began before the release of the 1.7.2, had synergy reinstalled on both machines.

**Comment by nbolton** [comment]
Duplicates #4601
