### ISSUE TITLE
Plugin download freezes or crashes at download 'ns' plugin step

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4664]
1. Run the activation wizard
2. Login successfully
3. See that the 'ns' step freezes/crashes

Problem: The Qt library doesn't work very well with local proxy configs.
Solution: Use `syntool` to download the plugin which uses proxy settings.

**Comment by the-wes** [comment]
superceded by https://github.com/synergy/synergy/issues/4696

**Comment by joao-fidalgo** [comment]
"Solution: Use syntool to download the plugin which uses proxy settings."

Would help if you would post an example of the syntool usage.
