### ISSUE TITLE
Google Sheets Copy / Paste

### ISSUE THREAD

**Issue by claytonperkins** [synergy/synergy#4668]
Server: OSX 10.10.4
Client: Windows 7 Enterprise SP1
Wireless network

On the server, while using Google Sheets, if you select and copy multiple cells (ctrl/command + c) and then move the mouse to the client it either disconnects or the mouse jumps to the center of the main server screen. The server will shut off after one or more attempts.

The only work around is to have something other than multiple cells from Google Sheets on the clipboard.

Log for selecting just one cell on server in Google Chrome and moving cursor to client ...

INFO: screen "SERVER" grabbed clipboard 0 from "SERVER"
INFO: screen "SERVER" grabbed clipboard 1 from "SERVER"
INFO: switch from "SERVER" to "CLIENT" at 1610,1079
INFO: leaving screen
WARNING: cursor may not be visible
INFO: screen "SERVER" updated clipboard 0
INFO: screen "SERVER" updated clipboard 1
INFO: switch from "CLIENT" to "SERVER" at -1443,19
INFO: entering screen

Log for selecting just multiple cells on server in Google Chrome and moving cursor to client ...

INFO: screen "SERVER" grabbed clipboard 0 from "SERVER"
INFO: screen "SERVER" grabbed clipboard 1 from "SERVER"
INFO: switch from "SERVER" to "CLIENT" at 1403,1079
INFO: leaving screen
WARNING: cursor may not be visible
INFO: screen "SERVER" updated clipboard 0
INFO: screen "SERVER" updated clipboard 1
NOTE: client "CLIENT" has disconnected

**Comment by VeNoMouS** [comment]
Are you running ~1.7.1 with SSL enabled?

**Comment by nbolton** [comment]
Duplicates #4601
