### ISSUE TITLE
Fails to download [working] plugin

### ISSUE THREAD

**Issue by zoqaeski** [synergy/synergy#4688]
Whenever I proceed through the wizard to set up Synergy, it spends an awful long time trying to download the plugin, occasionally seeminly timing out (as noted in #4620, #4673, #4664, among others). When it does finish, I get reports that `libssl.so.10` is missing (#4621), or that the plugin cannot be found, and Synergy fails to connect.

Looking in the configuration directory reveals that a `libns.so` plugin exists, but either it hasn't downloaded correctly or has somehow become corrupted. This issue seemingly occurs on all of my machines.

**Comment by speaker** [comment]
There are really 2 issues being reported here. One is fix as a side effect of #4696 in 1.7.4, and the other is a problem with the OpenSSL library on some systems, usually seen on Mint. For the library version issue check out this post on the synergy project forums: http://synergy-project.org/forum/viewtopic.php?f=8&t=138
