### ISSUE TITLE
Log line 'activeDesktop' does not use logging system

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4690]

**Comment by nbolton** [comment]
Ah, this is parsed by lib/platform/MSWindowsWatchdog.cpp - very hacky.

**Comment by XinyuHou** [comment]
Fixed by f063b0

**Comment by nbolton** [comment]
Please test this pre-release to confirm this is ready for release.
http://synergy-project.org/nightly?filter=v1.7.4-stable-ebb7edf
