### ISSUE TITLE
Synergy Server address not found args incorrect

### ISSUE THREAD

**Issue by pauldaustin** [synergy/synergy#4693]
I'm getting the following error message every few seconds in the syslog. I'm on Yosimite.

May 20 15:52:52 x.local Synergy 1.7.3[4086]: WARNING: failed to connect to server: address not found for: -version
May 20 15:52:52 x.local Synergy 1.7.3[4083]: WARNING: failed to connect to server: address not found for: -v

I also have home-brew on that machine.

What command is it trying to run? That way I can see what version of the command is used and compare it for compatibility

**Comment by speaker** [comment]
@pauldaustin The address and port must be the very last items on the command line, when it's not (like trying the command with --version at the end) the error will be reported. If Synergy is being run from the GUI (or in a similarly automated way), there should be a log entry with the command being used prior to that error message:
`NOTE: command: /Applications/Synergy.app/Contents/MacOS/synergyc -f --no-tray --debug DEBUG --name clientname --enable-drag-drop --enable-crypto --log /Users/someuser/Desktop/synergy.log 192.168.1.200:24800`

If you would check your logs to see if that's there and if so could you add it to this report?

Any other information about the setup would also help.

**Comment by pauldaustin** [comment]
I just purchased the basic edition from the website and now don't have the problem
