### ISSUE TITLE
Automatically upload plugins as Buildbot step

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4695]
Problem: Plugins need to be manually collected and uploaded from the buildslaves, which is a very time consuming and error-prone task.

Solution: Modify the 'dist-ftp' Buildbot step to automatically upload every plugin to the production web server.

Here's the function you'll probably need to extend:
https://github.com/synergy/synergy/blob/master/ext/toolchain/commands1.py#L1347

**Comment by XinyuHou** [comment]
Hooray!! No more manual copy!
