### ISSUE TITLE
Include 'ns' plugin in installers (instead of wizard download)

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4696]
Problem: We currently use the wizard to download the 'ns' plugin (network security/SSL), which causes many bugs (proxy/firewall issues, plugin not being updated, wrong plugin downloaded, plugin not downloaded properly, etc).

Solution: Include the plugin in the installer/packages so it doesn't need to be downloaded during the wizard/activation process.

**Comment by nbolton** [comment]
@speaker What's the ETA on this one?

**Comment by speaker** [comment]
Plugins should now comw with installer and either be copied to the user space (windows) or have symbolic links  made from user space to the appropriate library locations (linux, MacOS).

**Comment by speaker** [comment]
Issue found when synergys is running and the wizard attempts to replace the plugin.

**Comment by nbolton** [comment]
Please test this pre-release to confirm this is ready for release.
http://synergy-project.org/nightly?filter=v1.7.4-stable-ebb7edf

**Comment by Zapnologica** [comment]
I'm still getting this error on win 64 1.7.5 stable

**Comment by Malcolmlowe** [comment]
@Zapnologica This is only fixed in 1.8

**Comment by Zapnologica** [comment]
@Malcolmlowe  oh I see. Thanks for filling me in.

**Comment by jieseattle** [comment]
getting this error in 1.8. this is not fixed.

**Comment by piknik** [comment]
Synergy 1.8.1-beta-b25ed99, when going through the wizard on x86_64 ubuntu linux, at least installation of the server results in the error at the end of the wizard: "Failed to copy plugin 'libns.so' to: /home/piknik/.synergy/plugins/libns.so File exists". As well, a loading indicator is activated when it should not be. The file does indeed already exist in the location.

**Comment by tcely** [comment]
Here's a good way to update the link using bash shell.

Creating a new link and moving it into place has advantages:

1. It leaves the original link alone if things go badly.
2. It doesn't try to overwrite anything
3. Moves are as close to atomic as we get with file system operations

```
unset -v _linkdst _newlink
_linkdst=~/.synergy/plugins/libns.so
_newlink="$(mktemp -q "${_linkdst}.XXXXX")"
if [ -f "$_newlink" ]; then
    ln -sf '/usr/lib/synergy/plugins/libns.so' "$_newlink" &&
        mv "$_linkdst" "${_newlink}.$$" &&
        mv "$_newlink" "$_linkdst" &&
        mv "${_newlink}.$$" "$_newlink"
fi
[ -z "$_newlink" ] || rm -rf "$_newlink"
unset -v _linkdst _newlink
```

**Comment by bird2920** [comment]
Worked correctly in Synergy v1.8.1-beta.
ns.dll downloaded to Plugins folder as expected.

**Comment by dspeers** [comment]
I installed and tested Synergy v1.8.1 for OSX 11.10, Initially SSL worked fine, but after removing the Plugins directory and reinstalling it doesn't come back.  I then re-ran the wizard and it still did not come back.  So I removed Synergy and remove the Library/Synergy directory completely.  Again re-installed and re-ran the wizard, the Plugins directory still did not come back.

**Comment by joshburgess79** [comment]
Plugin does not download when using my Pro account on Ubuntu 16.04. SSL remains greyed out.
It does download when I enter the provided key.

[2016-07-01T23:55:23] NOTE: crypto disabled because of ns plugin not available
[2016-07-01T23:55:23] NOTE: started server, waiting for clients
[2016-07-01T23:55:24] NOTE: accepted client connection
[2016-07-01T23:55:24] NOTE: client "lr" has connected

**Comment by Lochemage** [comment]
I am seeing the same results as @joshburgess79.

When installing a fresh copy of the beta link provided, it installs with the ns plugin. However, when deleting the plugin and using the setup wizard to log in with my pro account, no plugin is installed. After using the provided key, the plugin returns.

Either I don't actually have a pro account, or this isn't actually fixed (and I'm pretty sure I have payed for the pro).

**Comment by MyXelf** [comment]
Working as expected in Kubuntu 16.04 using synergy-v1.8.1-beta-f7377d6-Linux-x86_64.deb, but there is an strange issue with the generated symbolic link in the user profile:

    libns.so -> /usr/bin/../lib/synergy/plugins/libns.so

For some reason there is a redundancy in the generated link.

**Comment by herrenP** [comment]
Fix verified in:
- synergy-v1.8.1-beta-f7377d6
- Linux - elementary OS 0.3.2. Freya 64-bit
- Windows 10 Pro Insider Preview 64-bit (build: 14379.rs1_release.160627-1607)

Please note that on my Windows machine the NS plugin does is not created if user simply uninstall and reinstall. The user need to perform some manual uninstallation steps prior to recreating this. This could be true for other platforms as well although my Linux machine did not have this problem.

**Comment by herrenP** [comment]
Ops, didn't notice it was already closed. Pretty new at Github. :)

**Comment by XinyuHou** [comment]
@herrenP 
Uninstall and reinstall doesn't necessarily re-run the wizard. I know it's not intuitive. We need to improve our UX.

**Comment by frankentux** [comment]
Fix verified:
-  Version 1.8.1-beta-f7377d6
- Linux Mint 17.3 / Cinnamon 2.8.8 / Kernel 3.19.0-32
- MS Windows 10 Enterprise Ver 1511 (B 10586.420)
