### ISSUE TITLE
Timing can allow an SSL socket to be used after cleanup call

### ISSUE THREAD

**Issue by speaker** [synergy/synergy#4697]
When an SSL socket is considered to be eligible for cleanup, the destructor is called but isn't blocking. Nothing prevents a new job from being created that uses the same SSL connection.
In this case (usually caused by retries) the socket can be cleaned up and memory freed while it is in use.

**Comment by nbolton** [comment]
Closing... I guess this is fixed? Hard to reproduce I imagine.

**Comment by lacombar** [comment]
Introducing arbitrary sleep in the destructor looks awful ...

```
@@ -78,13 +81,15 @@ SecureSocket::~SecureSocket()
                SSL_CTX_free(m_ssl->m_context);
                m_ssl->m_context = NULL;
        }
-
+       ARCH->sleep(1);
        delete m_ssl;
 }
```
