### ISSUE TITLE
Having a large amount of text in the clipboard causes client to disconnect

### ISSUE THREAD

**Issue by mattsheehe** [synergy/synergy#4700]
Copying a large amount of text (~5000 characters) and then trying to move to a client causes the client to disconnect. The client reconnects immediately, but until a smaller amount of text is copied, I can't move from the server to the client.

Both computers are Windows 8.1 using Synergy 1.7.2.

**Comment by adamjames** [comment]
I did some testing on this and found that a clipboard payload of 1500 bytes or longer is sufficient to cause the issue. My test string was 1499 'a' characters. Add another 'a' and the mouse no longer moves between screens.

This also happens to be a common maximum for the [size of a single IP packet without fragmentation](http://en.wikipedia.org/wiki/Maximum_transmission_unit).

**Comment by beporter** [comment]
This is a known issue and a duplicate report. Please see #4601.

**Comment by adamjames** [comment]
Thanks :) Should I add the comment above to that issue or is having it here sufficient?

**Comment by beporter** [comment]
You can subscribe to the other thread if you want to be notified of updates. No other action is necessary though. Either way, it's safe to close this duplicate thread out (either the original poster or a project admin will need to do that.
