### ISSUE TITLE
1.7.2 server crashes on OS X when moving mouse to client screen if an image is in the clipboard

### ISSUE THREAD

**Issue by pohlcj** [synergy/synergy#4709]
Server: 1.7.2, OS X 10.10.3
Client: 1.7.2, Windows 8.1

If I have an image in the OS X clipboard, the Synergy server crashes when I move the mouse to the client screen. If I clear the clipboard or replace the image with text before moving the mouse to the client screen, the server does not crash.

**Comment by speaker** [comment]
duplicate #4712
