### ISSUE TITLE
Unity 3D does not properly handle keyboard/mouse on Mac OS with Synergy as client

### ISSUE THREAD

**Issue by hunterua** [synergy/synergy#4714]
Hi
Here is the issue description:
I have a windows pc as the synergy server and next to it I have MBP with synergy as the client.
When I work Unity 3D ( http://unity3d.com/ ) on MBP all seems to be working well, except "dragging" actions. For example to move/pan scene there is a shortcut Alt + LMB which works on windows or MBP native keyboard/touchpad, but with synergy nothing happens. There is also other issues similar to this.
Alt + RMB for zoom in/out does not work
Press and hold LMB then drag mouse over integer/float fields to change values does not work too.

Would be great if this can be fixed.

Thank you!

**Comment by hunterua** [comment]
Looks like its related to #4260 ?

**Comment by speaker** [comment]
Yep, agreed.

Duplicate: #3992
