### ISSUE TITLE
Activation dialog which also accepts a serial key

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4715]
Depends on #4716

Problem: Login based activation restricts users who are behind a proxy.

Solution: Allow user to copy/paste a key generated by a key generation tool. When key is used, run a background thread which fails silently to log that the key is used on the web server.

**Comment by pdelporte** [comment]
If you use a web service based on port 80 or 8080, most of the proxies will let the connection goes out. Just do not forget to foreseen to the possibility to configure authentification.

**Comment by nbolton** [comment]
@pdelporte Proxy issues aren't the only thing stopping people from activating (that was really just an example), generally having to activate is a huge pain in the butt for way too many users. So I don't think we should focus our discussion on proxies (yes, we know its solvable). Having offline activation is the best way to go, it gives the user much more freedom.

**Comment by pdelporte** [comment]
Offline activation is another good way to activate the product. Already looking forward to test it.

**Comment by bird2920** [comment]
Worked as expected using provided Serial key

**Comment by TheSpiritof69** [comment]
Worked as expected.

**Comment by kdoteu** [comment]
Works for me:
OS: Windows 64bit
Version: synergy-v1.8.1-beta-f7377d6

Expired Key:
![image](https://cloud.githubusercontent.com/assets/3602457/16535416/5f142daa-3fe7-11e6-8ab5-f5f2381f198e.png)
--> no ns.dll file

Valid Key: ns.dll is loaded

**Comment by mikeo-bixly** [comment]
Worked as expected.
OS: Linux (Fedora 24)
Version: v1.8.1-beta-f7377d6-Linux-x86_64

**Comment by Imaginable** [comment]
Working as expected.

OS: Windows 64bit
Version: v1.8.1-beta-f7377d6

**Comment by Verequies** [comment]
Works as expcted on Windows 10 Enterprise 64-bit, version v1.8.1-beta-f7377d6. 
If Synergy is running, unable to delete the 'Plugins' folder as ns.dll is loaded.

**Comment by pugnut** [comment]
worked as expected.
OS: windows 10
Synergy: 1.8.1-beta-f7377d6

**Comment by Zygislovas** [comment]
Works as intended.
**SERVER** system info:
Windows 10 Enterprise x64

**CLIENT** system info:
Windows 8.1 Pro x64

**Comment by yidhoe** [comment]
Works for me:
OS: Windows 64bit (Client & Server)
Version: synergy-v1.8.1-beta-f7377d6

Valid timed Key: ns.dll is loaded

**Comment by CarlatFSJ** [comment]
The serial key worked during installation.
Was able to delete the folder after stopping Synergy and was able to restart Synergy after deleting the folder.  

Noticed the following on restart of system after deleting the ns plugin folder.

[2016-07-02T09:20:43] NOTE: crypto disabled because of ns plugin not available
[2016-07-02T09:20:43] WARNING: failed to register hotkey ScrollLock (id=ef14 mask=0000)

Tested on a windows 10 64bit.

**Comment by herrenP** [comment]
Fix verified in:
- synergy-v1.8.1-beta-f7377d6
- Linux - elementary OS 0.3.2. Freya 64-bit
- Windows 10 Pro Insider Preview 64-bit (build: 14379.rs1_release.160627-1607)

Please note that on my Windows machine the NS plugin does is not created if user simply uninstall and reinstall. The user need to perform some manual uninstallation steps prior to recreating this. This could be true for other platforms as well although my Linux machine did not have this problem.

**Comment by herrenP** [comment]
Ops, didn't notice it was already closed. Pretty new at Github. :)
