### ISSUE TITLE
SSL 'alert bad record mac' error causes disconnect

### ISSUE THREAD

**Issue by BlackDex** [synergy/synergy#4717]
I Just compiled the latest git version and get the following error while using the it for a while.

NOTE: accepted client connection
ERROR: ssl error occurred (generic failure)
ERROR: error:140943FC:SSL routines:SSL3_READ_BYTES:sslv3 alert bad record mac
NOTE: accepted client connection
ERROR: ssl error occurred (system call failure)
ERROR: eof violates ssl protocol
ERROR: failed to accept secure socket
NOTE: stopping synergy desktop process

**Comment by XinyuHou** [comment]
@BlackDex 
What platform are you on? 

Did you mean Synergy was functional for a while and suddenly the connection was dropped?

**Comment by BlackDex** [comment]
@XinyuHou
Yes, i was working , and suddenly the mouse was back at the server. This error was in the log.

I'm using Ubuntu 15.04 64bit. With a manually compiled libns.so.

**Comment by speaker** [comment]
@BlackDex 
What version are the OpenSSL installs on the server and client?
Are both ends 15.04, 64 bit? If not, what's the other end (and is it the client?)
If you're still seeing the issue, have you been able to capture it in a log? (DEBUG2 perhaps? ;)

I'm looking into this issue, but most of the sources I can find imply an SSL library problem or a problem with how SSL is being used. The first we can't control, but the second we can. If this was a common problem, or happened often I would be much more concerned with the 2nd being the case. I haven't been able to reproduce it either which makes it harder to figure out what's going on.

**Comment by speaker** [comment]
@BlackDex 
Also, what's the hash of the code you're working from?

**Comment by BlackDex** [comment]
@speaker 
I Have compiled the latests version now on both systems and created a deb package. Purged the previous install and installed the fresh created deb package. Both are compiled on the system they are running on. What i saw is that the sha256sums of all the binaries are different, except for `synergy`, also the libns.so sha256sum is different on both systems.

With the latest version (`git log` - 82f822b51a6b078cf76f9c7c2c4e591a030138ec) it seems to work without interruptions, but with some errors in the logs about ssl.

I do not see the other errors above anymore, although i did exactly the same now as i did with the previous version, and both systems are Ubuntu 15.04 with the exact same (dev) libraries (as far as i can tell).

Here are the logs if you want to see them.
Server: https://gist.github.com/BlackDex/c4c6e84213ee39c241da
Client: https://gist.github.com/BlackDex/74bd83664116865ce8b7

**Comment by BlackDex** [comment]
After i just stoped and started it again, i got the following error (Unfortunally without DEBUG2).

ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to connect secure socket
NOTE: stopping synergy desktop process

**Comment by BlackDex** [comment]
Ok, some more info here. Don't know why it happens now, but it does.

DEBUG2: onMouseMoveSecondary -1,+6
DEBUG2: move on BlackDex to 719,100
DEBUG2: send mouse move to "BlackDex" 719,100
DEBUG2: writef(DMMV%2i%2i)
DEBUG2: wrote 8 bytes
DEBUG2: writing secure socket:0xabe530
DEBUG2: reading secure socket
DEBUG2: reading secure socket
DEBUG2: passive ssl error, error=2, attempt=1
DEBUG2: msg from "BlackDex": CNOP
DEBUG2: no-op from
DEBUG2: event: MotionNotify 958,555
DEBUG2: event: MotionNotify 958,555
DEBUG2: onMouseMoveSecondary +0,+4
DEBUG2: move on BlackDex to 719,104
DEBUG2: send mouse move to "BlackDex" 719,104
DEBUG2: writef(DMMV%2i%2i)
DEBUG2: wrote 8 bytes
DEBUG2: writing secure socket:0xabe530
DEBUG2: reading secure socket
DEBUG2: reading secure socket
DEBUG2: passive ssl error, error=2, attempt=1
DEBUG2: msg from "BlackDex": CNOP
DEBUG2: no-op from
DEBUG2: event: MotionNotify 957,560
DEBUG2: event: MotionNotify 957,560
DEBUG2: onMouseMoveSecondary -1,+5
DEBUG2: move on BlackDex to 718,109
DEBUG2: send mouse move to "BlackDex" 718,109
DEBUG2: writef(DMMV%2i%2i)
DEBUG2: wrote 8 bytes
DEBUG2: writing secure socket:0xabe530
DEBUG2: reading secure socket
DEBUG2: reading secure socket
DEBUG2: passive ssl error, error=2, attempt=1
DEBUG2: msg from "BlackDex": CNOP
DEBUG2: no-op from
DEBUG2: event: MotionNotify 957,566
DEBUG2: event: MotionNotify 957,566
DEBUG2: onMouseMoveSecondary +0,+6
DEBUG2: move on BlackDex to 718,115
DEBUG2: send mouse move to "BlackDex" 718,115
DEBUG2: writef(DMMV%2i%2i)
DEBUG2: wrote 8 bytes
DEBUG2: writing secure socket:0xabe530
DEBUG2: reading secure socket
DEBUG2: reading secure socket
DEBUG2: passive ssl error, error=2, attempt=1
DEBUG2: msg from "BlackDex": CNOP
DEBUG2: no-op from
DEBUG2: event: MotionNotify 956,571
DEBUG2: event: MotionNotify 956,571
DEBUG2: onMouseMoveSecondary -1,+5
DEBUG2: move on BlackDex to 717,120
DEBUG2: send mouse move to "BlackDex" 717,120
DEBUG2: writef(DMMV%2i%2i)
DEBUG2: wrote 8 bytes
DEBUG2: writing secure socket:0xabe530
DEBUG2: reading secure socket
DEBUG2: reading secure socket
DEBUG2: passive ssl error, error=2, attempt=1
DEBUG2: msg from "BlackDex": CNOP
DEBUG2: no-op from
DEBUG2: event: MotionNotify 956,583
DEBUG2: warped to 960,540
DEBUG2: event: MotionNotify 956,583
DEBUG2: warped to 960,540
DEBUG2: event: MotionNotify 960,540
DEBUG2: onMouseMoveSecondary +0,+12
DEBUG2: move on BlackDex to 717,132
DEBUG2: send mouse move to "BlackDex" 717,132
DEBUG2: writef(DMMV%2i%2i)
DEBUG2: wrote 8 bytes
DEBUG2: event: MotionNotify 960,540
DEBUG2: writing secure socket:0xabe530
DEBUG2: reading secure socket
DEBUG2: reading secure socket
DEBUG2: passive ssl error, error=2, attempt=1
DEBUG2: msg from "BlackDex": CNOP
DEBUG2: no-op from
DEBUG2: event: MotionNotify 959,544
DEBUG2: event: MotionNotify 959,544
DEBUG2: onMouseMoveSecondary -1,+4
DEBUG2: move on BlackDex to 716,136
DEBUG2: send mouse move to "BlackDex" 716,136
DEBUG2: writef(DMMV%2i%2i)
DEBUG2: wrote 8 bytes
DEBUG2: writing secure socket:0xabe530
DEBUG2: reading secure socket
DEBUG2: reading secure socket
DEBUG2: passive ssl error, error=2, attempt=1
DEBUG2: msg from "BlackDex": CNOP
DEBUG2: no-op from
DEBUG2: event: MotionNotify 958,550
DEBUG2: event: MotionNotify 958,550
DEBUG2: onMouseMoveSecondary -1,+6
DEBUG2: move on BlackDex to 715,142
DEBUG2: send mouse move to "BlackDex" 715,142
DEBUG2: writef(DMMV%2i%2i)
DEBUG2: wrote 8 bytes
DEBUG2: writing secure socket:0xabe530
DEBUG2: reading secure socket
DEBUG2: reading secure socket
DEBUG2: passive ssl error, error=2, attempt=1
DEBUG2: msg from "BlackDex": CNOP
DEBUG2: no-op from
DEBUG2: event: MotionNotify 958,556
DEBUG2: event: MotionNotify 958,556
DEBUG2: onMouseMoveSecondary +0,+6
DEBUG2: move on BlackDex to 715,148
DEBUG2: send mouse move to "BlackDex" 715,148
DEBUG2: writef(DMMV%2i%2i)
DEBUG2: wrote 8 bytes
DEBUG2: writing secure socket:0xabe530
DEBUG2: reading secure socket
DEBUG2: reading secure socket
DEBUG2: passive ssl error, error=2, attempt=1
DEBUG2: msg from "BlackDex": CNOP
DEBUG2: no-op from
DEBUG2: event: MotionNotify 958,562
DEBUG2: event: MotionNotify 958,562
DEBUG2: onMouseMoveSecondary +0,+6
DEBUG2: move on BlackDex to 715,154
DEBUG2: send mouse move to "BlackDex" 715,154
DEBUG2: writef(DMMV%2i%2i)
DEBUG2: wrote 8 bytes
DEBUG2: writing secure socket:0xabe530
DEBUG2: reading secure socket
DEBUG2: reading secure socket
DEBUG2: passive ssl error, error=2, attempt=1
DEBUG2: msg from "BlackDex": CNOP
DEBUG2: no-op from
DEBUG1: sending clipboard chunk
DEBUG2: sending clipboard chunk data: size=2048
DEBUG2: writef(DCLP%1i%4i%1i%s)
DEBUG2: wrote 2062 bytes
DEBUG2: writing secure socket:0xabe530
DEBUG2: reading secure socket
DEBUG: ssl connection closed
DEBUG1: registered event type stopRetry as 46
DEBUG1: registered event type disconnected as 47
NOTE: client "BlackDex" has disconnected
INFO: jump from "BlackDex" to "thijs-ubuntu" at 960,540
DEBUG2: mapping state: 16
DEBUG2: |= modifier: 4
DEBUG2: warped to 960,540
INFO: entering screen

**Comment by BlackDex** [comment]
Oke, after some more debugging, it only happens when i have a large amount of data in my past buffer. Without it, everythings to go just fine. With a large paste buffer, the servers stops when i enter the client.

This happens on both clients (Laptop with 15.04 and Raspberry PI with Raspbian).

**Comment by speaker** [comment]
@BlackDex There is an issue #4712 that is related to large clipboard that might address that part of the issue. There were a number of fixes put in over the last few weeks to address SSL stability in general and given some were timing fixes it's possible they've fixed the other problems that have now gone away. 

Does it seem reasonable to close this one out as fixed by other changes and track the buffer size via #4712? (This fix is in jerry-sandbox if you want to try it out.)

**Comment by speaker** [comment]
This issue appears fixed by other changes, if it persists, we'll reopen it and hopefully new logging will help identify the issue better. #4793

**Comment by nbolton** [comment]
Duplicates #4696
