### ISSUE TITLE
Plugin download shows 'Could not get Linux package type' error

### ISSUE THREAD

**Issue by maximd** [synergy/synergy#4720]
Hi,

I am using the new SSL feature since version 1.7.2 and everything worked fine since then.

Today, I decided to upgrade to 1.7.3 and, after the initial wizard, I got the following error when trying to download the ns plugin:

```
Error: Could not get Linux package type.
```

I am using Centos 6.5. If you need any other information, please don't hesitate.

**Comment by maximd** [comment]
Side note: if I downgrade to 1.7.2, the ns plugin is correclty downloaded by the wizard.

**Comment by nbolton** [comment]
Damn, my bad, this is a stupid bug. This should just set isDeb to `false` instead of emit error...
https://github.com/synergy/synergy/blob/3563217c7b349cd59d3d02fedee1234c5492c82e/src/gui/src/PluginManager.cpp

**Comment by maximd** [comment]
You owned it :)

**Comment by nbolton** [comment]
Maybe this is more elegant...

`bool isDeb = (success && process.waitForFinished() & (process.exitCode() == 0));`

**Comment by nbolton** [comment]
@maximd Fancy getting your hands dirty? I'm traveling right now... @speaker and @XinyuHou have their hands full.

**Comment by maximd** [comment]
@nbolton it works. I will open a pull request in a few minutes which includes your elegant solution, tested succesfully on my centos 6.5 (after build and package).

**Comment by jlp78** [comment]
FYI, a workaround I posted on the forum is to create a symlink called "dpkg" to /bin/false somewhere in your PATH.

**Comment by abeeson** [comment]
FYI this is also an issue with Fedora....

**Comment by quiffman** [comment]
Ditto that.
@jlp78's temporary workaround did the job for me.

**Comment by CyberKiller40** [comment]
This affects also OpenSUSE.

**Comment by mrsno** [comment]
Thanks workaround helped me too on Fedora server / Debian client.

**Comment by mrichmon** [comment]
Thanks, the work-around allowed me to bypass this issue on CentOS 7.1.

**Comment by XinyuHou** [comment]
Fixed by 03fc9b5fa72fd3197ca1e496f2c22e640304a602

**Comment by nbolton** [comment]
@XinyuHou I guess #4696 makes this issue redundant?

**Comment by XinyuHou** [comment]
@nbolton Agree

**Comment by nbolton** [comment]
Fixed by #4696

**Comment by nbolton** [comment]
Please test this pre-release to confirm this is ready for release.
http://synergy-project.org/nightly?filter=v1.7.4-stable-ebb7edf

**Comment by jlp78** [comment]
Well, it sort of worked.  I had to remove my .synergy directory, then run the wizard (just running the synergy command wasn't enough and it complained that the ns plugin couldn't be loaded so crypto was disabled).  Running the wizard also had me specify the host my client was connecting to, which refreshed the SSL key so I didn't have to do it manually.  I was then able to stop the client and restart synergyc with my desired options and it came up and connected.

**Comment by nbolton** [comment]
Looks like @XinyuHou accidentally committed https://github.com/synergy/synergy/commit/03fc9b5fa72fd3197ca1e496f2c22e640304a602 to master instead of 1.7.4 branch.
