### ISSUE TITLE
Waiting for active desktop result freezes Windows service

### ISSUE THREAD

**Issue by XinyuHou** [synergy/synergy#4723]
1. Server calls syntool
2. Wait for the current active desktop result
3. If for some reason, syntool doesn't return this result, service waits forever

**Comment by XinyuHou** [comment]
Fixed by aec52c3

**Comment by nbolton** [comment]
Please test this pre-release to confirm this is ready for release.
http://synergy-project.org/nightly?filter=v1.7.4-stable-ebb7edf
