### ISSUE TITLE
REQ: Plugin Download Progress bar / Status window..

### ISSUE THREAD

**Issue by VeNoMouS** [synergy/synergy#4725]
When theres a problem... you dont know whats happening as it just sits there...

![2015-05-28 11_41_04-settings - search results](https://cloud.githubusercontent.com/assets/597545/7849890/c14956ac-052e-11e5-85a1-b0c2c28d3892.png)

**Comment by speaker** [comment]
#4696 deprecates this issue since the plugin is no longer downloaded.
