### ISSUE TITLE
Security BUG: Activation credentials sent in GET request rather than POST variables...

### ISSUE THREAD

**Issue by VeNoMouS** [synergy/synergy#4727]
![selection_343](https://cloud.githubusercontent.com/assets/597545/7850312/6c5a04c4-0534-11e5-802a-612084d205ad.png)

**Comment by VeNoMouS** [comment]
Also... MD5 hashing the password... really? so last decade... :P

**Comment by VeNoMouS** [comment]
@nbolton told me on facebook they are moving away from this method..

**Comment by speaker** [comment]
That's a fair point and good suggestion. 

Plugin processing has been moved to an install process, and if we go back to downloads in the future we'll use a more RESTful friendly process.
