### ISSUE TITLE
Key mapping issue for Japanese keyboard

### ISSUE THREAD

**Issue by juanpaulo** [synergy/synergy#4730]
Server: Windows 7 (Japanese keyboard)
Client: Mac OS X (English keyboard)

Apologies if this is already a known issue but I noticed some unexpected behaviour with the above setup.
There seems to be an issue with with some of the key mappings, the following keys are not mapped as expected:

`Shift + 7` : `"` instead of `'`
`Shift + -` : `+` instead of `=`
`6` instead of `^`
`2` instead of `@`
`Shift @`: `2` instead of `backtick`
`;` instead of `:`

Everything else seems to be fine. I'll try to look into it myself but if anyone has any workaround, please share. Thanks!

**Comment by XinyuHou** [comment]
Duplicated to #4280
