### ISSUE TITLE
ERROR: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

### ISSUE THREAD

**Issue by mrsno** [synergy/synergy#4731]
Re-creating this as new issue as it wasn't giving same warning as other ssl post.

Issue here with Debian sid as client and Fedora 20 as server. Fedora seems ok enabling SSL but Debian gives:

ERROR: ssl error occurred (generic failure)
ERROR: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
ERROR: failed to connect secure socket

This is after stopping the server and re-running the Wizard. Both client / server appear to have libns.so downloaded and a SSL folder in .synergy/

Turning off SSL on both makes it work (without SSL).

**Comment by mrsno** [comment]
Never mind this was the failed to download plugin issue #4720 and workaround fixed it for me.

**Comment by Sorunome** [comment]
Using archlinux I had to
cd /usr/lib
sudo ln -s libssl.so libssl.so.10
sudo ln -s libcrypto.so libcrypto.so.10
