### ISSUE TITLE
On client instead of '@' I get 'Ω'

### ISSUE THREAD

**Issue by marsbard** [synergy/synergy#4733]
All the other shifted numerals appear to give the correct keys. Both machines are fedora 20, laptop (client) is UK keyboard layout, desktop (server) is US layout. Pretty annoying since I keep my email client open in the laptop

**Comment by marsbard** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/197057/7860780/491dbe16-054c-11e5-88db-662a9fe28017.png)

**Comment by dsemi** [comment]
See https://github.com/synergy/synergy/issues/62

**Comment by speaker** [comment]
Duplicate of #62
