### ISSUE TITLE
Connection drops on copy/paste

### ISSUE THREAD

**Issue by kurtzilla** [synergy/synergy#4734]
Using Win 8.1 as server, Mac osx 10.10.3 as client.
Moving back and forth from screen to screen, I am continually being disconnected. It seems to be triggered by copy and paste operations on the client. ie as soon as I paste on the desktop, I am disconnected.

**Comment by MarttiR** [comment]
Confirmed using Linux server, OSX clients. Server closes SSL connections after copying something to the clipboard on a client and moving mouse to server screen.

Server log:
```
DEBUG1: received property GDK_SELECTION (327) delete from 0x082200003
DEBUG1: clipboard: finished reply to 0x02200003,364,327
DEBUG1: onKeyUp id=99 mask=0x2010 button=0x0036
DEBUG1: send key up to "client1.local" id=99, mask=0x2010, button=0x0036
DEBUG1: ignoring X error: 3
DEBUG1: ignoring X error: 3
DEBUG1: ignoring X error: 3
DEBUG1: ignoring X error: 3
DEBUG1: onKeyUp id=61419 mask=0x2010 button=0x0085
DEBUG1: send key up to "client1.local" id=61419, mask=0x2010, button=0x0085
DEBUG1: ignoring X error: 3
DEBUG1: ignoring X error: 3
DEBUG1: ignoring X error: 3
DEBUG1: ignoring X error: 3
DEBUG1: ignoring X error: 3
DEBUG1: ignoring X error: 3
DEBUG1: ignoring X error: 3
DEBUG1: ignoring X error: 3
DEBUG1: try to leave "client1" on left
INFO: switch from "client1" to "server" at 2126,959
DEBUG1: send leave to "client1.local"
INFO: entering screen
DEBUG1: thread 0x0000001a entry
DEBUG: start receiving clipboard data 
DEBUG: ssl connection closed
DEBUG: ssl connection closed
```

Both clients log is identical:
```
NOTE: server is dead
WARNING: failed to connect to server: server is not responding
NOTE: connecting to 'server': x.x.x.x:24800
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to connect secure socket
NOTE: disconnected from server
```

**Comment by XinyuHou** [comment]
@kurtzilla Are you using SSL?

**Comment by XinyuHou** [comment]
@MarttiR Please look at 4712.

**Comment by kurtzilla** [comment]
Yes:
![synergy1](https://cloud.githubusercontent.com/assets/579932/7887544/26c224d0-05ef-11e5-8290-905168a20b50.png)

**Comment by MarttiR** [comment]
@XinyuHou I did, this happens even when copying URLs and stuff, under 50 characters.

Could clipboard corruption be an issue? I've been sometimes seeing those errors with clipboard lengths in the thousands, while expected clipboard size (the next error) was under 50 and what the server received was around 100. It's hard to reproduce exactly, which kind of points to the actual clipboard content, i.e. possible charset issues.

**Comment by XinyuHou** [comment]
@MarttiR 
Please update your comment in #4712 since this issue has been closed due to duplication.

**Comment by BubDZombie** [comment]
I'm experiencing something like this, but I don't think it's a dup of 4712, since I'm copying small strings. Since both issues are closed, is there an appropriate place to attach my logs? I tried XinyuHou's nightly from 4712 and seem to have the same behavior. I'm on Mint 17, client and server. Enabling/disabling SSL seems to make no difference.

**Comment by XinyuHou** [comment]
@BubDZombie 
If this is a general clipboard issue, please use issue search function to see if there is any ticket that is similar to your case. If not, please create your own ticket, and copy the log and setup info.
