### ISSUE TITLE
"ssl error occurred" after server is stopped if SSL is enabled (OSX to OSX)

### ISSUE THREAD

**Issue by adrianosmond** [synergy/synergy#4738]
Both my client and server are running OSX 10.10.3. Steps to reproduce (100% reliably in my environment):

- Make sure SSL is enabled in preferences
- Open the GUI on the server
- Click the "Stop" button

At this point the log window on my client machine looks like this:

```
ERROR: ssl error occurred (system call failure)
ERROR: eof v
iolates ssl protocol
NOTE: disconnected from server
```
Repeating these steps with SSL disabled causes results in no issues. (Being able to restart is important to me as I'm another long standing sufferer of #451 :smile:)

**Comment by speaker** [comment]
@adrianosmond , The functionality around this is changed for 1.7.4. The newest master nightly builds have the fix in them: http://synergy-project.org/nightly?filter=master
