### ISSUE TITLE
v1.7.3 ERROR: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number

### ISSUE THREAD

**Issue by TinLe** [synergy/synergy#4748]
Just upgraded both client and server to v1.7.3.
Server: Linux RHEL 6.4
Client: OSX 10.10.4

Run Setup Wizard on both.  Every time I click start on OSX client side, I get following errors.

NOTE: started client
NOTE: connecting to 'tinle-desktop': 172.23.87.48:24800
NOTE: server fingerprint: E2:83:F6:3F:6B:37:DD:0C:C7:B5:C9:3B:DC:19:A7:44:F9:8E:6E:D7
INFO: connected to secure socket
INFO: server ssl certificate info: /CN=Synergy
2015-06-02 07:27:42.801 synergyc[68724:5453388] starting cocoa loop
ERROR: ssl error occurred (generic failure)
ERROR: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
NOTE: disconnected from server

**Comment by TinLe** [comment]
This is the errors on the server side.

NOTE: starting server
NOTE: config file: /tmp/qt_temp.T12252
NOTE: log level: NOTE
NOTE: started server, waiting for clients
NOTE: accepted client connection
NOTE: client "tinle-mn1" has connected
NOTE: client "tinle-mn1" has disconnected
NOTE: accepted client connection
NOTE: client "tinle-mn1" has connected
NOTE: client "tinle-mn1" is dead
NOTE: accepted client connection
NOTE: client "tinle-mn1" has connected
ERROR: secure socket error: SSL_ERROR_SYSCALL
ERROR: an EOF violates the protocol
NOTE: client "tinle-mn1" has disconnected
NOTE: accepted client connection
NOTE: client "tinle-mn1" has connected
NOTE: client "tinle-mn1" has disconnected
NOTE: accepted client connection
NOTE: client "tinle-mn1" has connected
NOTE: client "tinle-mn1" has disconnected
NOTE: accepted client connection
NOTE: client "tinle-mn1" has connected
NOTE: client "tinle-mn1" has disconnected
NOTE: accepted client connection
NOTE: client "tinle-mn1" has connected
NOTE: stopping synergy desktop process
NOTE: starting server
NOTE: config file: /tmp/qt_temp.X12252
NOTE: log level: NOTE
NOTE: started server, waiting for clients
NOTE: accepted client connection
NOTE: client "tinle-mn1" has connected
NOTE: client "tinle-mn1" has disconnected
NOTE: accepted client connection
NOTE: client "tinle-mn1" has connected
NOTE: client "tinle-mn1" has disconnected
NOTE: accepted client connection
NOTE: client "tinle-mn1" has connected
NOTE: client "tinle-mn1" has disconnected
NOTE: accepted client connection
NOTE: client "tinle-mn1" has connected
NOTE: client "tinle-mn1" has disconnected
NOTE: accepted client connection
NOTE: client "tinle-mn1" has connected
NOTE: client "tinle-mn1" has disconnected
NOTE: accepted client connection
NOTE: client "tinle-mn1" has connected
NOTE: client "tinle-mn1" has disconnected
NOTE: accepted client connection
NOTE: client "tinle-mn1" has connected
NOTE: client "tinle-mn1" has disconnected
NOTE: stopping synergy desktop process
NOTE: starting server
NOTE: config file: /tmp/qt_temp.L12252
NOTE: log level: NOTE
NOTE: started server, waiting for clients
NOTE: accepted client connection
NOTE: accepted client connection
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version
NOTE: new client disconnected
NOTE: accepted client connection
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version
NOTE: new client disconnected
NOTE: stopping synergy desktop process
NOTE: starting server
NOTE: config file: /tmp/qt_temp.n12252
NOTE: log level: NOTE
NOTE: started server, waiting for clients
NOTE: accepted client connection
NOTE: new client disconnected
NOTE: accepted client connection
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version
NOTE: new client disconnected
NOTE: stopping synergy desktop process
NOTE: starting server
NOTE: config file: /tmp/qt_temp.k12252
NOTE: log level: NOTE
NOTE: started server, waiting for clients
NOTE: stopping synergy desktop process
NOTE: starting server
NOTE: config file: /tmp/qt_temp.U12252
NOTE: log level: NOTE
NOTE: started server, waiting for clients
NOTE: accepted client connection
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:2006F079:BIO routines:BIO_read:unsupported method
ERROR: failed to accept secure socket
NOTE: accepted client connection
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version
NOTE: new client disconnected
NOTE: accepted client connection
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version
NOTE: new client disconnected

**Comment by TinLe** [comment]
Reverting both back to v1.7.2 allow me to work again.   Note that mixing them, e.g. v.1.7.2 client w/v.17.3 server or vice versa does not work.

**Comment by spacepluk** [comment]
Hi there, I'm having the same problem with these:

```
Server: Arch Linux
Client: Mac OSX 10.10.3
```

I tried reverting to v1.7.2 but it didn't work for me :(

**Comment by speaker** [comment]
@TinLe, @spacepluk , would you be willing to try this with the newest master nightly builds? http://synergy-project.org/nightly?filter=master

There is additional debugging output that should prove useful if the issue persists. Note that if you regress back to 1.7.2 after, you'll want to make sure the plugin entries get removed as well both in user space and in /usr/lib/synergy

**Comment by TinLe** [comment]
@speaker 

Sure.  I grabbed whatever was at the top of the link and installed them on both systems.   The About show they are 1.7.4.   I am using them now.  At least this version seem to be working for both client/server.   No more SSL errors.

**Comment by speaker** [comment]
@TinLe Yay! Thank you, I appreciate your willingness to try them out.
