### ISSUE TITLE
Mouse Navigation Button Functionality

### ISSUE THREAD

**Issue by aquishix** [synergy/synergy#4752]
Users should be able to run a Synergy server on a Linux OS box and use the navigation (i.e., forward and back buttons -- typically mapped to the 4th and 5th mouse buttons) buttons on a Windows client.

Currently, they cannot.

**Comment by cmellwig** [comment]
Works for me by mapping it in the config file
```
mousebutton(4) = keystroke(WWWBack)
mousebutton(5) = keystroke(WWWForward)

**Comment by aquishix** [comment]
cmellwig,

Thank you for your reply.

Which config file is that?  I can't seem to find one on my Xubuntu box (running the Synergy server) or my Windows 7 box (running the Synergy client).

Thanks again,

-aquishix

**Comment by cmellwig** [comment]
You can create a config file on the server using your existing configuration via CTRL+ALT+S. Check "Use existing configuration" with the path of the created config file and put in the two lines right before the "end" tag. 
In theory you could configure this behaviour in interactive mode, but I've never managed to remap mouse button 5.

**Comment by aquishix** [comment]
cmellwig,

I tried what you just described, to no effect.  I even killed the daemon and client, restarted everything, and ensured that the config file was being read.

Ideas?

Thanks,

-aquishix

**Comment by cmellwig** [comment]
You could try  
```
mousebutton(6) = keystroke(WWWBack)
mousebutton(7) = keystroke(WWWForward)

or mapping it to another button:
```
mousebutton(4) = mousebutton(6)
mousebutton(5) = mousebutton(7)

Depending what button should trigger back/forward.

**Comment by aquishix** [comment]
cmellwig,

Well, when I tried going into the interactive configuration window, it exhibited the same behavior as you alluded to -- mouse buttons 4 and 5 both get interpreted as 4.  However, given that, I assumed that meant that 4 and 5 were the correct numbers...  both of these work fine for me:

mousebutton(6) = keystroke(Alt+Left,CLIENTHOSTNAME)
mousebutton(7) = keystroke(Alt+Right,CLIENTHOSTNAME)

mousebutton(6) = keystroke(WWWBack,CLIENTHOSTNAME)
mousebutton(7) = keystroke(WWWForward,CLIENTHOSTNAME)

But trying to use mousebutton(4) and mousebutton(5) doesn't work... This is utterly mysterious to me.  I'm tempted to call it a bug.

Thank you VERY much for your help!  

-aquishix
