### ISSUE TITLE
1.7.3 synergyd High CPU utilization on Windows 7

### ISSUE THREAD

**Issue by zdndanny** [synergy/synergy#4754]
Windows task manager showing process "synergyd.exe" run as System service constantly take 25% CPU, while system is idle, total CPU usage is 26%.

Stopping the service "Synergy" will bring CPU usage down by 25%. Of couse that will disable synergy connections.  

Server running synergy 1.7.3 for Linux 64 bit
Client running synergy 1.7.3 on Windows 7, both machines are in same LAN.
SSL disabled on both server and client,  because errors related to another issue.

**Comment by zdndanny** [comment]
This issue is only observed when the Synergy Pro application is not started after the system startup.
If the Synergy GUI is started the CPU untilization by synergyd.exe drop to near 0.  The total CPU utilization also drop.  If I exit from the GUI, the service CPU utilization will go up. 
Question:  
Is synergyd.exe service a required part of current version of Synergy? 
I can use the keyboard and mouse on the server to control the Windows clients, as long as the service is running. What is needed in the GUI by the services?

**Comment by alexandre-p** [comment]
I have the same issue.
Synergyd uses 25% of the overall CPU. 
My computer has a "4 cores CPU" (actually 2 cores, 4 with hyper threading), which means that synergyd uses an entire virtual core to run.

I notice the same thing you do when I launch Synergy GUI : the CPU usage drops down to zero.

Details :
Server Ubuntu 14.04 64 bits with Synergy 1.7.3
Client Windows 7 Ent 64 with Synergy 1.7.3.
The machines are on the same LAN with SSL activated.

**Comment by Loswave** [comment]
Same Problem as above. Also useing about 25%. I have a quad core i7. Meaning that it's using an entire core with it's HT node. Server is Win8.1 and client is Win 8.1. Both exhibit the issue. SSL is enabled.

Same as the above, if I leave the GUI open even in a minimized state the cpu usage drops to almost nothing for all synergy processes.

**Comment by XinyuHou** [comment]
@Loswave @alexandre-p @zdndanny 
Please check #4721. This is duplicated.
