### ISSUE TITLE
SSL error (140C5042) after updating to 1.7.3

### ISSUE THREAD

**Issue by movoho** [synergy/synergy#4757]
After having updated my client and server installations, I get the following errors:

Server (Win 7 64-bit):
NOTE: connecting to service...
NOTE: connection established
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to connect secure socket
INFO: server connection may not be secure
ERROR: secure socket error: SSL_ERROR_SSL

The client has the same failures in log.

**Comment by XinyuHou** [comment]
Please try rerun the wizard to get the latest plugins.

**Comment by movoho** [comment]
Still not working. For the OS X version there is not such option, on the Windows server I have updated plugins wihtout any luck.
Please fix this ASAP - I would have expected a little more caretaking when releasing updates.

**Comment by movoho** [comment]
This is the log from the OS X client:

NOTE: starting client
NOTE: config file: /var/folders/7p/r5tn4s795kl6vw33_04xwn3m0000gn/T/Synergy.xJL697
NOTE: log level: INFO
INFO: drag and drop enabled
NOTE: started client
NOTE: connecting to '128.176.159.129': 128.176.159.129:222
2015-06-05 10:02:50.388 synergyc[708:10859] starting cocoa loop
ERROR: secure socket error: SSL
_ERROR_SSL
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to accept secure socket
INFO: client connection may not be secure
INFO: accepted secure socket
NOTE: disconnected from server

**Comment by python138** [comment]
Actually OSX does have the option. 

With the Synergy application shown, and with focus - 
   - File
   - Run Wizard. 

That will redownload the plugins.

**Comment by 0bl1t3r4t3** [comment]
I'm having the same problem on Fedora.  The wizard fails to get any plugins with the error "Error: Could not get Linux package type".

**Comment by python138** [comment]
See - https://github.com/synergy/synergy/issues/4758

ln -s /usr/bin/false /usr/bin/dpkg

**Comment by XinyuHou** [comment]
duplicated to #4719
