### ISSUE TITLE
Fedora 21: Error: Could not get Linux Package Type. 

### ISSUE THREAD

**Issue by qops1981** [synergy/synergy#4758]
I ran the rpm on my Fedora 21 system to install. During the wizard running I got the error in the title: Error: Could not get Linux Package Type.

**Comment by pithium** [comment]
Synergy looks for /usr/bin/dpkg. If not found unfortunate things happen. 
I created a symlink:

```
ln -s /usr/bin/false /usr/bin/dpkg
```

Slackware is not deb or rpm based, and this gets SSLworking.

**Comment by ccgurley** [comment]
Hi, I'm currently running synergy 1.7.3 on a RHEL 6/7.1 machines, and I'm getting the Could not get Linux Package Type error on the RHEL6 box. The dpkg link seems to work on RHEL7.1 but not RHEL6, any suggestions?

**Comment by XinyuHou** [comment]
Duplicated to #4720
