### ISSUE TITLE
High CPU usage on client

### ISSUE THREAD

**Issue by willianma** [synergy/synergy#4759]
sometimes, oftenly synergyd.exe gets high cpu usage (around 25% on two cores)'
this seems to have started when I updated to the latest version..

the mouse starts delaying the moves.. becoming very difficult to use it..
when it doesn't happens the process uses only 0-2% of processor and mouse moves quite smoothly..

Nick, feel free to connect to my computer to do as many tests as you might need..
I have teamviewer and I'll pass you the connection details by email

Also have another issue when transferring data through the network. Synergy seems to use the same channel without QoS so mouse also delays, but this is another issue that has nothing to do with the issue reported above..

**Comment by XinyuHou** [comment]
Please check #4721. Duplicated.
