### ISSUE TITLE
1.7.3 - synergyd.exe takes 100% usage on one cpu core

### ISSUE THREAD

**Issue by inSeek** [synergy/synergy#4765]
on my pc with win7 x64 sp1, I found that synergyd.exe takes 100% usage on one cpu core all the time

**Comment by Rooks103** [comment]
Seeing the same thing.  Have a Linux Mint 13 server setup with a Win7 x64 SP1 client.  Synergyd.exe basically sits at 12-13% on the Windows box (i.e. 1 of the 8 cores).  CPU is i7-2600 @ 3.4Ghz.

**Comment by XinyuHou** [comment]
Please check #4721. There is a nightly ready for test.
