### ISSUE TITLE
Copy-Paste from Windows 7 to Ubuntu Freezes the program I paste in

### ISSUE THREAD

**Issue by didibus** [synergy/synergy#4773]
When I copy some text from Windows 7 and paste it in Ubuntu 12.04.5 the program I'm pasting in often freezes.

Synergy shows: ```ERROR: corrupted clipboard data, expected size=784 actual size=0```

This seems to happen more when the source of the copy is Firefox on Windows. Where I'm pasting does not seem to matter.

On top of making the app I'm pasting in freeze, my mouse stops being able to move across after this happens, and I need to stop and start the server again to make it work.

I get this behavior with Synergy Pro 1.7.3. SSL is not enabled. The 1.6 version I was using before did not have this problem.

**Comment by beporter** [comment]
Oh so many possible duplicates: https://github.com/synergy/synergy/issues/4735#issuecomment-108422245

**Comment by unwiredben** [comment]
There seems to be some sort of 1024-ish limit in the new protocol.  Doing some testing from my Redhat 22 server to my Windows 7 client, both running 1.7.3, I found that I'd get debug notifications on Windows about clipboard changed up through 1012 characters, but if my original copy buffer was larger than that, I'd get no clipboard update on Windows at all.  Here's the log of the largest payload that came over OK:

    INFO: entering screen
    DEBUG: start receiving clipboard data
    DEBUG: received clipboard 0 size=1024
    DEBUG: open clipboard
    DEBUG: empty clipboard
    DEBUG: add 1012 bytes to clipboard format: 0
    DEBUG: close clipboard
    INFO: leaving screen

**Comment by speaker** [comment]
Duplicate #4712
