### ISSUE TITLE
System tray is unavailable, quitting error in Elementary OS Freya

### ISSUE THREAD

**Issue by THPubs** [synergy/synergy#4774]
On some installations of Freya I get an error saying `System tray is unavailable, quitting` when trying to launch the app. In some installations it works fine! What might be the issue?

**Comment by THPubs** [comment]
PS : Not on some... In all installations this happens. I think it have something to do with a recent update.

**Comment by THPubs** [comment]
Found the solution! After running `apt-get autoremove` the system have removed the package `sni-qt` which is used by `synergy` to add the tray icon. I have no idea why autoremove removed a package which is needed by another package. It should remove only the packages which are not used. Is it a problem in `synergy` ?

**Comment by vacoj** [comment]
Thanks for posting this - I was having the same issue.

**Comment by orschiro** [comment]
Hi all, 

I encountered the same issue with both CopyQ and RescueTime. Thanks for your solution that worked on my eOS system as well!

Anybody an idea why `sny-qt` has been considered redundant by the system?

**Comment by speaker** [comment]
Looks like this has been resolved, thank you @THPubs for the catch.
