### ISSUE TITLE
Synergy Server (rhel6) - Doublefree crash on client connection (osx)

### ISSUE THREAD

**Issue by zblach** [synergy/synergy#4780]
RHEL6 synergy server crashes immediately after client connects. Latest version (1.7.3) on both client and server.

Seems to only be an issue when connecting over SSL.

    NOTE: log level: INFO
    NOTE: started server, waiting for clients
    NOTE: accepted client connection
    *** glibc detected *** /usr/bin/synergys: double free or corruption (fasttop): 0x00007f3fb000f990 ***
    ======= Backtrace: =========
    /lib64/libc.so.6[0x3f28275e66]
    /usr/lib64/libcrypto.so.10(CRYPTO_free+0x1d)[0x3f33a6ad1d]
    /usr/lib64/libcrypto.so.10(BIO_free+0x90)[0x3f33adc3b0]
    /usr/lib64/libcrypto.so.10(BIO_free_all+0x24)[0x3f33adc3e4]
    /usr/lib64/libssl.so.10(SSL_free+0x8b)[0x3f36a44cbb]
    /home/zblacher/.synergy/plugins/libns.so(_ZN12SecureSocketD1Ev+0x45)[0x7f3fb70f3465]
    /home/zblacher/.synergy/plugins/libns.so(_ZN12SecureSocketD0Ev+0x9)[0x7f3fb70f34e9]
    /home/zblacher/.synergy/plugins/libns.so(_ZN18SecureListenSocket12deleteSocketEPv+0x57)[0x7f3fb70f2847]
    /usr/bin/synergys(_ZN10EventQueue13dispatchEventERK5Event+0x58)[0x44b4e8]
    /usr/bin/synergys(_ZN10EventQueue4loopEv+0xdc)[0x44ec4c]
    /usr/bin/synergys(_ZN9ServerApp8mainLoopEv+0x3b0)[0x45a490]
    /usr/bin/synergys(_ZN9ServerApp8runInnerEiPPcP13ILogOutputterPFiiS1_E+0xb7)[0x459607]
    /usr/bin/synergys(_ZN3App3runEiPPc+0x42)[0x4583f2]
    /usr/bin/synergys(main+0x83)[0x444123]
    /lib64/libc.so.6(__libc_start_main+0xfd)[0x3f2821ed5d]
    /usr/bin/synergys[0x443ef9]
    ======= Memory map: ========
    00400000-004dd000 r-xp 00000000 08:02 24121015                           /usr/bin/synergys
    006dc000-006ea000 rw-p 000dc000 08:02 24121015                           /usr/bin/synergys
    006ea000-006eb000 rw-p 00000000 00:00 0 
    00a6e000-00af2000 rw-p 00000000 00:00 0                                  [heap]
    3f27e00000-3f27e20000 r-xp 00000000 08:02 13893705                       /lib64/ld-2.12.so
    3f2801f000-3f28020000 r--p 0001f000 08:02 13893705                       /lib64/ld-2.12.so
    3f28020000-3f28021000 rw-p 00020000 08:02 13893705                       /lib64/ld-2.12.so
    3f28021000-3f28022000 rw-p 00000000 00:00 0 
    3f28200000-3f2838a000 r-xp 00000000 08:02 13893707                       /lib64/libc-2.12.so
    3f2838a000-3f2858a000 ---p 0018a000 08:02 13893707                       /lib64/libc-2.12.so
    3f2858a000-3f2858e000 r--p 0018a000 08:02 13893707                       /lib64/libc-2.12.so
    3f2858e000-3f2858f000 rw-p 0018e000 08:02 13893707                       /lib64/libc-2.12.so
    3f2858f000-3f28594000 rw-p 00000000 00:00 0 
    3f28600000-3f28602000 r-xp 00000000 08:02 13893726                       /lib64/libdl-2.12.so
    3f28602000-3f28802000 ---p 00002000 08:02 13893726                       /lib64/libdl-2.12.so
    3f28802000-3f28803000 r--p 00002000 08:02 13893726                       /lib64/libdl-2.12.so
    3f28803000-3f28804000 rw-p 00003000 08:02 13893726                       /lib64/libdl-2.12.so
    3f28a00000-3f28a17000 r-xp 00000000 08:02 13893710                       /lib64/libpthread-2.12.so
    3f28a17000-3f28c17000 ---p 00017000 08:02 13893710                       /lib64/libpthread-2.12.so
    3f28c17000-3f28c18000 r--p 00017000 08:02 13893710                       /lib64/libpthread-2.12.so
    3f28c18000-3f28c19000 rw-p 00018000 08:02 13893710                       /lib64/libpthread-2.12.so
    3f28c19000-3f28c1d000 rw-p 00000000 00:00 0 
    3f28e00000-3f28e83000 r-xp 00000000 08:02 13893717                       /lib64/libm-2.12.so
    3f28e83000-3f29082000 ---p 00083000 08:02 13893717                       /lib64/libm-2.12.so
    3f29082000-3f29083000 r--p 00082000 08:02 13893717                       /lib64/libm-2.12.so
    3f29083000-3f29084000 rw-p 00083000 08:02 13893717                       /lib64/libm-2.12.so
    3f29200000-3f29207000 r-xp 00000000 08:02 13893712                       /lib64/librt-2.12.so
    3f29207000-3f29406000 ---p 00007000 08:02 13893712                       /lib64/librt-2.12.so
    3f29406000-3f29407000 r--p 00006000 08:02 13893712                       /lib64/librt-2.12.so
    3f29407000-3f29408000 rw-p 00007000 08:02 13893712                       /lib64/librt-2.12.so
    3f29600000-3f29615000 r-xp 00000000 08:02 13893722                       /lib64/libz.so.1.2.3
    3f29615000-3f29814000 ---p 00015000 08:02 13893722                       /lib64/libz.so.1.2.3
    3f29814000-3f29815000 r--p 00014000 08:02 13893722                       /lib64/libz.so.1.2.3
    3f29815000-3f29816000 rw-p 00015000 08:02 13893722                       /lib64/libz.so.1.2.3
    3f29e00000-3f29e1d000 r-xp 00000000 08:02 13893734                       /lib64/libselinux.so.1
    3f29e1d000-3f2a01c000 ---p 0001d000 08:02 13893734                       /lib64/libselinux.so.1
    3f2a01c000-3f2a01d000 r--p 0001c000 08:02 13893734                       /lib64/libselinux.so.1
    3f2a01d000-3f2a01e000 rw-p 0001d000 08:02 13893734                       /lib64/libselinux.so.1
    3f2a01e000-3f2a01f000 rw-p 00000000 00:00 0 
    3f2a600000-3f2a616000 r-xp 00000000 08:02 13893732                       /lib64/libresolv-2.12.so
    3f2a616000-3f2a816000 ---p 00016000 08:02 13893732                       /lib64/libresolv-2.12.so
    3f2a816000-3f2a817000 r--p 00016000 08:02 13893732                       /lib64/libresolv-2.12.so
    3f2a817000-3f2a818000 rw-p 00017000 08:02 13893732                       /lib64/libresolv-2.12.so
    3f2a818000-3f2a81a000 rw-p 00000000 00:00 0 
    3f2b200000-3f2b21d000 r-xp 00000000 08:02 24130085                       /usr/lib64/libxcb.so.1.1.0
    3f2b21d000-3f2b41d000 ---p 0001d000 08:02 24130085                       /usr/lib64/libxcb.so.1.1.0
    3f2b41d000-3f2b41e000 rw-p 0001d000 08:02 24130085                       /usr/lib64/libxcb.so.1.1.0
    3f2b600000-3f2b602000 r-xp 00000000 08:02 24130084                       /usr/lib64/libXau.so.6.0.0
    3f2b602000-3f2b802000 ---p 00002000 08:02 24130084                       /usr/lib64/libXau.so.6.0.0
    3f2b802000-3f2b803000 rw-p 00002000 08:02 24130084                       /usr/lib64/libXau.so.6.0.0
    3f2ba00000-3f2bb37000 r-xp 00000000 08:02 24130086                       /usr/lib64/libX11.so.6.3.0
    3f2bb37000-3f2bd37000 ---p 00137000 08:02 24130086                       /usr/lib64/libX11.so.6.3.0
    3f2bd37000-3f2bd3d000 rw-p 00137000 08:02 24130086                       /usr/lib64/libX11.so.6.3.0
    3f2c600000-3f2c612000 r-xp 00000000 08:02 24130092                       /usr/lib64/libXext.so.6.4.0
    3f2c612000-3f2c812000 ---p 00012000 08:02 24130092                       /usr/lib64/libXext.so.6.4.0
    3f2c812000-3f2c813000 rw-p 00012000 08:02 24130092                       /usr/lib64/libXext.so.6.4.0
    3f2ca00000-3f2ca09000 r-xp 00000000 08:02 24130087                       /usr/lib64/libXrender.so.1.3.0
    3f2ca09000-3f2cc09000 ---p 00009000 08:02 24130087                       /usr/lib64/libXrender.so.1.3.0
    3f2cc09000-3f2cc0a000 rw-p 00009000 08:02 24130087                       /usr/lib64/libXrender.so.1.3.0
    3f2d600000-3f2d60e000 r-xp 00000000 08:02 24130094                       /usr/lib64/libXi.so.6.1.0
    3f2d60e000-3f2d80e000 ---p 0000e000 08:02 24130094                       /usr/lib64/libXi.so.6.1.0
    3f2d80e000-3f2d80f000 rw-p 0000e000 08:02 24130094                       /usr/lib64/libXi.so.6.1.0
    3f2de00000-3f2de51000 r-xp 00000000 08:02 24130128                       /usr/lib64/libcurl.so.4.1.1
    3f2de51000-3f2e050000 ---p 00051000 08:02 24130128                       /usr/lib64/libcurl.so.4.1.1
    3f2e050000-3f2e053000 rw-p 00050000 08:02 24130128                       /usr/lib64/libcurl.so.4.1.1
    3f2e600000-3f2e602000 r-xp 00000000 08:02 24130093                       /usr/lib64/libXinerama.so.1.0.0
    3f2e602000-3f2e801000 ---p 00002000 08:02 24130093                       /usr/lib64/libXinerama.so.1.0.0
    3f2e801000-3f2e802000 rw-p 00001000 08:02 24130093                       /usr/lib64/libXinerama.so.1.0.0
    3f2ea00000-3f2ea0a000 r-xp 00000000 08:02 24130095                       /usr/lib64/libXrandr.so.2.2.0
    3f2ea0a000-3f2ec09000 ---p 0000a000 08:02 24130095                       /usr/lib64/libXrandr.so.2.2.0
    3f2ec09000-3f2ec0a000 rw-p 00009000 08:02 24130095                       /usr/lib64/libXrandr.so.2.2.0
    3f2ee00000-3f2ee05000 r-xp 00000000 08:02 24130096                       /usr/lib64/libXfixes.so.3.1.0
    3f2ee05000-3f2f005000 ---p 00005000 08:02 24130096                       /usr/lib64/libXfixes.so.3.1.0
    3f2f005000-3f2f006000 rw-p 00005000 08:02 24130096                       /usr/lib64/libXfixes.so.3.1.0
    3f2fa00000-3f2fa09000 r-xp 00000000 08:02 24130097                       /usr/lib64/libXcursor.so.1.0.2
    3f2fa09000-3f2fc09000 ---p 00009000 08:02 24130097                       /usr/lib64/libXcursor.so.1.0.2
    3f2fc09000-3f2fc0a000 rw-p 00009000 08:02 24130097                       /usr/lib64/libXcursor.so.1.0.2
    3f32600000-3f32632000 r-xp 00000000 08:02 13894105                       /lib64/libidn.so.11.6.1
    3f32632000-3f32831000 ---p 00032000 08:02 13894105                       /lib64/libidn.so.11.6.1
    3f32831000-3f32832000 rw-p 00031000 08:02 13894105                       /lib64/libidn.so.11.6.1
    3f32a00000-3f32a16000 r-xp 00000000 08:02 13893744                       /lib64/libgcc_s-4.4.7-20120601.so.1
    3f32a16000-3f32c15000 ---p 00016000 08:02 13893744                       /lib64/libgcc_s-4.4.7-20120601.so.1
    3f32c15000-3f32c16000 rw-p 00015000 08:02 13893744                       /lib64/libgcc_s-4.4.7-20120601.so.1
    3f33200000-3f33204000 r-xp 00000000 08:02 13893779                       /lib64/libuuid.so.1.3.0
    3f33204000-3f33403000 ---p 00004000 08:02 13893779                       /lib64/libuuid.so.1.3.0
    3f33403000-3f33404000 rw-p 00003000 08:02 13893779                       /lib64/libuuid.so.1.3.0
    3f33a00000-3f33bb9000 r-xp 00000000 08:02 24127676                       /usr/lib64/libcrypto.so.1.0.1e
    3f33bb9000-3f33db8000 ---p 001b9000 08:02 24127676                       /usr/lib64/libcrypto.so.1.0.1e
    3f33db8000-3f33dd3000 r--p 001b8000 08:02 24127676                       /usr/lib64/libcrypto.so.1.0.1e
    3f33dd3000-3f33ddf000 rw-p 001d3000 08:02 24127676                       /usr/lib64/libcrypto.so.1.0.1e
    3f33ddf000-3f33de3000 rw-p 00000000 00:00 0 
    3f33e00000-3f33e07000 r-xp 00000000 08:02 13893748                       /lib64/libcrypt-2.12.so
    3f33e07000-3f34007000 ---p 00007000 08:02 13893748                       /lib64/libcrypt-2.12.so
    3f34007000-3f34008000 r--p 00007000 08:02 13893748                       /lib64/libcrypt-2.12.so
    3f34008000-3f34009000 rw-p 00008000 08:02 13893748                       /lib64/libcrypt-2.12.so
    3f34009000-3f34037000 rw-p 00000000 00:00 0 
    3f34200000-3f342e8000 r-xp 00000000 08:02 24130104                       /usr/lib64/libstdc++.so.6.0.13
    3f342e8000-3f344e8000 ---p 000e8000 08:02 24130104                       /usr/lib64/libstdc++.so.6.0.13
    3f344e8000-3f344ef000 r--p 000e8000 08:02 24130104                       /usr/lib64/libstdc++.so.6.0.13
    3f344ef000-3f344f1000 rw-p 000ef000 08:02 24130104                       /usr/lib64/libstdc++.so.6.0.13
    3f344f1000-3f34506000 rw-p 00000000 00:00 0 
    3f34600000-3f34666000 r-xp 00000000 08:02 13893746                       /lib64/libfreebl3.so
    3f34666000-3f34866000 ---p 00066000 08:02 13893746                       /lib64/libfreebl3.so
    3f34866000-3f34867000 r--p 00066000 08:02 13893746                       /lib64/libfreebl3.so
    3f34867000-3f34868000 rw-p 00067000 08:02 13893746                       /lib64/libfreebl3.so
    3f34868000-3f3486c000 rw-p 00000000 00:00 0 
    3f34a00000-3f34a17000 r-xp 00000000 08:02 24121283                       /usr/lib64/libICE.so.6.3.0
    3f34a17000-3f34c17000 ---p 00017000 08:02 24121283                       /usr/lib64/libICE.so.6.3.0
    3f34c17000-3f34c18000 rw-p 00017000 08:02 24121283                       /usr/lib64/libICE.so.6.3.0
    3f34c18000-3f34c1c000 rw-p 00000000 00:00 0 
    3f34e00000-3f34e07000 r-xp 00000000 08:02 24130108                       /usr/lib64/libSM.so.6.0.1
    3f34e07000-3f35007000 ---p 00007000 08:02 24130108                       /usr/lib64/libSM.so.6.0.1
    3f35007000-3f35008000 rw-p 00007000 08:02 24130108                       /usr/lib64/libSM.so.6.0.1
    3f35200000-3f35203000 r-xp 00000000 08:02 13893760                       /lib64/libcom_err.so.2.1
    3f35203000-3f35402000 ---p 00003000 08:02 13893760                       /lib64/libcom_err.so.2.1
    3f35402000-3f35403000 r--p 00002000 08:02 13893760                       /lib64/libcom_err.so.2.1
    3f35403000-3f35404000 rw-p 00003000 08:02 13893760                       /lib64/libcom_err.so.2.1
    3f35600000-3f35602000 r-xp 00000000 08:02 13893753                       /lib64/libkeyutils.so.1.3
    3f35602000-3f35801000 ---p 00002000 08:02 13893753                       /lib64/libkeyutils.so.1.3
    3f35801000-3f35802000 r--p 00001000 08:02 13893753                       /lib64/libkeyutils.so.1.3
    3f35802000-3f35803000 rw-p 00002000 08:02 13893753                       /lib64/libkeyutils.so.1.3
    3f35a00000-3f35a0a000 r-xp 00000000 08:02 13893755                       /lib64/libkrb5support.so.0.1
    3f35a0a000-3f35c09000 ---p 0000a000 08:02 13893755                       /lib64/libkrb5support.so.0.1
    3f35c09000-3f35c0a000 r--p 00009000 08:02 13893755                       /lib64/libkrb5support.so.0.1
    3f35c0a000-3f35c0b000 rw-p 0000a000 08:02 13893755                       /lib64/libkrb5support.so.0.1
    3f35e00000-3f35e41000 r-xp 00000000 08:02 13893764                       /lib64/libgssapi_krb5.so.2.2
    3f35e41000-3f36041000 ---p 00041000 08:02 13893764                       /lib64/libgssapi_krb5.so.2.2
    3f36041000-3f36042000 r--p 00041000 08:02 13893764                       /lib64/libgssapi_krb5.so.2.2
    3f36042000-3f36044000 rw-p 00042000 08:02 13893764                       /lib64/libgssapi_krb5.so.2.2
    3f36200000-3f362db000 r-xp 00000000 08:02 13893762                       /lib64/libkrb5.so.3.3
    3f362db000-3f364da000 ---p 000db000 08:02 13893762                       /lib64/libkrb5.so.3.3
    3f364da000-3f364e4000 r--p 000da000 08:02 13893762                       /lib64/libkrb5.so.3.3
    3f364e4000-3f364e6000 rw-p 000e4000 08:02 13893762                       /lib64/libkrb5.so.3.3
    3f36600000-3f36629000 r-xp 00000000 08:02 13893756                       /lib64/libk5crypto.so.3.1
    3f36629000-3f36829000 ---p 00029000 08:02 13893756                       /lib64/libk5crypto.so.3.1
    3f36829000-3f3682a000 r--p 00029000 08:02 13893756                       /lib64/libk5crypto.so.3.1
    3f3682a000-3f3682b000 rw-p 0002a000 08:02 13893756                       /lib64/libk5crypto.so.3.1
    3f3682b000-3f3682c000 rw-p 00000000 00:00 0 
    3f36a00000-3f36a62000 r-xp 00000000 08:02 24130106                       /usr/lib64/libssl.so.1.0.1e
    3f36a62000-3f36c61000 ---p 00062000 08:02 24130106                       /usr/lib64/libssl.so.1.0.1e
    3f36c61000-3f36c65000 r--p 00061000 08:02 24130106                       /usr/lib64/libssl.so.1.0.1e
    3f36c65000-3f36c6c000 rw-p 00065000 08:02 24130106                       /usr/lib64/libssl.so.1.0.1e
    3f37200000-3f37225000 r-xp 00000000 08:02 24120201                       /usr/lib64/libnssutil3.so
    3f37225000-3f37424000 ---p 00025000 08:02 24120201                       /usr/lib64/libnssutil3.so
    3f37424000-3f3742a000 r--p 00024000 08:02 24120201                       /usr/lib64/libnssutil3.so
    3f3742a000-3f3742b000 rw-p 0002a000 08:02 24120201                       /usr/lib64/libnssutil3.so
    3f37600000-3f37639000 r-xp 00000000 08:02 13893789                       /lib64/libnspr4.so
    3f37639000-3f37839000 ---p 00039000 08:02 13893789                       /lib64/libnspr4.so
    3f37839000-3f3783a000 r--p 00039000 08:02 13893789                       /lib64/libnspr4.so
    3f3783a000-3f3783c000 rw-p 0003a000 08:02 13893789                       /lib64/libnspr4.so
    3f3783c000-3f3783e000 rw-p 00000000 00:00 0 
    3f37a00000-3f37a04000 r-xp 00000000 08:02 13893791                       /lib64/libplc4.so
    3f37a04000-3f37c03000 ---p 00004000 08:02 13893791                       /lib64/libplc4.so
    3f37c03000-3f37c04000 r--p 00003000 08:02 13893791                       /lib64/libplc4.so
    3f37c04000-3f37c05000 rw-p 00004000 08:02 13893791                       /lib64/libplc4.so
    3f37e00000-3f37e03000 r-xp 00000000 08:02 13893849                       /lib64/libplds4.so
    3f37e03000-3f38002000 ---p 00003000 08:02 13893849                       /lib64/libplds4.so
    3f38002000-3f38003000 r--p 00002000 08:02 13893849                       /lib64/libplds4.so
    3f38003000-3f38004000 rw-p 00003000 08:02 13893849                       /lib64/libplds4.so
    3f38200000-3f38335000 r-xp 00000000 08:02 24130111                       /usr/lib64/libnss3.so
    3f38335000-3f38534000 ---p 00135000 08:02 24130111                       /usr/lib64/libnss3.so
    3f38534000-3f38539000 r--p 00134000 08:02 24130111                       /usr/lib64/libnss3.so
    3f38539000-3f3853b000 rw-p 00139000 08:02 24130111                       /usr/lib64/libnss3.so
    3f3853b000-3f3853d000 rw-p 00000000 00:00 0 
    3f38600000-3f38628000 r-xp 00000000 08:02 24130126                       /usr/lib64/libsmime3.so
    3f38628000-3f38828000 ---p 00028000 08:02 24130126                       /usr/lib64/libsmime3.so
    3f38828000-3f3882b000 r--p 00028000 08:02 24130126                       /usr/lib64/libsmime3.so
    3f3882b000-3f3882c000 rw-p 0002b000 08:02 24130126                       /usr/lib64/libsmime3.so
    3f38a00000-3f38a33000 r-xp 00000000 08:02 24130125                       /usr/lib64/libssl3.so
    3f38a33000-3f38c33000 ---p 00033000 08:02 24130125                       /usr/lib64/libssl3.so
    3f38c33000-3f38c35000 r--p 00033000 08:02 24130125                       /usr/lib64/libssl3.so
    3f38c35000-3f38c36000 rw-p 00035000 08:02 24130125                       /usr/lib64/libssl3.so
    3f38c36000-3f38c37000 rw-p 00000000 00:00 0 
    3f39e00000-3f39e16000 r-xp 00000000 08:02 13893750                       /lib64/libnsl-2.12.so
    3f39e16000-3f3a015000 ---p 00016000 08:02 13893750                       /lib64/libnsl-2.12.so
    3f3a015000-3f3a016000 r--p 00015000 08:02 13893750                       /lib64/libnsl-2.12.so
    3f3a016000-3f3a017000 rw-p 00016000 08:02 13893750                       /lib64/libnsl-2.12.so
    3f3a017000-3f3a019000 rw-p 00000000 00:00 0 
    3f3aa00000-3f3aa05000 r-xp 00000000 08:02 24130148                       /usr/lib64/libXtst.so.6.1.0
    3f3aa05000-3f3ac05000 ---p 00005000 08:02 24130148                       /usr/lib64/libXtst.so.6.1.0
    3f3ac05000-3f3ac06000 rw-p 00005000 08:02 24130148                       /usr/lib64/libXtst.so.6.1.0
    3f3ae00000-3f3ae27000 r-xp 00000000 08:02 24130127                       /usr/lib64/libssh2.so.1.0.1
    3f3ae27000-3f3b026000 ---p 00027000 08:02 24130127                       /usr/lib64/libssh2.so.1.0.1
    3f3b026000-3f3b027000 rw-p 00026000 08:02 24130127                       /usr/lib64/libssh2.so.1.0.1
    3f3b027000-3f3b028000 rw-p 00000000 00:00 0 
    3f3b600000-3f3b649000 r-xp 00000000 08:02 13894106                       /lib64/libldap-2.4.so.2.5.6
    3f3b649000-3f3b849000 ---p 00049000 08:02 13894106                       /lib64/libldap-2.4.so.2.5.6
    3f3b849000-3f3b84b000 r--p 00049000 08:02 13894106                       /lib64/libldap-2.4.so.2.5.6
    3f3b84b000-3f3b84d000 rw-p 0004b000 08:02 13894106                       /lib64/libldap-2.4.so.2.5.6
    3f3ba00000-3f3ba0e000 r-xp 00000000 08:02 13893639                       /lib64/liblber-2.4.so.2.5.6
    3f3ba0e000-3f3bc0d000 ---p 0000e000 08:02 13893639                       /lib64/liblber-2.4.so.2.5.6
    3f3bc0d000-3f3bc0e000 r--p 0000d000 08:02 13893639                       /lib64/liblber-2.4.so.2.5.6
    3f3bc0e000-3f3bc0f000 rw-p 0000e000 08:02 13893639                       /lib64/liblber-2.4.so.2.5.6
    3f3c600000-3f3c619000 r-xp 00000000 08:02 24130124                       /usr/lib64/libsasl2.so.2.0.23
    3f3c619000-3f3c818000 ---p 00019000 08:02 24130124                       /usr/lib64/libsasl2.so.2.0.23
    3f3c818000-3f3c819000 r--p 00018000 08:02 24130124                       /usr/lib64/libsasl2.so.2.0.23
    3f3c819000-3f3c81a000 rw-p 00019000 08:02 24130124                       /usr/lib64/libsasl2.so.2.0.23
    7f3fb0000000-7f3fb0021000 rw-p 00000000 00:00 0 
    7f3fb0021000-7f3fb4000000 ---p 00000000 00:00 0 
    7f3fb70d2000-7f3fb7112000 r-xp 00000000 08:02 19808846                   /home/zblacher/.synergy/plugins/libns.so
    7f3fb7112000-7f3fb7311000 ---p 00040000 08:02 19808846                   /home/zblacher/.synergy/plugins/libns.so
    7f3fb7311000-7f3fb7316000 rw-p 0003f000 08:02 19808846                   /home/zblacher/.synergy/plugins/libns.so
    7f3fb7316000-7f3fb7317000 rw-p 00000000 00:00 0 
    7f3fb7317000-7f3fb73f6000 r-xp 00000000 08:02 26739174                   /opt/likewise/lib64/libiconv.so.2.4.0
    7f3fb73f6000-7f3fb74f6000 ---p 000df000 08:02 26739174                   /opt/likewise/lib64/libiconv.so.2.4.0
    7f3fb74f6000-7f3fb74f8000 rw-p 000df000 08:02 26739174                   /opt/likewise/lib64/libiconv.so.2.4.0
    7f3fb74f8000-7f3fb7517000 r-xp 00000000 08:02 26739204                   /opt/likewise/lib64/liblwmsg_nothr.so.0.0.0
    7f3fb7517000-7f3fb7616000 ---p 0001f000 08:02 26739204                   /opt/likewise/lib64/liblwmsg_nothr.so.0.0.0
    7f3fb7616000-7f3fb7619000 rw-p 0001e000 08:02 26739204                   /opt/likewise/lib64/liblwmsg_nothr.so.0.0.0
    7f3fb7619000-7f3fb769a000 r-xp 00000000 08:02 26739194                   /opt/likewise/lib64/liblwbase_nothr.so.0.0.0
    7f3fb769a000-7f3fb7799000 ---p 00081000 08:02 26739194                   /opt/likewise/lib64/liblwbase_nothr.so.0.0.0
    7f3fb7799000-7f3fb77c7000 rw-p 00080000 08:02 26739194                   /opt/likewise/lib64/liblwbase_nothr.so.0.0.0
    7f3fb77c7000-7f3fb77e9000 r-xp 00000000 08:02 26739184                   /opt/likewise/lib64/liblwadvapi_nothr.so.0.0.0
    7f3fb77e9000-7f3fb78e9000 ---p 00022000 08:02 26739184                   /opt/likewise/lib64/liblwadvapi_nothr.so.0.0.0
    7f3fb78e9000-7f3fb78f1000 rw-p 00022000 08:02 26739184                   /opt/likewise/lib64/liblwadvapi_nothr.so.0.0.0
    7f3fb78f1000-7f3fb7919000 r-xp 00000000 08:02 26739470                   /opt/likewise/lib64/liblsacommon.so.0.0.0
    7f3fb7919000-7f3fb7a18000 ---p 00028000 08:02 26739470                   /opt/likewise/lib64/liblsacommon.so.0.0.0
    7f3fb7a18000-7f3fb7a25000 rw-p 00027000 08:02 26739470                   /opt/likewise/lib64/liblsacommon.so.0.0.0
    7f3fb7a25000-7f3fb7a3d000 r-xp 00000000 08:02 26739460                   /opt/likewise/lib64/liblsaclient.so.0.0.0
    7f3fb7a3d000-7f3fb7b3c000 ---p 00018000 08:02 26739460                   /opt/likewise/lib64/liblsaclient.so.0.0.0
    7f3fb7b3c000-7f3fb7b3d000 rw-p 00017000 08:02 26739460                   /opt/likewise/lib64/liblsaclient.so.0.0.0
    7f3fb7b3d000-7f3fb7b40000 r-xp 00000000 08:02 26739455                   /opt/likewise/lib64/liblsaauth.so.0.0.0
    7f3fb7b40000-7f3fb7c3f000 ---p 00003000 08:02 26739455                   /opt/likewise/lib64/liblsaauth.so.0.0.0
    7f3fb7c3f000-7f3fb7c40000 rw-p 00002000 08:02 26739455                   /opt/likewise/lib64/liblsaauth.so.0.0.0
    7f3fb7c40000-7f3fb7c46000 r-xp 00000000 08:02 13894044                   /lib64/libnss_lsass.so.2.0.0
    7f3fb7c46000-7f3fb7d45000 ---p 00006000 08:02 13894044                   /lib64/libnss_lsass.so.2.0.0
    7f3fb7d45000-7f3fb7d46000 rw-p 00005000 08:02 13894044                   /lib64/libnss_lsass.so.2.0.0
    7f3fb7d46000-7f3fb7d52000 r-xp 00000000 08:02 13893661                   /lib64/libnss_files-2.12.so
    7f3fb7d52000-7f3fb7f52000 ---p 0000c000 08:02 13893661                   /lib64/libnss_files-2.12.so
    7f3fb7f52000-7f3fb7f53000 r--p 0000c000 08:02 13893661                   /lib64/libnss_files-2.12.so
    7f3fb7f53000-7f3fb7f54000 rw-p 0000d000 08:02 13893661                   /lib64/libnss_files-2.12.so
    7f3fb7f54000-7f3fb7f55000 ---p 00000000 00:00 0 
    7f3fb7f55000-7f3fb8955000 rw-p 00000000 00:00 0 
    7f3fb8955000-7f3fb8956000 ---p 00000000 00:00 0 
    7f3fb8956000-7f3fb936d000 rw-p 00000000 00:00 0 
    7f3fb937f000-7f3fb9382000 rw-p 00000000 00:00 0 
    7fffb9c28000-7fffb9c3d000 rw-p 00000000 00:00 0                          [stack]
    7fffb9dea000-7fffb9deb000 r-xp 00000000 00:00 0                          [vdso]
    ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by VeNoMouS** [comment]
How about you supplying the dev's with some info... like version... and learn to github markdown....

**Comment by VeNoMouS** [comment]
@nbolton is there any other open ticket you can link this too?

**Comment by XinyuHou** [comment]
duplicated to #4561
