### ISSUE TITLE
Drag and drop does not work from Windows Explorer

### ISSUE THREAD

**Issue by shoelzer** [synergy/synergy#4781]
@XinyuHou
I am testing beta 5c71efe to verify a fix for #4584. I can drag and drop files from the desktop of my two Windows 7 machines, but I cannot drag and drop from Windows Explorer. I tried from both the server and client. They both give the same error in the log:

~~~
DEBUG: failed to get drag file name from OLE
~~~

**Comment by XinyuHou** [comment]
@shoelzer 
Did you use elevate mode?

**Comment by shoelzer** [comment]
@XinyuHou 
I was not using elevate mode but I tried it just now and got the same result.

I changed the elevate setting, then clicked stop and start in the Synergy GUI. Do I need to do anything else?

I don't really understand elevate mode in general. I enabled it on the server and client. Is that right?

**Comment by shoelzer** [comment]
@XinyuHou 
I turned off elevate mode, tried again, and now it works. I don't understand.

**Comment by shoelzer** [comment]
@XinyuHou 
I just tried nightly 8e15b77 and it still works. Closing the issue since I can't reproduce.

**Comment by XinyuHou** [comment]
@shoelzer 
If you enable elevate mode, drag and drop would not work.

Elevate mode is useful when UAC or login screen is on. But we have a feature automatically detect if elevate mode is needed and switch between normal user and system user. Unless you want Synergy in elevate mode all the time, don't turn it on.
