### ISSUE TITLE
Release 1.7.3 unusually high cpu usage

### ISSUE THREAD

**Issue by furrydad** [synergy/synergy#4782]
I have installed 1.7.3 as a client on a win7 machine which has had many versions of synergy in the past.  I do not know previously how much cpu it used, but it did not interfere with my other programs.  After installation, it now uses between 50 and 80% of the cpu whether I am using it from the server or not.  What information can I collect/provide to you to make this better.

**Comment by XinyuHou** [comment]
Is synergys/c or synergyd using the CPU?

**Comment by egustafson** [comment]
I am observing (what I think is) the same problem.  It started when I upgraded to 173 and I have run many previous versions.

1) it's synergyd
2) It appears to eat 1 core.  on a 4 core host it's 25% on my 8 core it's 12.5 %
   (core == 1 thread of the hyperthread, which appears as a separate thread in most process tools)
3) Windows 7 on both hosts (client & server).  I do not have any other OS in the mix.

I restarted both the client and the server using the Synergy dialog box's "start/stop" button.   Both hosts' processes came up and did _not_ consume CPU.   After ~1-2 min I closed both hosts' Synergy dialog boxes.  Both processes (synergyd) remained at a nominal cpu use (<0.1% utilization) for a few minutes.

After a few minutes (2-3) the client host began consuming 1 core's worth of cpu (25% in this case).  After another 45-60 seconds I opened the Synergy dialog, but did NOT stop/start the service.  When I opened the clients dialog the synergyd process stopped consuming CPU and went back to (<0.1% utilization).

Closing the (client) dialog box and waiting ~30-40s causes the client to start running synergyd at ~25% again.  Additionally, about the time I closed the client dialog the server's synergyd started consuming one core of cpu (12.5%)

... Sorry for the long winded description.   CPU came up and can be made to go down on both the client and server by starting (downs cpu) and closing (ups cpu use) the Synergy app (dialog box).  I repeated the process 3/4 times on each host.

Work around:  Run the synergy app (dialog) and select the "Window -> Hide" option to place the dialog in the windows tray -- which keeps the CPU from rising above a nominal <0.1% cpu utilization.

I'm available to capture more information or experiment, just comment here in the issue.

Thanks for the product love - Eric

**Comment by XinyuHou** [comment]
@egustafson 
Your issue is more related to #4721. Please check that and there is a nightly ready for test.

**Comment by XinyuHou** [comment]
@furrydad 
If it is synergyd using the CPU, please check #4721 and close this issue.

**Comment by egustafson** [comment]
#4721 and nightly build 7795d68 resolved my issue.  12+ hrs of monitored use with no problems.

**Comment by XinyuHou** [comment]
duplicated to #4721
