### ISSUE TITLE
Unable to cut and paste from an ubuntu client (15.01) to MS server (7) - using synergy 1.7.3 all across

### ISSUE THREAD

**Issue by gitsheema** [synergy/synergy#4785]
Hi:

I am using Synergy 1.7.3.
Windows 7 machine is the server 
Mac and Ubuntu based machines are clients.
The cut and paste from Ubuntu to Windows or to Mac is not working.
But the reverse is working..
Can you please help?

**Comment by beporter** [comment]
There are a few possible causes/duplicates of your problem already. Please scan the Issues in this list and see if any describe your problem in more detail: https://github.com/synergy/synergy/issues/4735#issuecomment-108422245

If you find an existing report that matches your current problem, please close this one so we can keep things manageable for the developers. And in the future, it never hurts to search the existing Issues before posting a new one.

**Comment by gitsheema** [comment]
I agree it seems to be duplicate. However I do to see solution for the issue. If you keep #4735 as OPEN and help us to find a fix - would be really appreciated....

**Comment by beporter** [comment]
The two most common causes are:

**Copying "rich" text fails** (#2909): Workaround is to copy your text into a plaintext program like Notepad _on the same machine first_, then **re**-copy it from there before moving to the other system to paste.

**SSL limits clipboard to 1024 characters** (#4712): Workaround is to disable SSL on all machines.

**Comment by gitsheema** [comment]
Thank you for your response. But I tried both ways..

The issue is between Ubuntu (as client) to other participants in synergy 
network.

I have also disabled SSL on all machines.

My arrangements are

Ubuntu-client --- Mac-Client --- Win-PC-Srvr:

When I tried to copy text from Ubuntu-client and paste to Win-PC-Srvr 
this is what I see in the logs. Clipboard is empty.

INFO: switch from "ubuntu-client" to "mac-client" at 4,725

ERROR: invalid message from client "ubuntu-client": DCLP

INFO: switch from "mac-client" to "win-pc-srvr" at 22,471

INFO: entering screen

INFO: previous clipboard data has become invalid

NOTE: accepted client connection

NOTE: client "ubuntu-client" has connected

**Comment by gitsheema** [comment]
Never mind ... It looks like it takes time to copy the clipboard system 
to system.

Sorry... I just have to give it some time... (must be local network delay)

**Comment by XinyuHou** [comment]
Please turn the log level to Debug, it would show the clipboard info. Something like:

DEBUG: added 123 bytes to clipboard format: 0

A good example is when I copy a image from google image in chrome, it actually copies both the image and the html data, so when move cursor to the other side, it transfers those 2 formats. The issue is some programs don't accept this. For example the image I copied from above can not be pasted into photoshop, but can be pasted into gmail. If I do the same thing on my Mac, it only copy the image data, so in this case I can paste into paint but not my gmail.
