### ISSUE TITLE
Install Windows service

### ISSUE THREAD

**Issue by lukeyeager** [synergy/synergy#4786]
Here's my setup. I'm trying to get all of these OS's to start Synergy on login.

### Server - working

OS - Ubuntu 14.04
Guide - https://help.ubuntu.com/community/SynergyHowto
Startup Application - `/usr/bin/synergys`
Configuration file - `~/.synergy.conf`

### Client 1 - working

OS - OSX 10.10
Guide - https://github.com/synergy/synergy/blob/v1.7.3-stable/doc/org.synergy-foss.org.synergyc.plist
launchctl configuration file - `~/Library/LaunchAgents/org.synergy-project.org.synergyc.plist`

### Client 2 - NOT WORKING

OS - Windows 7
Guide - *None?*

When I run `Synergy.exe` manually, I get this error:
```
ERROR: ssl error occurred (generic failure)
ERROR: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
ERROR: failed to connect secure socket
```
I can get it to work by unchecking "Use SSL encryption." Whatever.

But I need it to start on login. I tried:
```
> synergyc.exe --service install
WARNING: obsolete argument --service, use synergyd instead.

> synergyd.exe
The service process could not connect to the service controller.
```
**Where is the guide for windows?** All the docs seem to imply that the service will just install itself and I won't have to worry about it.

**Comment by XinyuHou** [comment]
@lukeyeager 

This looks more like a support ticket. 

Please use our [forum](http://synergy-project.org/forum/).

**Comment by DieselDriver** [comment]
Same issue.
How can I install the synergyd service?
I downloaded the synergy-1.xx.xx.xx-adxxxxx-windows-10-amd64.zip file - there is no installer included.

How can I install the Synergy service?

Thanks.
