### ISSUE TITLE
Synergy server stops after moving cursor out of a full-screen mode vmplayer

### ISSUE THREAD

**Issue by kopwei** [synergy/synergy#4790]
I am using synergy pro 1.7.3 on 2 computers, A Ubuntu PC (14.04) and a Mac book (OS X 10.10.3). The synergy server and VMPlayer is running on the Ubuntu PC and Macbook has synergy running in client mode.
After I setup and start server/client on both computers, it works fine. But when I started the VM (windows 10) in VM player and enter the full screen mode on Ubuntu PC, once I want to move the mouse cursor out of the screen to the Mac screen, the synergy server stops running and I have to restart synergy server and re-connect the client.

**Comment by speaker** [comment]
@kopwei , VirtualBox has a mode where the mouse is completely commandeered by the VM and synergy gets no signaling from windows. If the VM is then put in full screen, it behaves as if synergy isn't running at all. I wonder if the same thing is going on with VM player?  In VB, you hit right-ctrl and it frees the mouse up from the VM and everything goes back to normal.

**Comment by XinyuHou** [comment]
@kopwei 
I can't identify the bug since there is no error or log. So I have to close it.
