### ISSUE TITLE
Improve secure socket intensive try operations

### ISSUE THREAD

**Issue by XinyuHou** [synergy/synergy#4796]
Problem: When use non-block socket with SSL and a call to a function return WANT_WRITE or WANT_READ, the same function needs to be called again. Right now we simple recall this function and give it a maximum retry threshold.

Solution: use poll or select to check on the readability and writability.

**Comment by XinyuHou** [comment]
Resolved by 3e32d9fbee026c337ea8c6d4b479ddc50d1a344a

**Comment by nbolton** [comment]
Please test this pre-release to confirm this issue is fixed.
http://synergy-project.org/nightly?filter=v1.7.4-stable

**Comment by nbolton** [comment]
Duplicates #4750
