### ISSUE TITLE
25% CPU overhead in synergyd.exe service - Win7

### ISSUE THREAD

**Issue by wlodek76** [synergy/synergy#4807]
Synergy Basic 1.7.3

One core is eaten by Synergy :-(

Windows7 64bit + Intel Core 4

<b>Temporary workaround!
Open synergy gui app and hide it into try icon then overhead is gone and all back to normal.</b>

Terminating and starting service again via services.msc does not solve the problem.
We need to open a synergy.exe application to eliminate the problem and allow synergy.exe to work in the background.

**Comment by dattas** [comment]
Same things happens on my system, same workaround works for me
Synergy Pro 1.7.3 acting as a client
Windows 10 build 10130
5th gen core i5

**Comment by XinyuHou** [comment]
Duplicated to #4721

**Comment by wlodek76** [comment]
<b>SOLVED in v1.7.4</b> - nightly build bd3a8e9
No CPU overhead now.
