### ISSUE TITLE
System freezes when opening GUI on Windows

### ISSUE THREAD

**Issue by speaker** [synergy/synergy#4809]
1. Use GUI on Windows
2. Open GUI
3. Close GUI
4. Open GUI
5. Entire system freezes

synergys can deadlock while sending stdout to synergyd in rare cases where one log output thread holds the logging mutex and another tried to check the loglevel. Solution is to stop locking the mutex when checking or setting the loglevel.

**Comment by speaker** [comment]
Might be one cause of the case of #4538

**Comment by nbolton** [comment]
Revert code, can not reproduce bug to prove fix.

**Comment by nbolton** [comment]
@XinyuHou Todo: Please revert commit 3eef49d in **master**, can not reproduce bug to prove fix.
