### ISSUE TITLE
Connection failure when PC reconnects to network

### ISSUE THREAD

**Issue by nassus** [synergy/synergy#4811]
Initial conditions: 
Laptop running windows 7 64bit, docked and connected to LAN as server . PC running windows 7 64bit, connected to the same network as client.

Observed behavior: 
When removing the laptop from docking station the connection is lost which is expected because the IP changes to wlan. But when the laptop is plugged back into the docking station, the connection is not established to the client.Synergy reports the following error: 
"ERROR: failed to init synwinhk.dll, another program may be using it
INFO: restarting your computer may solve this error
FATAL: failed to start server: unable to open screen"

Only a restart of server OS is fixing this issue.

**Comment by XinyuHou** [comment]
Duplicates #4721
