### ISSUE TITLE
Running the wizzard does not download the ssl plugin

### ISSUE THREAD

**Issue by despairblue** [synergy/synergy#4817]
System: arch linux

After running the wizzard (entering the account data) the ssl option is still disabled. How do I know that the wizard actually downloaded it?

Also when starting I get `crypto disabled because of ns plugin not available`.

**Comment by despairblue** [comment]
Also I'm running v1.7.4-stable-ebb7edf

**Comment by speaker** [comment]
@despairblue , As of 1.7.4, the plugin isn't downloaded anymore, it's installed into a public place. Check the /usr/lib/synergy directory and see if there is a plugins directory. A link should have been created from ~/.synergy/plugins/libns.so to /usr/bin/lib/synergy/plugins/libns.so (The path might look odd) as well. If the /usr/lib is missing than the plugin didn't install for some reason, if the link is missing but the plugin is in lib, thank the wizard didn't make the link.

Could you verify if any of these are missing?

**Comment by speaker** [comment]
If you wanted to check out the newest GM candidate, take a look at http://synergy-project.org/nightly?filter=v1.7.4-stable-267f3ac

**Comment by despairblue** [comment]
Do you mean `~/.config/Synergy`? Because the wizard does not create a `~/.synergy` folder. And the `~/.config/Synergy` folder does not contain a `plugins` folder.

**Comment by despairblue** [comment]
The new version does not print the error anymore. But the SSL option is still greyed out.

**Comment by despairblue** [comment]
Oh, wait, what? Are you sure you mean `/usr/bin/lib/synergy/plugins/libns.so`? Not `/usr/lib/synergy/libns.so`?

**Comment by despairblue** [comment]
Ok, the arch linux pkgbuild installed the file to `/usr/bin/lib/synergy/libns.so`. That's why it didn't work.
