### ISSUE TITLE
Assertion failed causes synergy to crash

### ISSUE THREAD

**Issue by meowfaceman** [synergy/synergy#4820]
I've got a Windows 7.1 server and a Linux client, both running Synergy 1.7.3

It seems that, if I idle for a while, and then attempt to mouse from my server to my client, Synergy crashes and I get the following error:

2015-06-22T22:48:43 DEBUG: open clipboard 1
        /build/synergy/src/synergy-1.7.3-stable/src/lib/platform/XWindowsClipboard.cpp,319
2015-06-22T22:48:44 DEBUG: ICCCM fill clipboard 1
        /build/synergy/src/synergy-1.7.3-stable/src/lib/platform/XWindowsClipboard.cpp,499
2015-06-22T22:48:44 DEBUG:   available targets: STRING (31)
        /build/synergy/src/synergy-1.7.3-stable/src/lib/platform/XWindowsClipboard.cpp,518
2015-06-22T22:48:44 INFO: entering screen
        /build/synergy/src/synergy-1.7.3-stable/src/lib/synergy/Screen.cpp,113
2015-06-22T22:48:45 INFO: leaving screen
        /build/synergy/src/synergy-1.7.3-stable/src/lib/synergy/Screen.cpp,131
synergyc: /build/synergy/src/synergy-1.7.3-stable/src/lib/platform/XWindowsClipboard.cpp:317: virtual bool XWindowsClipboard::open(IClipboard::Time) const: Assertion `!m_open' failed.
Aborted (core dumped)

**Comment by meowfaceman** [comment]
Nevermind -- looks like a dupe of 4749.

**Comment by speaker** [comment]
Dupe of #4749
