### ISSUE TITLE
Cannot copy specific Unicode character between computers

### ISSUE THREAD

**Issue by VeridianDynamics** [synergy/synergy#4824]
Hi,
I am unable to copy the shit (💩) character between two computers using clipboard. It always turns into the following symbol: �
It is worth noting that other interesting symbols such as snowman (☃) work fine.

The character is lost both from server to client and from client to server.

Using Synergy 1.7.3 on both ends. Both systems are Windows 8.1. I'm not using SSL connection.

**Comment by speaker** [comment]
@VeridianDynamics Well that stinks, sorry this isn't working properly. I strongly suspect that the 2 machines have a different idea what the "pile" symbol is in terms of a character and so although each can show it, the same literal sequence on the other is not a known symbol.

**Comment by VeridianDynamics** [comment]
Actually, this is not about emoticons, it's about the Unicode U+1F4A9 character ( http://www.fileformat.info/info/unicode/char/1F4A9/index.htm ). GitHub just changed the character to an image automatically for some reason :-/ . The symbol is exactly the same on both machines, but it is not transported over the network correctly.

**Comment by XinyuHou** [comment]
Duplicate to #4973
