### ISSUE TITLE
Copy/Paste causes crashes and loss of connection to server.

### ISSUE THREAD

**Issue by werebear73** [synergy/synergy#4829]
I am running Server on Ubuntu 15.04 as well as clients on Windows 7 and Mac Yosemite.  I am experiencing crashes on Mac from time to time when Copy/Paste and I loss connection from my WIndows 7 when Copy/Paste.  I can Stop/Start my Server and the connection to Windows 7 is re-established but on Mac the client has to be started.

**Comment by beporter** [comment]
Please check here to see if there is an existing thread open that describes your issue. If it's a duplicate, it's safe to close this one, which helps keep things manageable for the developers. Thanks!

https://github.com/synergy/synergy/issues/4735#issuecomment-108422245

**Comment by werebear73** [comment]
You are correct.  That does match.  I am sorry when I looked for issues it was filtering by one's created by me so I didn't see the existing issue.

**Comment by beporter** [comment]
No problem! Trust me, based on the number of duplicates in that other comment I linked to, it seems to be easy to miss. :+1:
