### ISSUE TITLE
Wix installer build fails to find 'synergy.exe'

### ISSUE THREAD

**Issue by jonpeachey** [synergy/synergy#4830]
When I run 'hm package win', I get the following error:

C:\Users\Jon\synergy-master\src\setup\win32\Product.wxs(110): error LGHT0103: The system cannot find the file '../../../bin/Release/synergy.exe'. [C:\Users\Jon\Downloads\synergy-master\src\setup\win32\synergy.wixproj]

I built it in VS2010 Pro with no errors, but 'synergy.exe' never shows up in the output folder.  It contains the following files:

integtests.exe
libeay32.dll
libeay32.lib
plugins
ssleay32.dll
ssleay32.lib
synergyc.exe
synergyd.exe
synergyp.exe
synergys.exe
syntool.exe
synwinhk.dll
synwinhk.exp
synwinhk.lib
unittests.exe
usynergy.exe

**Comment by nyetwurk** [comment]
You have to do "hm build" first.

**Comment by rockking1379** [comment]
im having the problem that even doing "hm build" wont build synergy.exe which is the GUI part of synergy. running into these errors
![ss 2015-07-02 at 02 43 01](https://cloud.githubusercontent.com/assets/4431119/8487342/b2019668-20c8-11e5-8d0f-5a36d86aacec.png)
i tried to trick it into thinking uic.exe was in that location but still didnt work

**Comment by nbolton** [comment]
Please use mailing list to discuss build problems.
https://groups.google.com/forum/#!forum/synergy-dev
