### ISSUE TITLE
Error leaving screen 2, back to screen 1 which is UHD

### ISSUE THREAD

**Issue by nixxle** [synergy/synergy#4833]
My setup:
-- SERVER ---
PC 1 SCREEN 1 : HD
PC 1 SCREEN 2 : UHD
-- CLIENT ---
MAC SCREEN 1 : HD

Now if I go to the client, I'm having trouble getting the mouse back to the server. It shows up for a millisecond, but snaps right back to the client. I think the margin is to narrow and the resolution of the UHD too high? 

I've solved it by swapping the position of the servers monitors. Like physically swap them on my desk.

**Comment by nbolton** [comment]
This looks like a configuration issue. Please use the forum to troubleshoot the issue.
http://synergy-project.org/forum/

**Comment by mdmojo** [comment]
This has to do with windows scaling the size of text and other items.
I found that if i return the slides to 100% the issue goes away.
