### ISSUE TITLE
Server to Client Transitions on Multi-Monitor configuration 

### ISSUE THREAD

**Issue by hidden72** [synergy/synergy#4838]
I read through the "multi-monitor" and "portrait" bugs and didn't find one that exactly matches my situation.  

A picture is worth a thousand words for this one.  (Forgive the awesome MS Paint drawing)

![capture](https://cloud.githubusercontent.com/assets/976913/8502430/1034d7d2-216d-11e5-855f-f6ac84063ed0.PNG)

Essentially I have a Windows 7x64 synergy server with two monitors.  One in landscape, and another in portrait.  I also have an MS Surface Pro 3 synergy client sitting below the server.

Broken:  transition from screen 2 to surface (red line)

Working: transition from surface to screen 2 (blue lines)
Working: transition from surface to screen 1 (blue lines)
Working: transition from screen 1 to surface (blue lines)

If I transition from the upper-left screen edge on the surface to the synergy server, I land on screen 2.  If I transition from the upper-right screen edge on the surface to the synergy server, I land on screen 1.  So client to server transitions are working perfectly.

However, on transitioning from server to client, if I leave the bottom-left corner of screen 1, I land on the top left corner of the surface (as if screen 2 doesn't exist at all).  

This was an issue with 1.7.3, and I also tried one of the current 1.7.4 builds from this week and am still having problems.

**Comment by beporter** [comment]
Possibly related: #3744

**Comment by nbolton** [comment]
Duplicates https://github.com/synergy/synergy/issues/3744
