### ISSUE TITLE
show indication in menu bar / system tray icon as to current status

### ISSUE THREAD

**Issue by glyph** [synergy/synergy#4839]
I'd like to glance at my menu bar and know (on server machines) if clients are connected, and (on client machines) if a connection to a server has succeeded.  Having this indication on the menu bar would be handy so that I don't need to click it and stare at logs to see if the connection succeeded.

(I'm on OS X, so apologies if this behavior exists on other platforms…)

**Comment by nbolton** [comment]
Duplicates #4791
