### ISSUE TITLE
Window focus flickers on server when moving mouse on client

### ISSUE THREAD

**Issue by glyph** [synergy/synergy#4842]
When I use Synergy to control a client's display, if I have a window open on the server in the middle of the screen sensitive to mouse movement events (like, for example, Github's issue list), I can see flickering as the mouse apparently moves and is re-set repeatedly.  Can Synergy perhaps open a hidden window or something to block those movement events from disturbing applications on the server?

**Comment by nbolton** [comment]
@glyph 
What OS is the server and client?

**Comment by nbolton** [comment]
Duplicates https://github.com/synergy/synergy/issues/4849

**Comment by glyph** [comment]
Both server and client are OS X.

**Comment by glyph** [comment]
10.10.4 in both cases.
