### ISSUE TITLE
Typos in the website

### ISSUE THREAD

**Issue by mdmksrbn** [synergy/synergy#4848]
Not sure if this is the right place, as it concerns the website and not the software.
Is there a way to edit the English language as in getlocalization for foreign languages ?

The string "Thanks! Your friend has been sent the referral link. When they purchase Synergy, you'll get $%s." presents a typo.
The subject of the first sentence is singular, and the one in the second is plural : "Your" first and then "They".
One of them should be corrected.

In the string "Sorry, it looks like this activation link is no longer valid. For security, an activation link can only be used once, and must be used within 1 week of being sent. If you think there may be aproblem, please check the <a href="%s">forum</a>."
There should be a space in "aproblem"

**Comment by nbolton** [comment]
Thanks! I've raised these bugs on our internal tracker for the website.
