### ISSUE TITLE
Upgrade shows 'you can close config window' after deleting registry key 

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4850]
1. Remove Synergy registry keys under HKEY_CURRENT_USER
2. Upgrade to a new version of Synergy
3. See wizard but also hint dialog in background

The connection can't possibly be established, since nothing is configured yet.

![image](https://cloud.githubusercontent.com/assets/313427/8559799/2391f3f8-24c6-11e5-8203-21d088b5e4b6.png)

**Comment by XinyuHou** [comment]
@nbolton 
Did you remove the last run command registry key?

**Comment by XinyuHou** [comment]
Fixed by 79bb43718d069fc4419ef4ae7c9eef37feac06da
