### ISSUE TITLE
Remove warning dialog for SSL feature

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4853]
Please remove this dialog...

![screen shot 2015-07-07 at 4 48 25 pm](https://cloud.githubusercontent.com/assets/313427/8559985/08ed4b40-24c8-11e5-9991-f0f3290fa872.png)

**Comment by XinyuHou** [comment]
Fixed by fcdcaeff3abd3425b7fb02e6eca91653e6b1c341
