### ISSUE TITLE
Fingerprint does not display on GUI after initial setup

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4854]
![image](https://cloud.githubusercontent.com/assets/313427/8560010/508d540e-24c8-11e5-982d-b1b336dd50c1.png)

**Comment by XinyuHou** [comment]
@nbolton 
Fresh install? Any error during plugin download?

**Comment by nbolton** [comment]
Fresh install, no errors.

**Comment by nbolton** [comment]
Can't reproduce any more.
