### ISSUE TITLE
hm conf command gives 'Project MESSAGE: Warning: unknown QT: widgets' error

### ISSUE THREAD

**Issue by joncooke** [synergy/synergy#4860]
**Synergy:** v1.7.4-stable
**System:** Windows 7 64bit
**QT:** Qt SDK 2010.02
**Cmake:** 3.3.0-rc3
**Python:** 2.7.10
**Visual Studio:** VS 2012 Express

I added the cmake generators for VS 2012 but apart from that no changes have been made to downloaded code.

**Command line result:**
> C:\softdev\synergy-master>hm conf -g1
> Mapping command: conf -> configure
> cmake version 3.3.0-rc3

> CMake suite maintained and supported by Kitware (kitware.com/cmake).
> Entering dir: build
> CMake command: cmake -G "Visual Studio 11" ..
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/softdev/synergy-master/build
> Going back to: C:\softdev\synergy-master
> QMake command: qmake gui.pro -r
> Entering dir: src/gui
> Project MESSAGE: Warning: unknown QT: widgets
> Project MESSAGE: Warning: unknown QT: widgets
> Project MESSAGE: Warning: unknown QT: widgets
> Going back to: C:\softdev\synergy-master

**Comment by sanyer** [comment]
It's just a warning, not an error. The Qt build will still be successful.
It is written, because Qt 5 component _widgets_ is defined in src\gui\gui.pro file.

**Comment by joncooke** [comment]
Ah ok sorry, thanks for letting me know :)
