### ISSUE TITLE
Quotation marks and double quotation marks stopped being sent to secondary computer on windows

### ISSUE THREAD

**Issue by xrv** [synergy/synergy#4861]
Using US international keyboard so I can use "é", "í", "ñ", etc, in both primary and secondary computers.

It worked in soynergy until this stopped working. Do not remember any synergy update in that date.

' and " characters just are ignored on secondary screen.

**Comment by XinyuHou** [comment]
Duplicates https://github.com/synergy/synergy/issues/4280
