### ISSUE TITLE
Pressing Tab key while entering time in A to Z Project manager crashes app

### ISSUE THREAD

**Issue by jmoore-accelerant** [synergy/synergy#4868]
A to Z Project Billing (http://www.lgwsoftware.com/) is my project time tracking/invoicing tool I use daily.

When I'm entering a new time entry, and press the Tab key in the Description field, the app crashes when Synergy is running. If I stop Synergy then pressing the Tab key does not crash the app.

I'm running Windows 7 on both server and client machine. The A to Z Project Billing app is running on the server machine.

**Comment by XinyuHou** [comment]
This is a third part compatibility issue. Nothing much we can do.
