### ISSUE TITLE
No option to log in with Synergy-Project pro account OSX latest nightly.

### ISSUE THREAD

**Issue by chamunks** [synergy/synergy#4869]
# Synergy registration issue
I'm trying to make my Macbook register that I've donated for Synergy.  I cannot seem to make the login screen come up again on my laptop yet its registered just fine on my iMac desktop.  I'm running a nightly build of version 1.7.4 downloaded on the date of this ticket posting.
![Both computers on the same version](http://i.imgur.com/PgybQBf.png)

## The problem
![unregistered MacbookPro](http://i.imgur.com/EmpKVcj.png)
Despite my attempts to locate a register button which allows me to make synergy stop having the `Synergy (UNREGISTERED)` bit across the top.  I can't seem to make my MacbookPro re-offer me the login screen.  Which should result in a screen looking more like this.
![Registered iMac](http://i.imgur.com/KUlQB8A.png)

## What I've tried to do to attempt a fix on my own.
Not entirely sure why I can't re-trigger the login screen. I've uninstalled synergy completely from the MacbookPro and I've even tried running the following command to clear any potential latent settings:  

    rm $(find ~/Library -iname *synergy* -type f -print|grep '.plist')
In an attempt to try and remove all traces of synergy settings from the MacMookPro in hopes to re-trigger the magic moment which unlocks the login screen for synergy.

**Comment by XinyuHou** [comment]
You can rerun wizard to login.

**Comment by chamunks** [comment]
... I never would have looked for that in the file menu...
