### ISSUE TITLE
Mac Server stops unintentionally

### ISSUE THREAD

**Issue by tarres** [synergy/synergy#4870]
From time to time the Synergy (1.7.3) Server on my Mac (10.10.4) the server just stops with error

ERROR: ssl error occurred (sys
INFO: leaving screen
tem call failure)

This is the acutal order of the lines in the logfile.

I can't reproduce it directly, but most of the times it happens shortly after server or client or both were in sleep mode.
It happens around 2 times a day.

**Comment by XinyuHou** [comment]
Duplicates https://github.com/synergy/synergy/issues/4558
