### ISSUE TITLE
System tray unavailable. Quitting.

### ISSUE THREAD

**Issue by Bazzek** [synergy/synergy#4873]
My systems:
Server
*Fedora 22 64 bit
*KDE Plasma 5
*multi monitor through nvidia driver
*Downgraded from 1.7.3 to 1.7.1 due to stability issues
*Running 1.7.3 again for testing

Client
*KUbuntu 15.04 64 bit
*Plasma 5 KDE
*Single monitor
*Downgraded from 1.7.3 to 1.7.1 due to stability issues

When i autostart Synergy client on my client AND server i get the message "System tray unavailable. Quitting."
When i then start the client again (manually obviously) it does start and it produces an icon in the system tray.

**Comment by XinyuHou** [comment]
Duplicates https://github.com/synergy/synergy/issues/2987
