### ISSUE TITLE
1.7.3 - Using wrong server connect IP with e.g. Virtualbox Networks on server side

### ISSUE THREAD

**Issue by Reiner030** [synergy/synergy#4874]
Hello,

client is detected on server side (via Bonjour?) with correct IP but gets offered the wrong IP (the one from Virtualbox is set as default [bold] in my setup by Synergy) after first successfull connect... which must always fail (client: Win 8.1, server: Win 7).

**Comment by XinyuHou** [comment]
Duplicates https://github.com/synergy/synergy/issues/4251
