### ISSUE TITLE
Synergy doesn't ask to verify changed/invalid

### ISSUE THREAD

**Issue by srl295** [synergy/synergy#4878]
In the logs:

`ERROR: failed to verify server certificate fingerprint`

I'd expect synergy to *ask* me if I can confirm the fingerprint, but it doesn't.  Probably the IP address just changed.

OSX 10.10.4, synergy 1.7.3

**Comment by XinyuHou** [comment]
Duplicates https://github.com/synergy/synergy/issues/4737

**Comment by srl295** [comment]
@XinyuHou Thanks! Glad to see it's being fixed. I did try to search for dups, but missed that one.
