### ISSUE TITLE
OSX Client v1.7.3: Resizing a window to the RHS edge of screen causes Synergy to Stop.

### ISSUE THREAD

**Issue by tohagan** [synergy/synergy#4884]
I'm running Synergy v1.7.3 on OSX as client and matching version on Windows running Synergy Server.

When I resize a window using the mouse to the RHS edge of OSX screen (where the mouse should cross over to my Windows computer) causes Synergy to Stop. I now have to plugin a mouse to OSX host to restart Synergy.

**Comment by XinyuHou** [comment]
Duplicates https://github.com/synergy/synergy/issues/4342
