### ISSUE TITLE
synergyd.exe consumes 25% CPU always

### ISSUE THREAD

**Issue by jooncheol** [synergy/synergy#4887]
I've installed synergy-v1.7.3-stable-efd0108-Windows-x64.msi yesterday.
After use synergy as client mode, my laptop's fan worked busy due to this maybe.

![synergyd](https://cloud.githubusercontent.com/assets/1052343/8817996/e57b1296-3075-11e5-8a5a-51144085a737.png)

**Comment by badger200** [comment]
I am experiencing the same issue using 1.7.3 on a Windows XP server connecting to a Mac OS X 10.9 client screen (also running 1.7.3). However I have noticed something strange - if I open Synergy from the Start Menu, it instantly causes synergyd.exe CPU to drop from 100% (or 25% on a 4 core system...). So as long as I leave Synergy UI open for no particular reason, it will work around this bug.

**Comment by douglascaetano** [comment]
I am experiencing the same. Synergy daemon uses 100% of one core all the time, except if the configuration is opened. When closed, the daemon uses all of one core again after mouse runs to another computer.

**Comment by XinyuHou** [comment]
Duplicates #4721
