### ISSUE TITLE
Occasional crash

### ISSUE THREAD

**Issue by Maeyanie** [synergy/synergy#4888]
It doesn't happen very often, but I managed to catch what triggered a random crash I'd been having.

````
==28719== Process terminating with default action of signal 11 (SIGSEGV)
==28719==  Access not within mapped region at address 0x10
==28719==    at 0x4F8489: ServerProxy::onClipboardChanged(unsigned char, IClipboard const*) (ServerProxy.cpp:364)
==28719==    by 0x4F4C4E: Client::sendClipboard(unsigned char) (Client.cpp:419)
==28719==    by 0x4F67D2: Client::sendClipboardThread(void*) (Client.cpp:775)
==28719==    by 0x4F719F: TMethodJob<Client>::run() (TMethodJob.h:66)
==28719==    by 0x54E0DC: Thread::threadFunc(void*) (Thread.cpp:157)
==28719==    by 0x4C3309: ArchMultithreadPosix::doThreadFunc(ArchThreadImpl*) (ArchMultithreadPosix.cpp:726)
==28719==    by 0x4C3270: ArchMultithreadPosix::threadFunc(void*) (ArchMultithreadPosix.cpp:707)
==28719==    by 0x3C1D807554: start_thread (in /usr/lib64/libpthread-2.21.so)
==28719==    by 0x3C1D501F3C: clone (in /usr/lib64/libc-2.21.so)
````
From what gdb tells me, it looks like somehow the Client::m_server field is null, which means "this" in onClipboardChanged is null, which results in a crash.

The odd thing is, there is an assert(m_server != NULL) at the top of Client::sendClipboard, which would indicate a race condition somewhere. There's a note at the top of it that "m_mutex must be locked on entry" but I couldn't find where that lock was happening, so perhaps that's the cause, or perhaps I'm just missing it.

Anyhow, I'm nowhere near familiar enough with this code to figure it out myself, so just posting this here and hopefully some of this rambling helps you guys.

**Comment by Maeyanie** [comment]
On further testing, I'm not sure it's a race condition. It also looks like it might be getting disconnected from the server during that function call, but the function continuing regardless.

**Comment by nyetwurk** [comment]
Also seeing a crash, likely this, but have not had gdb connected to verify it is the same one.

**Comment by XinyuHou** [comment]
Duplicates #4735
