### ISSUE TITLE
Unrecognized log level 'NOTIFY'

### ISSUE THREAD

**Issue by sthor69** [synergy/synergy#4889]
Client 1.7.4 on WindowsXP
Server 1.7.4 on Linux Ubuntu 14.04.1

If I set the log level to 'NOTIFY' the application stop working with the following log

INFO: ignoring --enable-drag-drop, not supported below vista.
INFO: service command updated
INFO: got ipc shutdown message

INFO: leaving screen

INFO: stopped client

INFO: process 6036 was shutdown gracefully
INFO: starting new process
INFO: activeDesktop:Default

INFO: starting new process
INFO: ignoring --enable-drag-drop, not supported below vista.

synergyc.exe: unrecognized log level `NOTIFY'
Try `synergyc.exe --help' for more information.

ERROR: failed to launch, error: process immediately stopped
INFO: backing off, wait=2s, failures=1
INFO: starting new process
INFO: activeDesktop:Default

INFO: starting new process
INFO: ignoring --enable-drag-drop, not supported below vista.

synergyc.exe: unrecognized log level `NOTIFY'
Try `synergyc.exe --help' for more information.

ERROR: failed to launch, error: process immediately stopped
INFO: backing off, wait=4s, failures=2
INFO: starting new process
INFO: activeDesktop:Default

**Comment by XinyuHou** [comment]
This feature has been reverted. This issue is not valid any more.
