### ISSUE TITLE
Apostrophe ("shift+\") does not work on Czech keyboard

### ISSUE THREAD

**Issue by thiemel** [synergy/synergy#4891]
Hi,
server - Windows 7 with Czech keyboard
client - Linux

With Czech keyboard when I try to type apostrophe "'" on client ("shift+\" key on US), I got wrong character. When I use US keyboard, everything works fine. Apostrophe on Czech keyboard is mapped under "|" ("shift+\" key). If I hit the key 2x, I get "̛".

The problem is since I've started using Synergy ~3 years ago.

**Comment by thiemel** [comment]
Also found other keyboard related issues:
US: /1/2/3/4/5/6/7/8/9/0/+d/+t/+n/[/;/= /+ /=a/=e/=i/=o/=u/=n/+s/+c/+r/+z/
CZ: /+/ě/š/č/ř/ž/ý/á/í/é/ď/ť/ň/ú/ů/´/ˇ/á/é/í/ó/ú/ń/š/č/ř/ž/
client: /+/ì/š/è/ø/ž/ý/á/í/é/ï//ò/ú/ù/'//á/é/í/ó/ú/ñ/š/è/ø/ž/

**Comment by XinyuHou** [comment]
Duplicates https://github.com/synergy/synergy/issues/4280

**Comment by Brambor** [comment]
The duplicate doesn't exist...
