### ISSUE TITLE
Show detailed version info on GUI about screen

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4893]
Problem: During testing, we often have no idea which *exact* version we have installed.

Solution: Include the **stage name**, **git revision** and **build date** in the about dialog as part of the build process (pass it to cmake from hm?)

**Comment by mfilipe** [comment]
This is going to be awesome! Today I had this problem because I didn't know if the software was 1.7.4-rc7 or 1.7.4-rc8. 

I suggest you implement this getting the information what you need one step before you start to compile. It is going to give you more freedom to automate this step in another ways.

**Comment by nbolton** [comment]
@XinyuHou Please port fe63124ed49a3becaa23b35a8aa94315c2f05205 to 1.8 and add the **build date**.

**Comment by Kays** [comment]
Looks good.

OS: Debian Jessie (8.5)
![2016-07-01-20 33 35_602x331](https://cloud.githubusercontent.com/assets/505500/16537215/21648ec6-3fcb-11e6-8430-d3741181357a.png)

OS: Windows 7
![tal2wxe](https://cloud.githubusercontent.com/assets/505500/16537246/b85587b8-3fcb-11e6-91b1-d3fe5b5ee505.png)

**Comment by Verequies** [comment]
Can confirm the information shows up on Windows 10 Enterprise 64-bit.
![issue 4893 test](https://cloud.githubusercontent.com/assets/282071/16537647/b041bba2-404b-11e6-85ca-328067fe2284.png)

**Comment by mohibsheth** [comment]
Confirmed on OSX El Capitan 10.11.5
![screenshot 2016-07-02 11 52 24](https://cloud.githubusercontent.com/assets/1132497/16538776/bcdf6f3a-404b-11e6-8d2c-2dbed17c7c67.png)

**Comment by yidhoe** [comment]
![image](https://cloud.githubusercontent.com/assets/2747150/16540430/374387e2-405c-11e6-8769-ecc8020c19bd.png)

**Comment by Zygislovas** [comment]
Looks good...
**System information:**
Windows 10 Enterprise x64
Windows 8.1 Pro x64
![image](https://cloud.githubusercontent.com/assets/20255330/16540470/9dd94368-406e-11e6-8b83-6e93bca86e92.png)

**Comment by ryanvito** [comment]
Agree with those above. Looks great on both of my macs 10.10 and 10.11.5. Well done.

**Comment by cletsimon** [comment]
looks good in osx 10.10.5
![screen shot 2016-07-03 at 7 01 27 pm](https://cloud.githubusercontent.com/assets/5573468/16545075/c1c9d476-4150-11e6-82fb-e074cee85dcd.png)

**Comment by MyXelf** [comment]
I would suggest to change the GUI component used to display this information to one with the ability to select and copy the text. This would make it easier to include this information in the reports, speeding up the whole process of bug reporting with people using different OSes and trying to get the info from different places.

The killer-enhacement would be a button to copy the info directly to the clipboard. ;-)

HTH

**Comment by mohibsheth** [comment]
I agree with MyXelf's suggestion. Further more, this would allow you to configure the reports in the exact format which you require it and you could bundle additional details/logs etc if you need.

**Comment by ChrisEdgington** [comment]
Looks to me like Build Date is not getting set properly. I downloaded the 1.8.1-beta-f7377d6 build, OSX 10.11 x64, and its Build Date says: Wed Jul 6 2016, which is today.

**Comment by BoStaahle** [comment]
Works on Win10 x64 and OSX 10.11 x64 for as well ...
![image](https://cloud.githubusercontent.com/assets/2256870/16679986/0f934158-44ec-11e6-951f-ac9d45dee5a1.png)
![image](https://cloud.githubusercontent.com/assets/2256870/16680061/86aa21da-44ec-11e6-97ca-8308d5c55bf7.png)

**Comment by mohibsheth** [comment]
Nice catch @ChrisEdgington !

**Comment by BoStaahle** [comment]
So Build Date field is in fact install date ?

**Comment by mohibsheth** [comment]
@BoStaahle No, I think it should actually be the date on which the build was prepared/release but it's not being populated correctly due to some bug and shows Today's date instead.

**Comment by BoStaahle** [comment]
@mohibsheth that is not what I meant. I meant that the date actually shown now could be the install date - which is not be the correct date to show.

**Comment by jesterKing** [comment]
@BoStaahle no, it shows Today's date. I installed already at the begin of this week, but today it shows Friday 8th as bulid date.
