### ISSUE TITLE
Synergy 1.7.4 - Ubuntu Crash Report

### ISSUE THREAD

**Issue by crazyben21** [synergy/synergy#4897]
Hello,

When I add "greeter-setup-script=/usr/bin/synergyc -n Left1 IP_ADDRESS" to the 50-ubuntu.conf file and reboot for the first time, it works great without any Ubuntu crash reports. But, when I reboot a second time, synergyc works but Ubuntu generate a crash report stating "system program problem detected". When I send the report it states "The application Synergy has closed unexpectedly".

I'm using Ubuntu 14.04 and Synergy 1.7.4 on both my Windows 7 server and Linux client.

What I'm suspecting is that synergyc is not closing properly when the computer reboots/shutdown.

Maybe this is not a bug or maybe is the way I'm starting sysnergyc. What do I need to do so I could close it properly before I reboot or shutdown?

Thank You,
Ben

**Comment by XinyuHou** [comment]
Sorry, I have to close this issue because I can identify it as a specific bug. Please send us some log or error code, so we can reopen this issue.

**Comment by crazyben21** [comment]
Sorry I had trouble finding a place to attach the log file so I post a Dropbox link to it.

https://www.dropbox.com/s/ym6y7gvwy6heg2o/_usr_bin_synergyc.0.crash?dl=0

Thank You,
Ben
