### ISSUE TITLE
Auto restart when running from GUI in desktop mode

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4901]
Problem: The core processes (synergys/synergyd) crash from time to time, its unavoidable. When it's the client, this is especially annoying since users need to plug in a mouse and keyboard and click the 'Start' button.

Solution: Implement a simple watchdog mechanism which restarts the server or client when it stops (and should be started).

**Comment by nbolton** [comment]
@the-wes @XinyuHou Not solved, causes multiple instances to start on Linux.

**Comment by Swaagie** [comment]
I'm seeing a lot of references to this issue from multiple issues involving reconnect logic and `ssl error occured (ssytem call failure)`. I'm not sure but I got two mac's both with 10.10.5 and the easiest way to reproduce this is simply restarting the server (autoconfig). The client (autoconfig) will never reconnect and throw the SSL error alongside with `ERROR: eof violates ssl protocol`. I'm not sure restarting deamons alone is enough, will this ensure reconnection?

**Comment by spronkey** [comment]
+1 to @Swaagie seeing this same error lately. Basically occurs every 30 seconds, has completely broken my setup.

**Comment by sruffell** [comment]
+1 to @Swaagie as well. I restart my server and the client never reconnects.
