### ISSUE TITLE
synergyd high CPU usage

### ISSUE THREAD

**Issue by jjjordan** [synergy/synergy#4903]
synergyd pegs one core of my Lenovo Yoga running Windows 8.1 Enterprise.  This happens with 1.7.3 pro, both 32 and 64 bit versions.  I haven't tried older versions.

This only reproduces when synergyd was not started from the frontend application.  For instance when the machine boots and the service auto-starts, it will exhibit this behavior.  If I stop the service and start it through the UI frontend, then it will use a sane amount of CPU.  If I close the frontend, then the CPU spikes back up.  This is especially a problem for my laptop as it quickly eats away at the battery.

**Comment by jjjordan** [comment]
I should have noted I'm using it as a client in this case.

**Comment by the-wes** [comment]
this is fixed in 1.7.4. http://synergy-project.org/nightly?filter=1.7.4
