### ISSUE TITLE
Relative mouse moves setting forgotten after Mac returns from sleep

### ISSUE THREAD

**Issue by Cheesebaron** [synergy/synergy#4904]
Server: OSX 10.10.4
Client: Windows 8.1

Reproduction steps:

1. Enable relative mouse moves on server and apply
2. Make the server sleep, I.e. triggered by hot corner in OSX
3. Wake the server from sleep
4. When the client connects, relative mouse moves is still enabled in the config, but not enforced and mouse speed is different on client.

This can be worked around by pressing the Apply button on the server and the setting is enforced again.

**Comment by XinyuHou** [comment]
Duplicates #451

**Comment by Cheesebaron** [comment]
That issue is closed. Consider reopening it then.
