### ISSUE TITLE
Wrong AltGr mapping.

### ISSUE THREAD

**Issue by djmentos** [synergy/synergy#4905]
Hi,

it is something wrong with AltGr key mapping, I have Synergy 1.7.3.

Server @ MS Windows 8
Client @ Ubuntu 14.04

When I am clicking on Windows AltGr key it is mapped to Right-Alt key, but when I do it under Ubuntu it is mapped to Left-Ctrl. 

When I try it directly under Ubuntu, without Synergy - it works properly.

Both systems have the same keybord layout - Polish (programmers), qwerty.
![win-kbd](https://cloud.githubusercontent.com/assets/11178791/8982701/0e37e912-36c4-11e5-89aa-8d8c2d7b5716.png)
![ubu-kbd](https://cloud.githubusercontent.com/assets/11178791/8982991/8ac9beea-36c6-11e5-8b10-c3d00288fb0f.png)

Configuration is default:
![config](https://cloud.githubusercontent.com/assets/11178791/8983022/d7f884f8-36c6-11e5-8fe7-e8c4791d60ef.png)

**Comment by XinyuHou** [comment]
Duplicates #4280
