### ISSUE TITLE
Wrong punctuation keystrokes sent to a Mac client

### ISSUE THREAD

**Issue by battlmonstr** [synergy/synergy#4912]
Typing a punctuation symbol on a client produces a wrong symbol.
The following keys are affected:
(expected characters without Shift)
```
`[]\;',.
```
When I type any of those characters (with or without Shift), it produces a different symbol than expected. If I type those characters in the same sequence as above, this is produced:
(actual characters without Shift)
```
0``78967
```
The same problem happens with Shift.
Expected characters with Shift:
```
~{}|:"<>
```
Actual characters with Shift:
```
M()!%@±±
```

Configuration:
Server: v1.7.4 on Linux Debian Stretch 64bit, or Windows 7 64bit. A desktop PC.
Client: v1.7.4 on Mac OS X Yosemite 10.10.3. A MacBook Pro.
App: any Mac app (Terminal, TextEdit)
Keyboard: Dell US keyboard, PC104 type.
Client locale: en_US.UTF-8
Server locale: en_US.UTF-8

Notes:
* a dot (.) works if typed on the numpad
* slash and question mark (/?) work fine

**Comment by battlmonstr** [comment]
In addition a percent sign doesn't work, which is Shift+5 - '%'.
Synergy produces a dollar sign - '$' - instead.

**Comment by XinyuHou** [comment]
Duplicates  #4280
