### ISSUE TITLE
Crash or hang with Linux + Windows, likely clipbuffer related.

### ISSUE THREAD

**Issue by DALDEI** [synergy/synergy#4916]
WIndows 7 Pro ,  Centos 6.5  - either way client or server.
THis started with the 1.7x builds and continues.  Synergy will not stay running longer then a few minutes.   Debugging this lead to the current pull request, but that only stops a crash in debug mode.
There is still a crash.  It happens shortly after an event on the linux side saying something like Unrecognized Event size: xxxxxxxx where size is  many MB large.
This seems to happen right after a clipboard event or maybe the clipboard event itself.
Within a few seconds synergy is hung or crashed.

**Comment by jtexp** [comment]
See https://github.com/synergy/synergy/issues/4735

**Comment by XinyuHou** [comment]
Duplicates #4735
