### ISSUE TITLE
High processor usage in Windows 10

### ISSUE THREAD

**Issue by krisdante** [synergy/synergy#4926]
I am running Synergy as Client on Windows 10 machine.
It is not the newest piece of hardware - i5 Processor ~2GHz.

Synergyd is constantly using about 45% of CPU which is bit high price to pay for possibility to use mouse from other computer ;)

Can this be somehow improved?

**Comment by YellowAfterlife** [comment]
I'm seeing similar issue - on startup synergyd proceeds to hog a single CPU core. Stopping and restarting Synergy via GUI fixes the problem. This happened both on Windows 8.1 and now Windows 10.

**Comment by krisdante** [comment]
Hah you are right. The trick with restart with GUI works.

**Comment by hidden72** [comment]
+1 I'm seeing the same high CPU utilization on initial startup, and yes the GUI restart quiets everything down.  Windows10x64.

**Comment by YellowAfterlife** [comment]
Looking through the issue list, this might be fixed in 1.7.4 as per https://github.com/synergy/synergy/issues/4721
A beta rolled out today.

**Comment by nbolton** [comment]
@YellowAfterlife We did plan to make it live today, but we hit a couple of snags. Are you on the beta testing list? If not, give this a try: http://synergy-project.org/nightly?filter=v1.7.4-rc7-e3e97cb

**Comment by YellowAfterlife** [comment]
@nbolton Yes, I've been looking through the list of affected issues after receiving a beta email-notification. Will check it later today.

**Comment by dpgt** [comment]
Problem with high cpu usage in client mode. Synergy is using about 25-30% of my CPU. It makes no difference if I open the GUI. Stopping and starting from the GUI also does nothing.
Server: Windows 10
Client: Windows 7
Synergy version: 1.7.4

**Comment by XinyuHou** [comment]
Fixed in 1.7.4
