### ISSUE TITLE
GUI "Synergy is starting" - after it is already started

### ISSUE THREAD

**Issue by Silarn** [synergy/synergy#4927]
On the more recent 1.7.4 RC builds - notably RC5 and RC6 - I've noticed that the GUI still indicates 'Synergy is starting.' after starting the client/server even after the client/server are connected and working just fine.

I've tried this with both custom built RPM packages on Fedora 22/23 as well as the prebuilts, and also the Windows version.

**Comment by Silarn** [comment]
Well, as of RC6 I was also having the fingerprint verification bug and set the log level to Debug2 as a previous known fix and lo and behold now the clients are properly indicating 'Synergy is running.'

**Comment by XinyuHou** [comment]
Duplicate to #4955
