### ISSUE TITLE
Problem with Runescape and synergy

### ISSUE THREAD

**Issue by brendenhoffman** [synergy/synergy#4928]
I've already contacted the Runescape developers about this, but in game there is not mouse-over text or right click options like there is supposed to. I've cleaned my runescape client and java caches  and the problem still persists. It stops as soon as Synergy is disconnected.

**Comment by XinyuHou** [comment]
@brendenhoffman 
Please give us more details about this issue. 

Here is a guild for raising an issue. https://github.com/synergy/synergy/wiki/Issues

This issue will be closed until we have more information.
