### ISSUE TITLE
Synergy 1.7.3 stops working after upgrade from Win 7 to Win 10

### ISSUE THREAD

**Issue by iayalamx** [synergy/synergy#4931]
After upgrading from Win 7 to Win 10, the Synergy app now comes up titled "Synergy (UNREGISTERED)" instead of "Synergy Pro".
Starting the server produces these messages in the log:
NOTE: connecting to service...
NOTE: connection established
NOTE: starting server
NOTE: config file: C:/Users/XXxx/AppData/Local/Temp/qt_temp.gq6740
NOTE: log level: NOTE
activeDesktop:Default
ERROR: could not get session id for process id 8472
NOTE: started server, waiting for clients
NOTE: accepted client connection
NOTE: client "XxxxXxxx" has connected
The client (Win 7, 1.7.3) shows no errors in the log, and even states "entering screen".
The mouse leaves the server, but on the client it only moves towards the lower right corner.
Once in the client, the mouse doesn't return to the server until the client is shut down.
What can I do to fix?
Thanks

**Comment by RSStephens** [comment]
I am seeing the same exact problem after upgrading to Windows 10 except with Synergy basic.  I can't use Synergy anymore.

Thanks,

**Comment by RSStephens** [comment]
I was able to get Synergy working again by switching the size for text in display options, from 125% to 100%.  The funny thing is after upgrading to Windows 10 it showed it as 100% but it was actually set to 125%, so when I first checked the setting it was showing incorrectly.  After switching it to 125% then back to 100% Snyergy started working again.  The setting can be found by going into Settings->System->Display->Change the size of text, apps, and other items.  Hope this helps.

**Comment by yatahaze** [comment]
I can confirm the same behavior here (using v1.7.4-rc8-c734bab-Windows-x64). On the host computer (running win10), when I move to another computer (running 7/8/10), the mouse shoots across the screen then disappears and gets locked there. I have to hit ctrl-alt-del and cancel to recover my mouse cursor. 

If I turn the text scaling on the host to 100% this problem goes away. The text scaling doesn't matter on the client side, only the host system. My clients have various text scaling sizes and none of it has an effect,

**Comment by qdot** [comment]
The temporary fix in https://github.com/synergy/synergy/issues/4041 works for me on windows 10.

**Comment by RSStephens** [comment]
That fix works for me.  I am now able to set the text size to 125% without issue.  Thanks.

**Comment by iayalamx** [comment]
Thanks for all the help. I Set the scaling back to %100, since the win10 upgrade did that on its own, apparently. I don't need the scaling, so I'm all set.

**Comment by XinyuHou** [comment]
Duplicate to #5030
