### ISSUE TITLE
Notify activation system when wizard finishes

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4932]
Depends on: #4715

Problem: We have no idea how many users see the 'UNREGISTERED' message in the title bar.

Solution: Notify the activation system when the activation wizard is skipped (as well as notifying when using a serial key or user account and password).

**Comment by legonigel** [comment]
As a privacy advocate, I think users should have the option to not allow the software to report, you could do like most other software does and make it **Recommended** that users do leave the option on.
