### ISSUE TITLE
double/single quote key is not working on client system

### ISSUE THREAD

**Issue by alexpanrui** [synergy/synergy#4939]
I am using windows 10 as server, and OS X 10.11 Beta (15A244d) as client, synergy version 1.7.3.

Connected through non-SSL.

On client, unable to type in double/single quote

**Comment by alexpanrui** [comment]
Log shows `key 0027 not on this keyboard`

**Comment by reinder** [comment]
Do you use a keyboard layout with dead keys?

**Comment by alexpanrui** [comment]
How do I tell whether my keyboard has dead keys or not? Thank you.
On Wed, Aug 12, 2015 at 2:28 AM, Reinder Feenstra <notifications@github.com>
wrote:

> Do you use a keyboard layout with dead keys?
>
> —
> Reply to this email directly or view it on GitHub
> <https://contactmonkey.com/api/v1/tracker?cm_session=acaea411-01fb-4002-9c81-028fcd6e5562&cm_type=link&cm_link=ae19364f-294c-4afc-a23a-a32038350dd6&cm_destination=https://github.com/synergy/synergy/issues/4939#issuecomment-130004668>
> .
>



-- 
Rgds,
Pan Rui

**Comment by reinder** [comment]
If you type a single or double quote on the server pc does it appear on the screen? Or do you have to press it twice to get two?

**Comment by alexpanrui** [comment]
I can key in a single or double quote on the server PC.
On Thu, Aug 13, 2015 at 1:03 PM, Reinder Feenstra <notifications@github.com>
wrote:

> If you type a single or double quote on the server pc does it appear on
> the screen? Or do you have to press it twice to get two?
>
> —
> Reply to this email directly or view it on GitHub
> <https://contactmonkey.com/api/v1/tracker?cm_session=6cab8e1e-1a54-4302-8d3e-e40daa499f82&cm_type=link&cm_link=93e4c674-3332-4d0e-855f-c84df14ce660&cm_destination=https://github.com/synergy/synergy/issues/4939#issuecomment-130536461>
> .
>



-- 
Rgds,
Pan Rui

**Comment by XinyuHou** [comment]
@alexpanrui 
Please give us more details about this issue. 

Here is a guild for raising an issue. 
https://github.com/synergy/synergy/wiki/Issues

This issue will be closed until we have more information.
