### ISSUE TITLE
Synergy 1.7.3 randomly goes to 100% CPU utilization on Windows 10 when Synergy GUI is not open

### ISSUE THREAD

**Issue by qdot** [synergy/synergy#4940]
With the synergy server running in the background on windows 10, sometimes I'll see it spike the CPU utilization of whatever CPU the process is assigned to. This only happens when the synergy GUI is not open. If I open the GUI, it goes back to being <5%. If I close the GUI, it'll stay there, but it eventually spikes again.

**Comment by XinyuHou** [comment]
Please upgrade to 1.7.4 and check our changelog.

https://github.com/synergy/synergy/blob/master/ChangeLog
