### ISSUE TITLE
Synergy can't be used after waking up from sleep mode on windows 8.1

### ISSUE THREAD

**Issue by demonguy** [synergy/synergy#4941]
It can be reproduced by me for 100% possibility. I don't know why.
If I sleep the computer and wake it up again, it will shows the lock screen and ask me to enter password. This computer is in client mode and i can move the cursor out from my server computer.
Unfortunately, i can't enter password on the waking up computer, but if i connect a keyboard and enter the password, then i can use synergy. It seems that synergy fail to work in lock screen

**Comment by Feksai** [comment]
@demonguy, try to set elevated mode on client (**Edit** -> **Settings** -> check **Elevated Mode**). This solved same problem on Windows 7 as a client and 8.1 as server.

**Comment by XinyuHou** [comment]
Duplicate to #4550
