### ISSUE TITLE
Space key types a "z"

### ISSUE THREAD

**Issue by sciamannikoo** [synergy/synergy#4943]
It's all in the title.

Just tried the nightly build and, as soon as I started typing, all spaces were replaced by a "z".

No idea how this key mapping could have gone so wrong, as the space key is the same in all keyboards, as far as I know.

Setup:
- Client: MBP 13" mid 2014
- Server: iMac 27" late 2013

**Comment by XinyuHou** [comment]
Duplicate to  #2765
