### ISSUE TITLE
Keyboard layout ENG-RUS

### ISSUE THREAD

**Issue by BeatCheat** [synergy/synergy#4945]
I work with systems Win7 64 (server) + Raspberry Pi 2 (client). As in previous versions of the program have not solved the problem with the layout. If you select English, then only works on English layout Raspberry Pi. if you select Russian, nothing works. I tested various versions synergy.

**Comment by Kami-no** [comment]
A bit more info. In my case Mac OSX 10.10 Server and 2 clients Gentoo Linux + Mac OSX 10.11. All systems use 1.7.3.

In most cases keyboard works at clients only if at the server ENG selected. But there are several cases when keyboard worked only if RUS selected at the server. Perhaps it depends on the layout when server started.

**Comment by XinyuHou** [comment]
Duplicate to #4280
