### ISSUE TITLE
Linux synergys hang (isXScreenSaver)

### ISSUE THREAD

**Issue by ceribik** [synergy/synergy#4946]
Happens occasionally to me with no obvious pattern or trigger. There was no screensaver running at the time. I have to forcefully kill synergys (kill -9) in order to restart it and get synergy working again.

Server: Arch Linux running KDE
Client: Win 8.1

Here is a backtrace:

> #0  0x00007fc62a7c996f in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007fc62a0b37e5 in _XReply () from /usr/lib/libX11.so.6
#2  0x00007fc62a0af11d in XSync () from /usr/lib/libX11.so.6
#3  0x000000000046cbdc in XWindowsUtil::ErrorLock::install(void (*)(_XDisplay*, XErrorEvent*, void*), void*) ()
#4  0x000000000046ccac in XWindowsUtil::getWindowProperty(_XDisplay*, unsigned long, unsigned long, std::string*, unsigned long*, int*, bool) ()
#5  0x000000000046daad in XWindowsScreenSaver::isXScreenSaver(unsigned long) const ()
#6  0x000000000046ea60 in XWindowsScreenSaver::handleXEvent(_XEvent const*) ()
#7  0x000000000045fda8 in XWindowsScreen::handleSystemEvent(Event const&, void*) ()
#8  0x000000000044b06a in EventQueue::dispatchEvent(Event const&) ()
#9  0x000000000044da8c in EventQueue::loop() ()
#10 0x00000000004553d5 in ServerApp::mainLoop() ()
#11 0x00000000004528db in ServerApp::runInner(int, char**, ILogOutputter*, int (*)(int, char**)) ()
#12 0x0000000000451ba9 in App::run(int, char**) ()
#13 0x000000000043e7f2 in main ()

Let me know if you need any more information.

**Comment by XinyuHou** [comment]
Duplicate to #5045
