### ISSUE TITLE
Synergy 1.7.4 ERROR: failed to verify server certificate fingerprint

### ISSUE THREAD

**Issue by dnickerson** [synergy/synergy#4958]
Installed Synergy 1.7.4 from scratch on both machines. Get this error from the client "ERROR: failed to verify server certificate fingerprint" There are no instructions for resetting the fingerprint. If I turn off "Use SSL encryption", synergy works.

**Comment by aledt** [comment]
I had this same issue and ramped up logging on the client to debug level to try and provide useful diagnostics. When I did so, I received a modal saying that the certificate was not in my keystore and asking me to add it if trusted, Once I did that, SSL works fine.

Logs: https://gist.github.com/aledt/062247241031719878cb

**Comment by kprovost** [comment]
I've managed to work around the problem on my i386 Debian machine by adding the server fingerprint to ~/.synergy/SSL/Fingerprints/TrustedServers.txt

**Comment by XinyuHou** [comment]
Duplicate to #4737

**Comment by vannitotaro** [comment]
Duplicate of #4626
