### ISSUE TITLE
Copy/Paste cross-platform behavior

### ISSUE THREAD

**Issue by jdc866** [synergy/synergy#4959]
Hey just a quick thought about a new feature...

For my setup, my host is a Mac and I have a Windows laptop as the client.

Not sure if it's possible, but when I'm on the laptop, could the shortcuts for copy/paste be the same as the Mac?

So when I copy a link or whatever on the Mac with command+c, I could paste on the Windows machine with command+v instead of ctrl+v? And then it would work vice-versa for folks with the reverse setup?

Thanks for considering!

**Comment by spronkey** [comment]
You can change the Command and Control keys on the server setup on a per screen basis, to achieve more or less this. The side effect is that all command shortcuts on the mac would be control key, but I use this setup on my own synergy.

**Comment by XinyuHou** [comment]
You can swap keys in Synergy.
