### ISSUE TITLE
Can't click or type on client while Chrome is focused on server.

### ISSUE THREAD

**Issue by JoshMcCullough** [synergy/synergy#4961]
Server: Win10
Client: Win10
Synergy: 1.7.4 (I believe this was also an issue with the previous version.)

If I am working in Chrome on the server, then mouse over to the client, sometimes I can't click or type. Doing so gives me a "ding" sound as if I'm trying to work in some window which has a modal open, blocking my action. If I return to the server and focus on something other than Chrome (e.g. click the Windows taskbar), I can then work on the client as expected.

**Comment by XinyuHou** [comment]
Duplicate to #47
