### ISSUE TITLE
OSX does not save the serverHostname setting when setup as a client

### ISSUE THREAD

**Issue by f8k8** [synergy/synergy#4962]
On OSX, entering a server IP address in the GUI and starting Synergy works fine, and will connect to a server. However, when OSX is restarted, the server's IP address is not saved in the settings, so the client does not automatically connect. It has only been tested with an OSX client and Windows 10 server, but may exhibit the same behaviour on all clients. Client version is 1.7.4.

The current workaround seems to be to manually edit the file ~/Library/Preferences/com.http-synergy-project-org.Synergy.plist, to add the key / value:

<key>serverHostname</key>
<string>SERVER IP ADDRESS</string>

**Comment by XinyuHou** [comment]
@f8k8 
This looks like a support ticket. Please contact our help desk or forum.
http://synergy-project.org/forum/
https://synergy-project.org/contact/

**Comment by nickspacek** [comment]
@f8k8 Did you ever create a forum item and/or get an answer/solution to this? I have been experiencing the same thing. Thanks for the plist suggestion.

**Comment by f8k8** [comment]
@nickspacek No, I don't think I ever got round to it.

**Comment by jessi3py** [comment]
Same here on macOS Sierra.

**Comment by ryanmortier** [comment]
Also having the same problem on a fresh install of Sierra.

**Comment by darkneo29** [comment]
Anyone figure this out?
