### ISSUE TITLE
Wrong screen size: w10 + amd Virtual Super Resolution

### ISSUE THREAD

**Issue by qdel** [synergy/synergy#4963]
Hi,

Synergy seems to detect an incorrect resolution for following configuration:

- windows 10
- Amd graphic card (whatever which one I think)
- Virtual Super Resolution activated (from 1680x1050 to 2560x1600)

Linux screen at right of windows 10 one. Windows 10 is synergy server.

Synergy report at boot on windows:

DEBUG: screen shape: 0,0 1707x1067

And indeed, it tries to switch screen at 1707 pixels... From this, mouse is unusable, stuck to the other screen (and not moving there).

Thanks!

**Comment by sidewinder94** [comment]
Did you try the fix needed by many users using HiDPI screens ?
Might be related to #4041

**Comment by XinyuHou** [comment]
Should be fixed by 1.7.5

http://synergy-project.org/nightly?filter=v1.7.5-rc1-ceab3a8
