### ISSUE TITLE
Stuck Win key since latest upgrade

### ISSUE THREAD

**Issue by gerroon** [synergy/synergy#4965]
Hi

I am isng Win764 as the server and Debian64 as the client. Since upgrading to  1.7.3 my windows keys actiong up on Linux client. I literally have to restart Xserver 3 times a day. This seems like to be the only solution. 

I am not saying this is a %100 Synergy issue but this started happening this much right after this upgrade.

thanks

**Comment by VeNoMouS** [comment]
1.7.4 is latest

**Comment by sadsfae** [comment]
Hi @gerroon have you tested this against 1.7.4?  This still happens for me (same as issue #4969 )

**Comment by gerroon** [comment]
Hi

I have not been testing it as much, but I see that 1.7.4 crashes so often for me or drops connection so often that I have stopped using Synergy. It seems to me that I had much better luck with 1.6x between Win and Lin.

I will try to test this behaviour though.

**Comment by XinyuHou** [comment]
Duplicate to 4969
