### ISSUE TITLE
apostrophe sometimes doesn't convert to diacritic when keyboard is set to US international

### ISSUE THREAD

**Issue by chgorsan** [synergy/synergy#4967]
This issue happened to me in both Windows 7 and Windows 10 and originally made me uninstall Synergy, it happens even if I'm not using my keyboard with a 2nd computer. I'm international and I'm familiar with the US layout, but I need to use sometimes diacritics because I use spanish too (examples, á, é, etc), therefore I set my keyboard layout to United States International, this will let you hit the apostrophe key but it won't appear right away, it will wait for you to type another key and then it will appear, and its mostly useful to put diacritics on vowels. Sometimes when I'm typing, some of the words that I intend to type with a diacritic won't display it, especially when I'm typing too fast, with words like "por qué". Interestingly, if I turn off the Synergy service, this behavior stops completely and I'm able to type fast with all diacritics, I'm assuming the Synergy service doesn't completely support the United States International keyboard layout.

**Comment by XinyuHou** [comment]
Duplicate to #4280
