### ISSUE TITLE
Keys type with shift pressed on Ubuntu 12.04 client

### ISSUE THREAD

**Issue by AlperSakarya** [synergy/synergy#4992]
I have a Mac OSX 10.10.5 Server that my Ubuntu 12.04 client connects.

After the upgrade I've started seeing ton of issues like client died etc. messages however this one is really causing issues.
- All the keys on the client typing as if SHIFT key pressed like here is what number 1 to = press on the key board:
!@#$%^&*()_+

- Also when I hit caps lock on client, or server, they are out of sync. If I am typing caps on server it's small letters in client, if I open caps lock in client then it's capital in server it was not like that before.

- I can't right click on Ubuntu terminal when this is happening as well

Here is my configuration file which worked fine since the past two versions except this version, also configuring server in interactive mode does the same thing so not config related I believe:

section: screens
    MyLaptop:
        halfDuplexCapsLock = false
        halfDuplexNumLock = false
        halfDuplexScrollLock = false
        xtestIsXineramaUnaware = false
        switchCorners = none
        switchCornerSize = 0
    MyDesktop:
        halfDuplexCapsLock = false
        halfDuplexNumLock = false
        halfDuplexScrollLock = false
        xtestIsXineramaUnaware = false
        switchCorners = none
        switchCornerSize = 0
end

section: aliases
end

section: links
    MyLaptop:
        right = MyDesktop
    MyDesktop:
        left = MyLaptop
end

section: options
    relativeMouseMoves = false
    screenSaverSync = true
    win32KeepForeground = false
    switchCorners = none
    switchCornerSize = 0
end

**Comment by AlperSakarya** [comment]
More from the logs

""" /var/log/auth.log:Sep  7 15:23:03 uc81f66212949555a6c87 sudo: brian : TTY=pts/0 ; PWD=/home/local/ANT/brian ; USER=root ; COMMAND=/usr/bin/killall synergyc
/var/log/auth.log:Sep  7 19:56:55 uc81f66212949555a6c87 sudo: brian : TTY=pts/1 ; PWD=/home/local/ANT/brian ; USER=root ; COMMAND=/usr/bin/killall synergyc
/var/log/auth.log:Sep  7 19:57:25 uc81f66212949555a6c87 sudo:     root : TTY=pts/1 ; PWD=/home/local/ANT/brian ; USER=root ; COMMAND=/usr/bin/killall synergyc
/var/log/auth.log:Sep  7 19:57:37 uc81f66212949555a6c87 sudo:     root : TTY=pts/1 ; PWD=/home/local/ANT/brian ; USER=root ; COMMAND=/usr/bin/killall synergyc
/var/log/auth.log:Sep  8 13:31:19 uc81f66212949555a6c87 sudo: brian : TTY=pts/1 ; PWD=/home/local/ANT/brian ; USER=root ; COMMAND=/usr/bin/killall synergyc
/var/log/auth.log:Sep  8 14:54:21 uc81f66212949555a6c87 sudo: brian : TTY=pts/1 ; PWD=/home/local/ANT/brian ; USER=root ; COMMAND=/usr/bin/apt-get install synergyc
/var/log/auth.log:Sep  9 15:38:22 uc81f66212949555a6c87 sudo: brian : TTY=pts/0 ; PWD=/home/local/ANT/brian ; USER=root ; COMMAND=/usr/bin/killall synergyc
/var/log/auth.log:Sep  9 19:17:23 uc81f66212949555a6c87 sudo: brian : TTY=pts/2 ; PWD=/home/local/ANT/brian ; USER=root ; COMMAND=/usr/bin/killall synergyc
/var/log/auth.log:Sep  9 19:19:47 uc81f66212949555a6c87 sudo: brian : TTY=pts/2 ; PWD=/home/local/ANT/brian ; USER=root ; COMMAND=/usr/bin/killall synergyc
/var/log/auth.log:Sep 10 14:26:10 uc81f66212949555a6c87 sudo: brian : TTY=pts/0 ; PWD=/home/local/ANT/brian ; USER=root ; COMMAND=/bin/grep -R synergyc /var/log
/var/log/auth.log:Sep 10 14:26:31 uc81f66212949555a6c87 sudo: brian : TTY=pts/0 ; PWD=/home/local/ANT/brian ; USER=root ; COMMAND=/bin/grep -R synergyc /var/log
/var/log/auth.log.1:Aug 30 14:28:42 uc81f66212949555a6c87 sudo: brian : TTY=pts/2 ; PWD=/home/local/ANT/brian ; USER=root ; COMMAND=/usr/bin/synergyc --display :0.0 685b35a94606.ant.amazon.com
/var/log/kern.log:Sep  7 19:56:11 uc81f66212949555a6c87 kernel: [11040.260215] synergyc[1439]: segfault at 20 ip 000000000045189b sp 00007fffba278590 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  7 19:57:25 uc81f66212949555a6c87 kernel: [11114.488383] synergyc[5079]: segfault at 0 ip 000000000044be93 sp 00007fff5438d430 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  7 19:57:37 uc81f66212949555a6c87 kernel: [11126.960863] synergyc[5088]: segfault at 0 ip 000000000044be93 sp 00007fff980654e0 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  7 19:58:48 uc81f66212949555a6c87 kernel: [11197.426873] synergyc[5107]: segfault at 20 ip 000000000045189b sp 00007fffecbafde0 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 13:30:28 uc81f66212949555a6c87 kernel: [   98.917158] synergyc[2272]: segfault at 0 ip 000000000044be93 sp 00007ffd2d1f5e90 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 13:31:19 uc81f66212949555a6c87 kernel: [  150.118076] synergyc[2293]: segfault at 0 ip 000000000044be93 sp 00007ffe3686efa0 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 13:31:41 uc81f66212949555a6c87 kernel: [  171.783853] synergyc[2319]: segfault at 0 ip 000000000044be93 sp 00007ffc20cdfd40 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 13:32:27 uc81f66212949555a6c87 kernel: [  217.784166] synergyc[2340]: segfault at 0 ip 000000000044be93 sp 00007ffc07b6a250 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 13:32:48 uc81f66212949555a6c87 kernel: [  238.665829] synergyc[2351]: segfault at 0 ip 000000000044be93 sp 00007ffee7ddab60 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 13:38:47 uc81f66212949555a6c87 kernel: [  598.679578] synergyc[2378]: segfault at 0 ip 000000000044be93 sp 00007ffc4f38ed20 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 14:31:39 uc81f66212949555a6c87 kernel: [ 3773.011492] synergyc[4616]: segfault at 0 ip 000000000044be93 sp 00007ffd5689fe70 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 14:50:10 uc81f66212949555a6c87 kernel: [ 4885.122595] synergyc[17158]: segfault at 0 ip 000000000044be93 sp 00007ffd2f86f9d0 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 14:57:48 uc81f66212949555a6c87 kernel: [ 5344.001208] synergyc[17889]: segfault at 0 ip 000000000044be93 sp 00007ffcc32af1b0 error 4 in synergyc[400000+a6000]
/var/log/daemon.log:Sep  8 14:55:37 uc81f66212949555a6c87 Synergy 1.3.8: 2015-09-08T10:55:37 WARNING: cannot open secondary screen: unable to open screen#012#011/build/buildd/synergy-1.3.8/src/cmd/synergyc/synergyc.cpp,346
/var/log/kern.log.1:Aug 31 15:49:29 uc81f66212949555a6c87 kernel: [ 6183.028854] synergyc[4397]: segfault at 10 ip 00000000004553b8 sp 00007fa43bfe6da0 error 4 in synergyc[400000+a6000]
/var/log/kern.log.1:Aug 31 20:57:14 uc81f66212949555a6c87 kernel: [24664.078772] synergyc[9900]: segfault at 0 ip 000000000044be93 sp 00007ffe38cddbd0 error 4 in synergyc[400000+a6000]
/var/log/kern.log.1:Aug 31 20:57:35 uc81f66212949555a6c87 kernel: [24684.891607] synergyc[9907]: segfault at 0 ip 000000000044be93 sp 00007fffa51e5ba0 error 4 in synergyc[400000+a6000]
/var/log/kern.log.1:Sep  2 19:11:11 uc81f66212949555a6c87 kernel: [191242.914079] synergyc[10702]: segfault at 0 ip 000000000044be93 sp 00007ffd5f6d0930 error 4 in synergyc[400000+a6000]
/var/log/kern.log.1:Sep  2 19:11:47 uc81f66212949555a6c87 kernel: [191278.044912] synergyc[10711]: segfault at 0 ip 000000000044be93 sp 00007ffd4c9faaf0 error 4 in synergyc[400000+a6000] """

**Comment by AlperSakarya** [comment]
More from the logs:

/var/log/daemon.log:Sep  8 14:55:37 brian-ubuntu Synergy 1.3.8: 2015-09-08T10:55:37 WARNING: cannot open secondary screen: unable to open screen#012#011/build/buildd/synergy-1.3.8/src/cmd/synergyc/synergyc.cpp,346
/var/log/kern.log.1:Aug 31 15:49:29 brian-ubuntu kernel: [ 6183.028854] synergyc[4397]: segfault at 10 ip 00000000004553b8 sp 00007fa43bfe6da0 error 4 in synergyc[400000+a6000]
/var/log/kern.log.1:Aug 31 20:57:14 brian-ubuntu kernel: [24664.078772] synergyc[9900]: segfault at 0 ip 000000000044be93 sp 00007ffe38cddbd0 error 4 in synergyc[400000+a6000]
/var/log/kern.log.1:Aug 31 20:57:35 brian-ubuntu kernel: [24684.891607] synergyc[9907]: segfault at 0 ip 000000000044be93 sp 00007fffa51e5ba0 error 4 in synergyc[400000+a6000]
/var/log/kern.log.1:Sep  2 19:11:11 brian-ubuntu kernel: [191242.914079] synergyc[10702]: segfault at 0 ip 000000000044be93 sp 00007ffd5f6d0930 error 4 in synergyc[400000+a6000]
/var/log/kern.log.1:Sep  2 19:11:47 brian-ubuntu kernel: [191278.044912] synergyc[10711]: segfault at 0 ip 000000000044be93 sp 00007ffd4c9faaf0 error 4 in synergyc[400000+a6000]


/var/log/kern.log:Sep  7 19:56:11 brian-ubuntu kernel: [11040.260215] synergyc[1439]: segfault at 20 ip 000000000045189b sp 00007fffba278590 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  7 19:57:25 brian-ubuntu kernel: [11114.488383] synergyc[5079]: segfault at 0 ip 000000000044be93 sp 00007fff5438d430 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  7 19:57:37 brian-ubuntu kernel: [11126.960863] synergyc[5088]: segfault at 0 ip 000000000044be93 sp 00007fff980654e0 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  7 19:58:48 brian-ubuntu kernel: [11197.426873] synergyc[5107]: segfault at 20 ip 000000000045189b sp 00007fffecbafde0 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 13:30:28 brian-ubuntu kernel: [   98.917158] synergyc[2272]: segfault at 0 ip 000000000044be93 sp 00007ffd2d1f5e90 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 13:31:19 brian-ubuntu kernel: [  150.118076] synergyc[2293]: segfault at 0 ip 000000000044be93 sp 00007ffe3686efa0 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 13:31:41 brian-ubuntu kernel: [  171.783853] synergyc[2319]: segfault at 0 ip 000000000044be93 sp 00007ffc20cdfd40 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 13:32:27 brian-ubuntu kernel: [  217.784166] synergyc[2340]: segfault at 0 ip 000000000044be93 sp 00007ffc07b6a250 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 13:32:48 brian-ubuntu kernel: [  238.665829] synergyc[2351]: segfault at 0 ip 000000000044be93 sp 00007ffee7ddab60 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 13:38:47 brian-ubuntu kernel: [  598.679578] synergyc[2378]: segfault at 0 ip 000000000044be93 sp 00007ffc4f38ed20 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 14:31:39 brian-ubuntu kernel: [ 3773.011492] synergyc[4616]: segfault at 0 ip 000000000044be93 sp 00007ffd5689fe70 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 14:50:10 brian-ubuntu kernel: [ 4885.122595] synergyc[17158]: segfault at 0 ip 000000000044be93 sp 00007ffd2f86f9d0 error 4 in synergyc[400000+a6000]
/var/log/kern.log:Sep  8 14:57:48 brian-ubuntu kernel: [ 5344.001208] synergyc[17889]: segfault at 0 ip 000000000044be93 sp 00007ffcc32af1b0 error 4 in synergyc[400000+a6000]

/var/log/auth.log:Sep 10 14:26:31 brian-ubuntu sudo: brian : TTY=pts/0 ; PWD=/home/local/company/brian ; USER=root ; COMMAND=/bin/grep -R synergyc /var/log
/var/log/auth.log.1:Aug 30 14:28:42 brian-ubuntu sudo: brian : TTY=pts/2 ; PWD=/home/local/company/brian ; USER=root ; COMMAND=/usr/bin/synergyc --display :0.0 brian-MAC

**Comment by XinyuHou** [comment]
Duplicate to #4493
