### ISSUE TITLE
Linux clipboard fails

### ISSUE THREAD

**Issue by dnickerson** [synergy/synergy#4995]
Linux mint 17.2 on both computers. synergy 1.7.4 with SSL enabled.OpenSSL 1.0.1f 6 Jan 2014. Most times when I do a clipboard operation bewtween computers, synergy fails with the message "SSL connection closed". I have to restart the client and/or the server. Very frustrating. Synergy used to be rock stable on Linux.

**Comment by nyetwurk** [comment]
https://github.com/synergy/synergy/issues/4735
https://github.com/synergy/synergy/issues/4920

**Comment by XinyuHou** [comment]
Duplicate to #4735
