### ISSUE TITLE
Include release date in Help -> About Synergy

### ISSUE THREAD

**Issue by OrganicBrian** [synergy/synergy#4996]
Problem: Users easily lose track of which nightly build they have installed, making it more difficult to accurately document and report bugs.

Solution: Show build ID in Help -> About Synergy window

This was originally suggested by a user in Google Groups:

https://groups.google.com/forum/#!topic/synergy-users/5wtKPHQraoI

**Comment by tomicjr** [comment]
Agreed. This appears to be on the roadmap for 1.8.

See https://github.com/synergy/synergy/issues/4893

**Comment by the-wes** [comment]
duplicates https://github.com/synergy/synergy/issues/4893

**Comment by nbolton** [comment]
Good spot @the-wes :+1:

**Comment by kdoteu** [comment]
#4893 got 404 so i post my answer here

![image](https://cloud.githubusercontent.com/assets/3602457/16535348/d086b102-3fe6-11e6-89ce-b9afc01728ba.png)

Version as shown :d 
OS: Windows 7 64Bit

**Comment by mikeo-bixly** [comment]
#4893 404'd
Worked as expected.
OS: Linux (Fedora 24)
Version: v1.8.1-beta-f7377d6-Linux-x86_64
