### ISSUE TITLE
synergys freeze

### ISSUE THREAD

**Issue by guss77** [synergy/synergy#4998]
This is an issue I'm encountering with Synergy 1.7.4 release on Ubuntu 15.10 x64. Occasionally synergys freezes - no more lines are shown in the logs (not even the "trying to move out of screen" DEBUG1 logs), and restarting the client does not reconnect.

I performed a core dump when synergys froze, see link below. The configuration includes a single client on the right side.

synergys log from a few minutes before the freeze up to the last log line when the server froze: https://drive.google.com/open?id=0B-ikbyi1ym69Q1ZSWUMydjZYSEk
synergys core dump https://drive.google.com/open?id=0B-ikbyi1ym69Tm5hallQZlFDMW8

I don't think this is related to the clipboard issue, because when the freeze happens I don't think I was doing any clipboard action (except maybe selection - I'm never sure when this happens)

**Comment by joecot** [comment]
Having the same issue, on 14.04

**Comment by dgstangel** [comment]
I'm having the exact same issue on 14.04 talking to a single Windows 7 desktop to the right.  

A very ugly workaround is to kill -9 the synergys process on the Linux system, wait a couple of seconds, and restart. That seems to get things going again, but only for so long before it freezes up again.

**Comment by XinyuHou** [comment]
Duplicate to #5045
