### ISSUE TITLE
Unable to paste text from Windows Chrome into OSX Terminal

### ISSUE THREAD

**Issue by the-wes** [synergy/synergy#5004]
1. Copy text from Chrome on Windows server
2. Switch focus to OSX client
3. Attempt to paste into Terminal (Paste option is greyed out)
4. Attempt to paste into TextEdit (works)
5. Switch focus to Windows server
6. Copy text from Notepad or anywhere else
7. Switch focus to OSX client
8. Attempt to paste into Terminal (works)

I can make a video if that would help.

**Comment by mergeweb** [comment]
We have this same issue and it is uber frustrating.

**Comment by joubertredrat** [comment]
Hi guys,

@XinyuHou my problem is in all browsers on Linux server or Windows client, but isn't all time that this problem occours.

**Comment by XinyuHou** [comment]
Duplicate to #5041
