### ISSUE TITLE
Synergy creates unused config files.

### ISSUE THREAD

**Issue by djmentos** [synergy/synergy#5009]
Hello,

I have putted my Synergy GUI configuration to:
/etc/xdg/Synergy.conf
and it loads it, but after several minutes it recreates file:
/home/dkoss/.config/Synergy/Synergy.conf

It is unwanted by me, because my homedir is shared between two PCs. One of them is server, second is a client.

**Comment by XinyuHou** [comment]
Please contact our help desk or forum.

http://synergy-project.org/contact/
http://synergy-project.org/forum/
