### ISSUE TITLE
Synergy Fast Mouse Win10

### ISSUE THREAD

**Issue by Overcon** [synergy/synergy#5014]
Hi,

I am going to try and explain this, but it's hard to put in words that I hope will make sense. When I was running Windows 7 and I had a client that ran WIndows Server 2012. When I would move the mouse from the server PC (Win7) to the client (Svr12) and inside the games I had on each machine, when you hold down the right mouse button and move the mouse, it helps you turn around and move (game is Archeage made by Trion) in game.

When the mouse was used on the server client, the game operated normally, I would turn int he normal method, slow and consistent as it should. When I moved the mouse to the Client PC, and tried to move it, it seems like it is 1000 times more sensitive. If I held the right mouse button down and tried moving with the keyboard it would spin the screen around super fast.

If I moved it back to the client it would operate as normal.

Now I have installed Windows 10, clean install, I didn't do an upgrade. Now, when I start the PC up and login, synergy connects and I can move the mouse between the two screens, but the spinning and super sensitivity when moving in game, is happening on the Windows 10 Server as it used to on the Svr 2012 Client.

It's now doing what it used to on the client on the server. If I stop synergy, the mouse returns to normal, but I can't share it across the PC's obviously.

If I stop the Synergy Server the mouse reverts to normal and if I restart it it goes back to the way it was before I installed Win10. Works normal on the server and super fast on the client.

Any suggestions? 

I put to fraps video captures on my Google Drive. One is of the client spinning around with Synergy super fast (which is what my Win10 Server is now doing on boot, unless I stop Synergy and start it again). The other video is on the Win10 in normal mode (like it used to be in Win7 and like it is after I close Synergy and restart it in Win10). Holding right mouse button down and spinning mouse to turn the characters. You can see the speed issues.

https://drive.google.com/open?id=0BzsKCe89GscxWldpVmRxR195Y3M

**Comment by XinyuHou** [comment]
Duplicate to #2631
