### ISSUE TITLE
How to set global hot key for all machines?

### ISSUE THREAD

**Issue by hu6360567** [synergy/synergy#5027]
For example,
Machine A has a software which has a hotkey, i.e. ctrl-alt-s.
I'd like to make it to global hotkey, which works on other machines. 
To be more specifically, when synergy focus on machine B, I push ctrl-alt-s, the software on machine A works.

**Comment by XinyuHou** [comment]
Please contact our help desk or forum.

http://synergy-project.org/contact/
http://synergy-project.org/forum/
