### ISSUE TITLE
Mouse speed on Client PC using Synergy Extremely Fast

### ISSUE THREAD

**Issue by Overcon** [synergy/synergy#5035]
Hi,

I am using Synergy 1.7.4 on a Windows 10 system (as Server) and a Windows Server 2012 R2 (as Client).

The issue is, when running games on the two systems and I move the mouse from the server to the client, movement actions in the game on the client are hyper accelerated. meaning when I push the right mouse button and then the keyboard to move character, the clients mouse is so sensitive it's not usable. 

This seems to be an issue for many across all OS's, so it's Synergy based. Has anyone found a solution to slow the mouse down on the client so it's usable in games? 

Looking for help on this!

Thanks!

**Comment by XinyuHou** [comment]
Duplicate to #2631

**Comment by depperson** [comment]
This isn't actually a dupe of #2631.  Perhaps the problem report here wasn't clearly understood?  The mouse speed on server pc is not the same as client pc.  Pretty simple.  And since I paid for Synergy I'd appreciate a little more concern from devs about user reported issues.

**Comment by depperson** [comment]
I have the same issue reported here, but not using any games.  I am not sure if this is actually a dupe of #2631.  See also https://symless.com/forums/topic/754-mouse-moves-too-fast-on-client-machine/
