### ISSUE TITLE
Cursor appears in Server but disappears as it enters client's screen

### ISSUE THREAD

**Issue by hiuwo** [synergy/synergy#5037]
Cursor appears in Server but disappears as it enters client's screen.

Server: 1.7.4, win 10, 3840 x 2160 175%
Client: 1.7.4, win 8.1 1388 x 768 125% (Touch Screen)

As the Cursor enters the Client's screen, the mouse disappears and remained hidden and does not click on anything. On occasions it will appear in server's screen and as I move more than maybe 2 inches across the screen, it snaps back to a fixed position and keeps snapping back if I attempt to move the cursor too far away.

PS I have read http://www.palermo4.com/post/Mouse-Cursor-Disappears-When-Switching-Screens-with-Synergy.aspx and tried to put both in the same magnification but no avail.
My Mac OSX 10.11 as a Server however works fine with my Client.

**Comment by mzazon** [comment]
I have a similar issue, on stable build 1.7.4.  Win 10 @ 4k 60Hz any magnification other than 100% (I usually run 125% or 150%) the cursor will disappear when moving to a mac client (or any other client) and not reappear until the server is stopped.

**Comment by XinyuHou** [comment]
Duplicate to #2754
