### ISSUE TITLE
System tray is unavailable, quitting

### ISSUE THREAD

**Issue by PureTryOut** [synergy/synergy#5040]
I've seen others post about this before, but for them the error appeared while they did in fact have a system tray. I use Lemonbar with i3, and thus have no system tray, don't need one either.

However I would still like to use Synergy. Is there anyway to run it without a system tray?

**Comment by XinyuHou** [comment]
@PureTryOut 
Please contact our help desk or forum.

http://synergy-project.org/contact/
http://synergy-project.org/forum/
