### ISSUE TITLE
Cursor freezes at client edge after lock screen loaded on Windows 10 server

### ISSUE THREAD

**Issue by mikeitca** [synergy/synergy#5055]
Just download and install the latest version 1.7.4 both client server.
It happens after upgrade server to Windows 10 Pro
Client:  windows XP Pro.
Server: Windows 10 Pro.
If the cursor is located at client screen, the cursor will freeze at the edge when server lock screen was loaded and you want to move the cursor back to server.  Keyboard doesn't work at the same time.
Work around solution: plug mouse in client PC to terminate synergyc.exe on client then the cursor will be released before synergyc.exe was reloaded. The cursor will be re-freezed after synergyc.exe auto reloaded if you don't move the cursor back to server screen.

**Comment by XinyuHou** [comment]
Duplicate to https://github.com/synergy/synergy/issues/5075
