### ISSUE TITLE
Syngery on gitter

### ISSUE THREAD

**Issue by joubertredrat** [synergy/synergy#5056]
Hi guys,

Why not add Synergy on gitter? I think that is good idea to syngery talk about issues, app performance and another thinks about syngery.

What you think? Is good idea? here 2 examples from projects with Gitter.

https://github.com/gogits/gogs
https://github.com/cachethq/Cachet

**Comment by XinyuHou** [comment]
@joubertredrat 

That sounds like a good idea.

But please use our dev/user mailing lists to discuss this.

https://groups.google.com/forum/#!forum/synergy-users
https://groups.google.com/forum/?pli=1#!forum/synergy-dev
