### ISSUE TITLE
Synergy 1.7.4 server not starting up due to synwinhk.dll being in use by another process

### ISSUE THREAD

**Issue by yin** [synergy/synergy#5062]
I have seen this issue closed here about twice, but my whole team is still having the same issue on Windows 8.1. Chrome and Cygwin's MinTTY (sometimes Eclipse) usually keep using the DLL, when problems occur (I used Process Explorer to troubleshoot the issue).

**Comment by XinyuHou** [comment]
Duplicate to #4957
