### ISSUE TITLE
Major opcode of failed request: 53 (X_CreatePixmap)

### ISSUE THREAD

**Issue by hlmasterchief93** [synergy/synergy#5068]
Problem running Synergy in Fedora 22. Start client from GUI will stop intermediately with synergy 1.7.3. With 1.7.4, it will stuck at stop and restart loop.

NOTE: starting client
NOTE: config file: /tmp/qt_temp.SL1839
NOTE: log level: INFO
X Error of failed request: BadValue (integer parameter out of range for operation)
Major opcode of failed request: 53 (X_CreatePixmap)
Value in failed request: 0x0
Serial number of failed request: 16
Current serial number in output stream: 17
NOTE: stopping synergy desktop process

**Comment by XinyuHou** [comment]
Duplicate to #4814

**Comment by hlmasterchief93** [comment]
Still not fixed in 1.7.5 rc1
