### ISSUE TITLE
Automated Unit Tests

### ISSUE THREAD

**Issue by jakesyl** [synergy/synergy#5069]
Hello,

I was wondering if synergies core developers thought automating unit tests with Travis CI was of interest to any developers in here.  Many other major c/c++ developers use continuous integration to run their unit tests and compile on every run to make seeing issues with PR's easier.  If you guys have interest I'd be happy to implement this.

**Comment by XinyuHou** [comment]
@jakesyl 
Automating and Unit tests are always good to have. We are definitely interested.

But probably it is better we discuss it in the dev mailing list.
https://groups.google.com/forum/#!forum/synergy-dev

**Comment by jakesyl** [comment]
@XinyuHou Alright will do.  Didn't know there was a google groups, as there's no CONTRIBUTING file.

Thanks!
