### ISSUE TITLE
International layouts are STILL broken on Mac OS

### ISSUE THREAD

**Issue by orcinus** [synergy/synergy#5070]
I've been stuck using an ancient version of Synergy on my Mac OS (client) FOR YEARS now.
Anything newer than synergyc 1.3.0 (copyrighted 2002!) just has completely broken non-US layouts on the client side.

Any idea on when this will finally change?
I didn't mind using 13 years old code, even though it doesn't support SSL, while it was still working.

But now the clipboard is broken, thanks to changes in Mac OS and new versions of Synergy Server.

I can't continue using it like this.
The layouts are a total mess.

**Comment by orcinus** [comment]
Related to: https://github.com/synergy/synergy/issues/3961

I might be naive, but the thing i don't understand is - WHY this is such a problem when you had it working just fine years ago.

**Comment by XinyuHou** [comment]
Duplicate to #4280

@orcinus 
Sorry for the inconvenience. We have prioritized this issue.
