### ISSUE TITLE
Win 7 Server - Accent in combo key stroke sometimes missing

### ISSUE THREAD

**Issue by mbargiel** [synergy/synergy#5079]
Server: Windows 7 SP1, Synergy 1.7.4
Client: Ubuntu 14.04 LTS, Synergy 1.7.4
Language: English (CA)
Keyboard: French Canadian

While on the server, if I need to type a letter with an accent (e.g. ` + e to get è), the accent will usually be missing if I type fast. I have to be very deliberate to avoid this problem (which does not occur if Synergy is not running).

Repro steps:
1) Press and release M, press and release \`, press and release E.
--> Printed out: "mè" (expected)
2) Interleave the previous letter press and the accent press (as often happens while typing fast): Press M, press \`, release M, release \`, press and release E.
--> Printed out: "me" (should have been "mè")
3) Alternative interleaving: Press M, press and release \`, release M, press and release E:
--> Printed out: "me" (should have been "mè")
4) Alternative interleaving: Press M, press and release \`, press and release E, release M
--> Printed out: "mè" (expected)

The exact problem appears to be when an accent key is pressed while another key is already down, and that key is released before the accent is "consumed". In that case, Synergy "swallows" the accent key.

**Comment by mbargiel** [comment]
I haven't checked if this problem happens while the client is not connected. I have confirmed that if I stop the server, this problem no longer occurs.

**Comment by XinyuHou** [comment]
Duplicate to https://github.com/synergy/synergy/issues/5007
