### ISSUE TITLE
Network spikes

### ISSUE THREAD

**Issue by MRDRMUFN** [synergy/synergy#5083]
Running v. 1.7.1  on OS X El Capitan

I've noticed that while synergy is not connected to any clients it will hog all network traffic on host machine for 1 second every ~5 seconds. 

Steps to reproduce
1. Connect to network with no synergy clients available or running.
2. Ping the gateway with short interval.
3. Shut down synergy server.

**Comment by XinyuHou** [comment]
Duplicate to 
https://github.com/synergy/synergy/issues/4132
https://github.com/synergy/synergy/issues/4520
