### ISSUE TITLE
Mouse Cursor sticks in client (does not recover)

### ISSUE THREAD

**Issue by mwalters12** [synergy/synergy#5084]
It started last week after installing new video card, drivers, monitors. I did many things during the process so not sure that's the sole cause. Also had to do a windows restore from driver issues.

Server: Windows 10 Desktop
Client: Windows 10 Laptop

I tried uninstall both from server/client and also ccleaner, deleted all registry items with "Synergy". No luck, fresh installs still has mouse sticking on client in bottom right corner. The only way I know this is when I right click it shows the prompt at the bottom "Show Desktop / Peek at Desktop". I can use Ctrl-alt-del to get my cursor back on the server.

Is there anyone else having this issue? Is there a different way I should be reinstalling?

Log Message: 
ERROR: could not get session id for process id 3972

**Comment by XinyuHou** [comment]
Please let me know if you case is the same as https://github.com/synergy/synergy/issues/5030

**Comment by mwalters12** [comment]
Yes, that was my issue.  Putting size of text/apps/items back to 100% allowed Synergy to work correctly.

Great that it worked, but now my text is very tiny.  Hopefully you know this and can fix for next release.

Thank You,

**Comment by XinyuHou** [comment]
Please try this rc which includes the fix
http://synergy-project.org/nightly?filter=v1.7.5-rc1-46271
