### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by bieniekmateusz** [synergy/synergy#5085]
I use synergy with my new laptop Dell which does not have a typical network cable. It needs an adapter to USB to connect to a network (will become relevant soon). 

Synergy has been losing connection, particularly when I stop moving the mouse. After synergy hanged, the log showed that it tried to reconnect. 

I decided to check whether my laptop loses connection for short periods of time. So I run a ping from the laptop to my PC. 

This ping has not shown any lost connections. However, when the ping is running in the background, synergy does not lose connection any more. 

Hope this helps somehow someone^.

**Comment by XinyuHou** [comment]
Please give us more details about this issue. 

Here is a guild for raising an issue. 
https://github.com/synergy/synergy/wiki/Issues

This issue will be closed until we have more information.
