### ISSUE TITLE
Cannot paste between Ubuntu 14.04 client and Mavericks OSX with Synergy 1.7.4

### ISSUE THREAD

**Issue by ivanixgames** [synergy/synergy#5086]
Hi all,

I recall I had copy/paste working before but on a different version of synergy.
Then later, i swapped out my Ubuntu drive for Windows 7 drive. somewhere along I was informed about Synergy Pro, so I downloaded and installed that. Things seemed to work more or less except sometimes copy/paste would fail between Win 7 and Mavericks.  
Then today, I swapped my Ubuntu 14.04 back in,  after some trouble I had synergy working, but no copy/paste.  I updated to 1.74 on ubuntu but still no dice.

Does anyone recall what prior version of synergy worked between linux and mac?

**Comment by ivanixgames** [comment]
The default version from ubuntu or debian's repos was 1.4 something.  So I installed a 1.4.x on Mavericks. Copy / paste now seems to work again.

**Comment by XinyuHou** [comment]
Duplicate to https://github.com/synergy/synergy/issues/4735

Please try this pull request.
https://github.com/synergy/synergy/pull/4994
