### ISSUE TITLE
./tmp\release\main.o: file not recognized: File format not recognized

### ISSUE THREAD

**Issue by jrossjones** [synergy/synergy#5088]
Trying to compile synergy 1.7.4 stable Win8 64bit
I am receiving the following error

    Time Elapsed 00:00:03.56
    Make GUI command: mingw32-make release
    Entering dir: src/gui
    mingw32-make -f Makefile.Release
    mingw32-make[1]: Entering directory `C:/synergy-1.7.4-stable/src/gui'
    g++ -enable-stdcall-fixup -Wl,-enable-auto-import -Wl,-enable-runtime-pseudo-rel
    oc -Wl,-s -mthreads -Wl -Wl,-subsystem,windows -o ..\..\bin\Release\synergy.exe
    object_script.synergy.Release  -L"c:\Qt\2010.02\qt\lib" -lmingw32 -lqtmain tmp\r
    elease\Synergy_res.o -L../../ext/bonjour/x64 -ldnssd -lQtGui4 -lQtNetwork4 -lQtC
    ore4
    ./tmp\release\main.o: file not recognized: File format not recognized
    collect2: ld returned 1 exit status
    mingw32-make[1]: *** [..\..\bin\Release\synergy.exe] Error 1
    mingw32-make[1]: Leaving directory `C:/synergy-1.7.4-stable/src/gui'
    mingw32-make: *** [release] Error 2
    Going back to: C:\synergy-1.7.4-stable
    Error: mingw32-make release failed with error: 2

in case it helps I also followed https://github.com/synergy/synergy/issues/4205 to fix another error

**Comment by XinyuHou** [comment]
Please use our dev mailing list for compiling Synergy on your own.

https://groups.google.com/forum/#!forum/synergy-dev
