### ISSUE TITLE
Client hangs on Linux Mint 17.2 (repro steps included)

### ISSUE THREAD

**Issue by baston85** [synergy/synergy#5090]
Ever since I updated to 1.7.3, synergyc would randomly stop working, and I was unable to kill the process as well. Updating to 1.7.4 (stable) eliminated the hangs on my Mint 17.2 Xfce laptop, but still happens periodically on my Mint 17.2 Cinnamon desktop. Having some spare time today, I dug in to it and came across the specific scenario causing the hang.

If there is text highlighted in bash (gnome-terminal) and I move the mouse between the client and server (Win 7), a freeze is immanent but not always on the first switch. The number of switches before freezing is inconsistent, but there is observable lag with each switch when it doesn't freeze. Highlighted text is copied to the server's clipboard properly.

If I highlight text in another window (tested Firefox and Update Manager so far), I can move the mouse back and forth all I want and it doesn't freeze. It will get laggy as hell, especially if I switch between them rapidly, and sometimes will appear it has hung, but it has recovered after a few seconds every time.

Clarification of hang/freeze: The synergyc process is still running according to 'ps aux', but I can not kill it or affect it with any other signals. The syn server does not report the client died, but I can see it's being ignored as though it's not active. In v1.7.3, I could see some logging process synergy was waiting on when it was hung, but I can't tell what 1.7.4 is waiting on. I can launch a new synergyc process and it works, but I have to log out of my session to actually end the hung synergyc process.

I do not have drag-n-drop enabled on the client and I'm not using SSL

Forgot to add: even with DEBUG2 logging, the client logs an entry about the log file it's using, then "ERROR: dup error 2" and nothing else after that. Server log indicates movement and clipboard copying as normal, but nothing significant with the times it freezes vs times it doesn't

**Comment by XinyuHou** [comment]
Please try this pull request
https://github.com/synergy/synergy/pull/4994

Duplicate to #4735
