### ISSUE TITLE
how fix ubuntu 14.04

### ISSUE THREAD

**Issue by kobeng** [synergy/synergy#5092]
Error: /usr/bin/syntool: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/syntool)

**Comment by XinyuHou** [comment]
Please check our wiki page or use our mailing list for compiling your own Synergy.

https://github.com/synergy/synergy/wiki/Compiling
https://groups.google.com/forum/#!forum/synergy-dev
