### ISSUE TITLE
Synergy server running on os x server sends both left/right alt (alt/altgr) as left alt (alt)

### ISSUE THREAD

**Issue by patrikaxelsson** [synergy/synergy#5101]
This is a problem on windows clients using a non-US keyboard layout where you need altgr to enter characters like backslash (\). When checking what the server sends, it sends the same keyCode=0x38, modifiers=0x0010 for both left and right alt.

This is related to #5098.

**Comment by LeadManPL** [comment]
This may be also reason for impossibility to input diacritic letters (with AltGr) on windows

**Comment by XinyuHou** [comment]
Duplicate to #4411
