### ISSUE TITLE
Non US keyboards

### ISSUE THREAD

**Issue by MihaMarkic** [synergy/synergy#5102]
I have a Windows 10 with Slovene keyboard acting as server and OSX with custom Slovene keyboard mappings as client.
The thing is that keys on OSX aren't the same as those in Windows. Is there a setting to fix this or any other workaround?

**Comment by XinyuHou** [comment]
Related to #4280, please comment in the related issue.

@MihaMarkic 
I can see a Linux work around, not sure about Mac and Windows.
