### ISSUE TITLE
please review! (Re: #5097)

### ISSUE THREAD

**Issue by teelittle** [synergy/synergy#5111]
Hi there, 

last week, the-wes closed issue #5097 (which had been opened by me). 
In my opinion the answer given did not match the issue (as expressed in my comment https://github.com/synergy/synergy/issues/5097#issuecomment-155925807 ), and therefore I would like someone to re-open that issue (I found no way to do it myself). 

Kind regards, 
TeeLitte

**Comment by the-wes** [comment]
replied in #5097
