### ISSUE TITLE
Hdmi switch question

### ISSUE THREAD

**Issue by AeonLucid** [synergy/synergy#5112]
Hi,

I want to purchase synergy so I can use it as a virtual KVM between my windows and osx computer.
My current setup on windows is;

1. hdmi 1920x1080 (main) - 2. vga 1600x900 (second)

Monitor 1 is hooked on a hdmi switch with the osx pc. Would I be able to use synergy for when I switch to osx on my main monitor and then return to normal usage after I switch back to windows, whilst keeping windows on my second at all times?

Sorry if the question is a bit weird formatted.

**Comment by XinyuHou** [comment]
This looks like a support ticket. Please contact our help desk or forum.
http://synergy-project.org/forum/
https://synergy-project.org/contact/
