### ISSUE TITLE
Mouse movement impared

### ISSUE THREAD

**Issue by zooid** [synergy/synergy#5115]
After shutting down the second PC Mouse movement is impaired, slowed, while moving the cursor along the edge of the screen that should transfer to the other desktop.

The problem disappears after restart

OS - Windows 7 on both PCs

**Comment by XinyuHou** [comment]
Please give us more details about this issue. 

Here is a guild for raising an issue. 
https://github.com/synergy/synergy/wiki/Issues

This issue will be closed until we have more information.
