### ISSUE TITLE
Causes VAC Errors inside Counter-strike:Global Offensive

### ISSUE THREAD

**Issue by zooid** [synergy/synergy#5116]
After shutting down a secondary PC, random VAC errors start to appear while playing on secured CSGO servers.

OS Windows 7 x64 Ultimate on both PCs

Problem disappears after restart.

This is unconfirmed issue, because of the randomness of it's appearance. Probably cause by the randomness of the servers in CSGO matchmaking.

**Comment by XinyuHou** [comment]
Please give us more details about this issue. 

Here is a guild for raising an issue. 
https://github.com/synergy/synergy/wiki/Issues

This issue will be closed until we have more information.
