### ISSUE TITLE
Connecting & Switching Issue 

### ISSUE THREAD

**Issue by saaiful** [synergy/synergy#5121]
I'm using latest version of synergy on my windows 10 pcs. synergy connects easily sometime and sometime i need to restart synergy service in both pc. in my server pc it says 
`[2015-11-22T14:27:44] INFO: drag and drop enabled
[2015-11-22T14:27:44] INFO: watchdog status: ok
[2015-11-22T14:27:44] NOTE: started server, waiting for clients
`

In my client pc it says "No route to host/  Connected and Disconnected without any reason / connection refused .  

Another issue is clipboard. It works sometime in both pc and sometime only i can copy from my server to client , but client to server copy not updating clipboard. 

And the most important issue is it's too slow while it copy clipboard from one pc to another. i'm using  synergy since 2009 , but i never faced this type of issue before 2015.

**Comment by XinyuHou** [comment]
Please give us more details about this issue. 

Here is a guild for raising an issue. 
https://github.com/synergy/synergy/wiki/Issues

This issue will be closed until we have more information.

Please try 1.7.5 which as clipboard fixes.
