### ISSUE TITLE
Failure conditions exist

### ISSUE THREAD

**Issue by yinlianwei** [synergy/synergy#5124]
linux as a server, when installing the software on windows, pop-authorization page will fail. 'Setup Wizard page' mouse clicks will fail

`server:` Linux evenvi-desktop-pc 3.16.0-53-generic #72~14.04.1-Ubuntu SMP Fri Nov 6 18:17:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
`client:`  windows 10 Professional Edition 1151(11586.11)
`synergy version:` 1.7.5

**Comment by XinyuHou** [comment]
Please give us more details about this issue. 

Here is a guild for raising an issue. 
https://github.com/synergy/synergy/wiki/Issues

This issue will be closed until we have more information.
