### ISSUE TITLE
Client is dead

### ISSUE THREAD

**Issue by GeoHolz** [synergy/synergy#5127]
Hello,

I have Synergy Pro Server on Windows 7 : 1.7.5 and client under Debian 1.7.5

Sometime ( 1O-20 times per day ) client disconnect, logs say nothing. I need to stop and restart the client.

I have this problem since 1.7.4.

If i install the 1.7.1 on my Debian client, it's works ! No problem.. ( but clipboard and ssl doesn't works )

I try client 1.8, server 1.8, nighty builds, ...

Can u help me ?

On Server:
[2015-11-24T08:29:52] INFO: entering screen
[2015-11-24T08:30:01] NOTE: client "Linux" is dead

On Client :
[2015-11-24T08:29:52] INFO: leaving screen
[2015-11-24T08:30:01] DEBUG: ssl connection closed

So i plug an mouse on Client, click Stop on the GUI, click Start and it's Ok

**Comment by nicklozon** [comment]
Identical issue here.

Windows 10 server and Arch Linux client, both running 1.75.

It will work flawlessly for a while, then jumping back from the client to the server reports that the client is dead. No log file on the client, the process will just die. I tried wrapping the process in supervisor, but to no avail.

Server:
[2015-11-25T19:08:36] NOTE: client "nick-laptop" is dead
[2015-11-25T19:08:36] INFO: jump from "nick-laptop" to "Nick-PC" at 840,525
[2015-11-25T19:08:36] INFO: entering screen

Client: 
[2015-11-25T19:08:18] INFO: leaving screen

**Comment by XinyuHou** [comment]
@nicklozon @GeoHolz 

I believe this issue is duplicate to #4768

Please test this nightly and leave feedback in another issue
http://synergy-project.org/nightly?filter=synergy-v1.7.6-rc1-abba6
