### ISSUE TITLE
Clipboard Not Updating 1.7.5

### ISSUE THREAD

**Issue by Jiinxt** [synergy/synergy#5129]
The server clipboard no longer updates the client clipboard. I know it is copied because I can copy and paste on the server, but as soon as I try to move to the client it no longer has updated clipboard.

**Comment by Damien0505** [comment]
Similar issue, cannot copy or paste on server or client while Synergy 1.7.5 is running.

Server: Windows 7 Ultimate 64-bit
Client:  FC 22 4.2.6-200 kernel 64-bit

**Comment by nyetwurk** [comment]
Guys there are already MULTIPLE bugs open for this issue. Please do not open bugs that are already being tracked. #4735 #4994 #5041

**Comment by XinyuHou** [comment]
Duplicate
