### ISSUE TITLE
Missing circumflex

### ISSUE THREAD

**Issue by anders-sjoegren** [synergy/synergy#5134]
I am using Synergy Pro 1.7.4, server on Kubuntu 15.10 and client on Windows 7. Swedish keyboards on both.
Referring to #4214: In my case equal sign and curly braces work on the Windows client (using the server keyboard), but not circumflex.
As I am working with Latex a lot the missing circumflex is frustrating.
A workaround would be great!

On Kubuntu server:
locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

On Windows client:
Current system locale is Swedish

**Comment by XinyuHou** [comment]
Duplicate to #4280
