### ISSUE TITLE
Display Scaling not handled correctly

### ISSUE THREAD

**Issue by matthiasg** [synergy/synergy#5135]
Windows 10 64bit

When a screen (the right-most one on the server in my case) has display scaling set (was 150% in my case) then moving out from that monitor to the right onto the client works fine. moving back though does not (it seems to misinterpret that as a region not part of the server's desktop).

when setting scaling to 100% it works fine.

**Comment by XinyuHou** [comment]
This should be fixed in 1.7.5
Duplicate to #5030
