### ISSUE TITLE
Easier way to manage finding the mouse

### ISSUE THREAD

**Issue by iiyt** [synergy/synergy#5137]
I have 4 screens, and often loose the mouse. Rather than make it easy to locate, add a hot key that brings it back to center of my main screen. That will be instantaneous, and I can move it from there. It would be super helpful.

**Comment by XinyuHou** [comment]
Please try hotkeys in configure server.

**Comment by iiyt** [comment]
It does not get the job done.  All my computers have multiple screens, so even if I set it to go to my main server, I can't find it.  What would be better is for a hot key to bring my cursor to a specific point on a specific computer.  That would be excellent.
