### ISSUE TITLE
are free versions not working? 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [synergy/synergy#5142]
I am using free version on Ubuntu 14.04 and El Captain. But, they doesn't seem to connect. 

Synergy says "can't connect to the server" there are configuration problem. 

I was wondering if there were really the step/configuration issues or the old free versions doesn't work?

**Comment by Malcolmlowe** [comment]
Hi,

The free versions should work fine, this will be a setup issue. I suggest
posting on our forums or looking at http://synergy-project.org/help/ and
seeing what issues you're having!

Thanks,

--
Malcolm Lowe
Sales Manager
Synergy Seamless Inc.
synergy-project.org

<http://synergy-project.org/>

*US:* +1 650-265-2044
*EU:* +44 (0)20 3598 3068
*Skype*: MalcolmLowe85 <http://is.gd/W4GL3p>

*Synergy:* Combine your desktop devices together in to one cohesive
experience. Synergy is software for sharing your mouse and keyboard between
multiple computers on your desk. It works on Windows, Mac OS X and Linux.
synergy-project.org

**Comment by XinyuHou** [comment]
@AbhimanyuAryan 
This should be a support ticket. Please use our help desk. 

http://synergy-project.org/help/

**Comment by AbhimanyuAryan** [comment]
Ok I'll post on the forum. Thanks.
