### ISSUE TITLE
conflict with source insight software

### ISSUE THREAD

**Issue by sosobiao** [synergy/synergy#5149]
When  I use mouse to select  contents in the source insight (a source code edit IDE ), if I pressed a shift key once, I can't select the contents by mouse any more. 

Shut down the process of synergy, It comes ok.

system:   windows 10   X64

**Comment by XinyuHou** [comment]
Duplicate to #4493

Please give us more details about this issue. 

Here is a guild for raising an issue. 
https://github.com/synergy/synergy/wiki/Issues

This issue will be closed until we have more information.

**Comment by sosobiao** [comment]
sorry for my poor english ，I will use chinese first and then english。 @XinyuHou  looks like a chinese name.
~~~~~~~~~~~~~~~~~~~~~~~chinese~~~~~~~~~~~~~~~~~~
1 在开机自动启动synergy的时候，后台会有两个进程： synergys.exe(32bit) synergyd.exe(32bit)
    这个时候打开sourceinsight 软件，按住鼠标左键拖拽选择任何区域的代码或文字是可以正常选择的。
    按一次shift按键松开，当前焦点还在sourinsight这个软件上，鼠标左键拖拽不再能选择任何文字。
2  将焦点切换到任何地方，在回到soureinsight这个软件，恢复正常，再按下shift按键 松开，鼠标左键不再可以选择任何文字区域。
3.关闭synergys.exe(32bit) 进程 异常消失。

**Comment by sosobiao** [comment]
1 When I start up the win10 (x64)system, there will be to process:  synergys.exe(32bit) synergyd.exe(32bit). Open the software sourceinsight, I can use the left button of the mouse to select  any words in the windows. press down the shift key and released, keep the current focus on the sourceinsight, I can't use the left mouse key to select any words by keep button down dragging.
2 Swap the current focus on any other windows but sourceinsight, then focus back, The left button dragging select works well ,press shift key and released , clash again。
3. shutdown the synergys.exe(32bit) , nice world again.
