### ISSUE TITLE
conflict with source insight software

### ISSUE THREAD

**Issue by sosobiao** [synergy/synergy#5154]
1 When I start up the win10 (x64)system, there will be two process: synergys.exe(32bit) synergyd.exe(32bit). Open the software sourceinsight, I can use the left button of the mouse to select any words in the windows. press down the shift key and released, keep the current focus on the sourceinsight, I can't use the left mouse key to select any words by keep button down dragging.
2 Swap the current focus on any other windows but sourceinsight, then focus back, The left button dragging select works well ,press shift key and released , clash again。
3. shutdown the synergys.exe(32bit) , nice world .

chinese：
1 在开机自动启动synergy的时候，后台会有两个进程： synergys.exe(32bit) synergyd.exe(32bit)
    这个时候打开sourceinsight 软件，按住鼠标左键拖拽选择任何区域的代码或文字是可以正常选择的。
    按一次shift按键松开，当前焦点还在sourinsight这个软件上，鼠标左键拖拽不再能选择任何文字。
2  将焦点切换到任何地方，在回到soureinsight这个软件，恢复正常，再按下shift按键 松开，鼠标左键不再可以选择任何文字区域。
3.关闭synergys.exe(32bit) 进程 异常消失。

@XinyuHou

**Comment by XinyuHou** [comment]
@sosobiao 
If this only affects sourinsight, then it's a software specific bug. We can only do limited work to get fix it.

If it's a general problem, it's probably related to this #4057.
