### ISSUE TITLE
The specified address is not available from the local machine

### ISSUE THREAD

**Issue by howardjones** [synergy/synergy#5159]
Synergy 1.7.5 on Windows 7 - I get an error message: "FATAL: failed to start server: cannot bind address: The specified address is not available from the local machine"

Thing is, I didn't specify the address. In fact, I can't see how to do that in the config file or UI. So Synergy is picking a non-existent address and then failing to bind to it! I do have quite a few network interfaces, and a few of them don't actually go anywhere (loopback or VM-related interfaces). There's nothing I could see in the manual to say what the bold address in the list means, but the one in bold is a VM-related NIC, not an actual LAN connection, in case it's relevant. I'm manually entering the (correct) IP for the server on my client, not auto-config.

This all did work when I first installed Synergy yesterday, but now fails reliably, even across reboots.

**Comment by XinyuHou** [comment]
This looks like a support ticket. Please contact our help desk or forum.
http://synergy-project.org/forum/
https://synergy-project.org/contact/
