### ISSUE TITLE
app tray icon is on the left side Ubuntu Unity

### ISSUE THREAD

**Issue by Goddard** [synergy/synergy#5164]
I am using 14.04 and the system tray icon is on the left side of the top panel.  It is right over where the x is. 

This was on a self-compiled version.  Not sure if I needed to do an additional step for this method.

I assume you can fix this?

**Comment by XinyuHou** [comment]
Please give us more details about this issue. 

Here is a guide for raising an issue. 
https://github.com/synergy/synergy/wiki/Issues

This issue will be closed until we have more information.

**Comment by Goddard** [comment]
It is pretty clear unless you are a douche bag that doesn't care.

Here is a guide to use your brain
https://dontbeadouchebag.com

This issue will be closed because you are to lazy to read.
