### ISSUE TITLE
Scrolling Issue

### ISSUE THREAD

**Issue by PedroContipelli** [synergy/synergy#5170]
My setup consists of a Windows 7 server and Ubuntu 14.04 LTS client. While I am playing league of legends (fullscreen) on my server, if I go to my client and scroll up/down on a webpage. It will zoom me in/out of my character (which happens when scrolling the mouse wheel). It's not a major issue, but fixing it would make life a bit easier.

The only options I have changed (which are off by default) are:
- Check clients every 5000 ms
- Don't take foreground window on Windows servers

**Comment by XinyuHou** [comment]
Duplicate to #4981
