### ISSUE TITLE
The button 'start' not refresh (to 'Stop) if launch the GUI when 'synergys' is running in background

### ISSUE THREAD

**Issue by sl1pkn07** [synergy/synergy#5171]
Hi

Server Archlinux (1.7.4) (GUI builded in Qt5)
Plasma 5

If it is launched 'synergys' with the system, and it open the GUI, the button 'Start' is show 'Start' when should be show 'Stop'

If press the button, the service is stopped, and the button show "Start", if press again, then the service is starting and the button is changed to show 'Stop'

Greetings

**Comment by XinyuHou** [comment]
Duplicate to #4955
