### ISSUE TITLE
Frequent crashes on Arch Linux with synergy as a client

### ISSUE THREAD

**Issue by JoKoT3** [synergy/synergy#5173]
I encounter multiple crashes a day with synergy as a client on arch linux.
synergyc version 1.7.5 
DM : GDM and WM : gnome-shell
started with synergyc -d DEBUG --restart --no-tray
synergys version 1.7.5 on windows 7

There is 2 kind of behavior:
- synergyc crashes, SIGSEGV: happens frequently after locking both server and client screen, but sometimes when it's not locked.
- can't move mouse on the client screen (stuck at the border of the server screen): have to kill / restart synergyc to regain control

coredump provided
[coredump.zip](https://github.com/synergy/synergy/files/78324/coredump.zip)

**Comment by acidicX** [comment]
Same issue here on arch, DM=mdm, DE = cinnamon
Server is also on arch, crashes even more often :)

**Comment by XinyuHou** [comment]
@JoKoT3 @acidicX 
Please try our 1.7.6 nightly
http://synergy-project.org/nightly?filter=v1.7.6-rc3-51705f7

Duplicate to #4735
