### ISSUE TITLE
@ now working on Win7 Client with Ubuntu 15.04 Server

### ISSUE THREAD

**Issue by vhgarandil** [synergy/synergy#5177]
Since 1.7.3 alt-gr + 2 (which is according to my keyboard layout is where @ is located) has not been working.

Currently I'm running 1.7.4 with Ubuntu 15.04 X86_64 as server and Windows 7 as client.

The logs does not give any indication as to what the issue might be.

I've been roaming around for a solution without being able to find one.

Any hints towards getting this working is greatly appreciated.

**Comment by XinyuHou** [comment]
This might be duplicated to  #4280.

@vhgarandil 
Could you give us more detail? 

Here is a guide for raising an issue. 
https://github.com/synergy/synergy/wiki/Issues

This issue will be closed until we have more information.
