### ISSUE TITLE
Occasional random "Server is dead" 

### ISSUE THREAD

**Issue by umumpaul** [synergy/synergy#5179]
Server: Win8
Client: CentOS 6.5
*Synergy version 1.7.5

It looks like after "Server is dead", client will stop trying again. Until I click on "Apply" (by client's own mouse, of course), then client is reconnect back to Server. Is it possible to automatically do this action without user intervene for like every second after Server is dead state (which obviously not)

**Comment by hthao** [comment]
I have the same problem too.
Server: Win7 X64
client: ubuntu 14.04
synergy version: 1.7.5

**Comment by XinyuHou** [comment]
Duplicate to #4768
