### ISSUE TITLE
Unending stream of random input sent to client by server when server suspends

### ISSUE THREAD

**Issue by ShirajG** [synergy/synergy#5184]
Using 1.7.5-1 on Ubuntu 14.04, when I put my laptop(server) to sleep, all kinds of random input gets sent to the client. Waking the laptop immediately stops the random input.

**Comment by XinyuHou** [comment]
Please give us more details about this issue. Some log would be helpful.

Here is a guide for raising an issue. 
https://github.com/synergy/synergy/wiki/Issues

This issue will be closed until we have more information.
