### ISSUE TITLE
Configurable "detent" at machine borders to improve usability for menus taskbars

### ISSUE THREAD

**Issue by dmland** [synergy/synergy#5193]
When two computers are stacked vertically (especially when one or both are Macs), it can be a little tricky to get to the menubar at the top of the bottom computer, or at the auto-hidden taskbar at the bottom of the upper computer, because the mouse so easily slides across the border to the adjoining computer.

I'd like a "detent" at the border between the computers so that there's a bit of hesitation that keeps the mouse from crossing over without the user expressing a little bit more intent than just sliding 1px up or down.

Ideally it would be configurable: at a minimum with an on/off toggle, but ideally with a number of pixels that the mouse needs to travel to "break through" the border.

This would make it easier to access the menubar that the top of the bottom computer, or the taskbar at the bottom of the upper computer.

**Comment by XinyuHou** [comment]
Check configure server -> advanced server settings -> switch -> switch after waiting

**Comment by XinyuHou** [comment]
This looks like a support ticket. Please contact our help desk or forum.
http://synergy-project.org/forum/
https://synergy-project.org/contact/
